ALTER TYPE "XeroSyncType" ADD VALUE IF NOT EXISTS 'INVOICE_PAYMENT';
ALTER TYPE "XeroSyncType" ADD VALUE IF NOT EXISTS 'BILL_ATTACHMENT';
ALTER TYPE "XeroSyncType" ADD VALUE IF NOT EXISTS 'INVOICE_PDF';
ALTER TYPE "XeroSyncType" ADD VALUE IF NOT EXISTS 'INVOICE_EMAIL';
ALTER TYPE "XeroSyncType" ADD VALUE IF NOT EXISTS 'WC_INVOICE_NOTE';

CREATE INDEX IF NOT EXISTS "activity_logs_level_createdAt_idx"
ON "activity_logs"("level", "createdAt");
