-- o3d-peh1 r7: fence the QuickBooks operations whose replay REPEATS A REAL-WORLD EFFECT.
--
-- Four accounting sync types post no document and carry no remote request id: BILL_ATTACHMENT,
-- INVOICE_PDF, INVOICE_EMAIL and WC_INVOICE_NOTE. They upload a file, save a PDF, send an EMAIL to
-- a customer, write a note onto a WooCommerce order. Nothing on the far side collapses a second
-- attempt into the first.
--
-- When such an operation succeeded and EVERY write that would have recorded it refused, the row was
-- left PROCESSING holding its claim. Fifteen minutes later the ordinary sweep reclaimed it as a
-- stale claim and ran the operation AGAIN -- and again on the sweep after that, unbounded, because
-- no retry is consumed by a row that never leaves PROCESSING. The escalation filed for it was a log
-- line, not a fence.
--
-- This column is that fence. It is stamped BY THE CLAIM, before anything is dispatched, and only for
-- those four types; the sweep's candidate and claim predicates both require it to be NULL, so a row
-- carrying it cannot be reclaimed. It is cleared by every write that records the attempt's outcome,
-- which is what keeps ordinary counted retries working.
--
-- It is deliberately not a status. Writing PENDING or FAILED over a row whose operation SUCCEEDED
-- would record a failure that did not happen; this records the thing that is true either way -- the
-- effect was dispatched and must not be dispatched again.
--
-- Nullable with no default, so this is metadata-only on Postgres 11+ and no historical row is
-- asserted about.
ALTER TABLE "accounting_sync_logs"
  ADD COLUMN "non_replayable_attempt_at" TIMESTAMP(3);
