import { registerCronJobs } from '@/lib/cron-registry'

registerCronJobs([
  {
    slug: 'backup',
    settingKey: 'backup',
    module: 'system',
    moduleLabel: 'System',
    label: 'Database Backup',
    description: 'Creates a scheduled PostgreSQL database backup and purges old files.',
    defaultSchedule: '0 1 * * *',
    defaultEnabled: false,
    legacyEnabledKey: 'backup_schedule_enabled',
  },
  {
    slug: 'activity-cleanup',
    settingKey: 'activity_cleanup',
    module: 'system',
    moduleLabel: 'System',
    label: 'Activity Log Cleanup',
    description: 'Archives old activity log entries based on retention settings.',
    defaultSchedule: '0 3 * * *',
    defaultEnabled: true,
  },
  {
    slug: 'fx-rates',
    settingKey: 'fx_rates',
    module: 'system',
    moduleLabel: 'System',
    label: 'FX Rate Update',
    description: 'Fetches daily exchange rates from the ECB via frankfurter.dev.',
    defaultSchedule: '0 7 * * *',
    defaultEnabled: true,
  },
  {
    slug: 'invariant-check',
    settingKey: 'invariant_check',
    module: 'system',
    moduleLabel: 'System',
    label: 'Invariant Check',
    description: 'Runs inventory and accounting invariant reports and logs critical findings.',
    defaultSchedule: '0 4 * * *',
    defaultEnabled: true,
  },
  {
    slug: 'inventory-snapshot',
    settingKey: 'inventory_snapshot',
    module: 'system',
    moduleLabel: 'System',
    label: 'Inventory Snapshot',
    description: 'Writes daily product/warehouse on-hand quantity and value snapshots for inventory analytics.',
    defaultSchedule: '0 0 * * *',
    defaultEnabled: false,
  },
  {
    slug: 'recompute-product-lead-times',
    settingKey: 'recompute_product_lead_times',
    module: 'system',
    moduleLabel: 'System',
    label: 'Recompute Product Lead Times',
    description: 'Recomputes each product\'s observed lead time (P95 of PO receipt times over the last 365 days) used by the Reorder Planning report when no manual override is set.',
    defaultSchedule: '0 4 * * *',
    defaultEnabled: true,
  },
  {
    slug: 'product-lifecycle-archive',
    settingKey: 'product_lifecycle_archive',
    module: 'system',
    moduleLabel: 'System',
    label: 'Product Lifecycle Archive',
    description: 'Archives EOL products after stock and incoming supply are depleted.',
    defaultSchedule: '30 0 * * *',
    defaultEnabled: true,
  },
  {
    slug: 'delivery-status',
    settingKey: 'delivery_status',
    module: 'system',
    moduleLabel: 'System',
    label: 'Delivery Status Check',
    description: 'Polls carrier APIs for delivery status updates on shipped orders.',
    defaultSchedule: '*/15 * * * *',
    defaultEnabled: true,
  },
  {
    slug: 'refund-reservation-release',
    settingKey: 'refund_reservation_release',
    module: 'system',
    moduleLabel: 'System',
    label: 'Refund Reservation Release',
    description: 'Durable backstop that re-runs allocation to release stock reservations for refunded units when the immediate post-refund release was bypassed or lost (o3d-67y).',
    defaultSchedule: '*/15 * * * *',
    defaultEnabled: true,
  },
  {
    slug: 'reallocation-sweep',
    settingKey: 'reallocation_sweep',
    module: 'system',
    moduleLabel: 'System',
    label: 'Reallocation Sweep',
    description: 'Re-runs allocation for PROCESSING orders left with outstanding demand — e.g. a paid order whose allocation failed transiently in a payment poller and would otherwise never be retried (o3d-9lx). Also finishes the allocation-coverage check for orders a storefront created directly at Picking or Packing, which no status transition examines (o3d-z82a).',
    defaultSchedule: '*/15 * * * *',
    defaultEnabled: true,
  },
])
