import { registerCronJobs } from '@/lib/cron-registry'

registerCronJobs([
  {
    slug: 'accounting-sync',
    settingKey: 'xero_sync',
    module: 'accounting',
    moduleLabel: 'Accounting',
    label: 'Accounting Sync Queue',
    description: 'Processes pending accounting sync entries and posts them to the active connector.',
    defaultSchedule: '*/5 * * * *',
    defaultEnabled: true,
  },
  {
    slug: 'account-balance-snapshot',
    settingKey: 'xero_account_balance_snapshot',
    module: 'accounting',
    moduleLabel: 'Accounting',
    label: 'Account Balance Snapshot',
    description: 'Fetches Xero Trial Balance account balances for GL variance reporting.',
    defaultSchedule: '0 1 * * *',
    defaultEnabled: true,
  },
  {
    slug: 'accounting-daily-batch',
    settingKey: 'xero_daily_batch',
    module: 'accounting',
    moduleLabel: 'Accounting',
    label: 'Accounting Daily Batch',
    description: 'Runs the daily accounting sub-ledger batch sync through the active connector.',
    defaultSchedule: '0 2 * * *',
    defaultEnabled: true,
  },
  {
    slug: 'accounting-payment-poll',
    settingKey: 'xero_payment_poll',
    module: 'accounting',
    moduleLabel: 'Accounting',
    label: 'Accounting Payment Poll',
    description: 'Polls the active accounting connector for payment status changes and reconciles invoices.',
    defaultSchedule: '*/15 * * * *',
    defaultEnabled: true,
  },
  {
    slug: 'xero-tax-rate-drift',
    settingKey: 'xero_tax_rate_drift',
    module: 'accounting',
    moduleLabel: 'Accounting',
    label: 'Xero Tax Rate Drift Detection',
    description: 'Compares active IMS tax rates against the live Xero rates and logs a warning when a rate was edited directly in Xero (alert-only).',
    defaultSchedule: '0 * * * *',
    defaultEnabled: true,
  },
])
