import assert from 'node:assert/strict'
import test from 'node:test'

import { getSidebarAnalyticsChildren } from '../../components/layout/sidebar.tsx'
import type { Role } from '../../lib/permissions.ts'

const EXPECTED_ANALYTICS_HREFS: Record<Exclude<Role, 'SUPPLIER'>, string[]> = {
  ADMIN: [
    '/analytics/sales-stats',
    '/analytics/purchase-stats',
    '/analytics/product-profitability',
    '/analytics/inventory-stats',
    '/analytics/stock-on-hand',
    '/analytics/inventory-aging',
    '/analytics/dead-stock',
    '/analytics/stock-allocations',
    '/analytics/negative-stock',
    '/analytics/reorder',
    '/analytics/backorder',
    '/analytics/component-shortage',
    '/analytics/sales',
    '/analytics/customers',
    '/analytics/margin',
    '/analytics/returns',
    '/analytics/fulfillment',
    '/analytics/throughput',
    '/analytics/open-pos',
    '/analytics/supplier-performance',
    '/analytics/ppv',
    '/analytics/spend',
    '/analytics/lead-times',
    '/analytics/vat',
    '/analytics/currency-summary',
    '/analytics/ar-aging',
    '/analytics/ap-aging',
    '/analytics/fx-gain-loss',
    '/analytics/production-variance',
    '/analytics/wip',
    '/analytics/stock-movements',
    '/analytics/stock-adjustments',
    '/analytics/transfers',
    '/analytics/stock-counts',
    '/analytics/inventory-valuation',
    '/analytics/cogs',
    '/analytics/landed-cost',
    '/analytics/inventory-turnover',
  ],
  MANAGER: [
    '/analytics/sales-stats',
    '/analytics/purchase-stats',
    '/analytics/product-profitability',
    '/analytics/inventory-stats',
    '/analytics/stock-on-hand',
    '/analytics/inventory-aging',
    '/analytics/dead-stock',
    '/analytics/stock-allocations',
    '/analytics/negative-stock',
    '/analytics/reorder',
    '/analytics/backorder',
    '/analytics/component-shortage',
    '/analytics/sales',
    '/analytics/customers',
    '/analytics/margin',
    '/analytics/returns',
    '/analytics/fulfillment',
    '/analytics/throughput',
    '/analytics/open-pos',
    '/analytics/supplier-performance',
    '/analytics/ppv',
    '/analytics/spend',
    '/analytics/lead-times',
    '/analytics/production-variance',
    '/analytics/wip',
    '/analytics/stock-movements',
    '/analytics/stock-adjustments',
    '/analytics/transfers',
    '/analytics/stock-counts',
    '/analytics/inventory-valuation',
    '/analytics/cogs',
    '/analytics/landed-cost',
    '/analytics/inventory-turnover',
  ],
  WAREHOUSE: [
    '/analytics/stock-on-hand',
    '/analytics/inventory-aging',
    '/analytics/dead-stock',
    '/analytics/stock-allocations',
    '/analytics/negative-stock',
    '/analytics/stock-movements',
    '/analytics/stock-adjustments',
    '/analytics/transfers',
    '/analytics/stock-counts',
  ],
  FINANCE: [
    '/analytics/sales-stats',
    '/analytics/purchase-stats',
    '/analytics/product-profitability',
    '/analytics/inventory-stats',
    '/analytics/stock-on-hand',
    '/analytics/inventory-aging',
    '/analytics/dead-stock',
    '/analytics/stock-allocations',
    '/analytics/negative-stock',
    '/analytics/reorder',
    '/analytics/backorder',
    '/analytics/component-shortage',
    '/analytics/sales',
    '/analytics/customers',
    '/analytics/margin',
    '/analytics/returns',
    '/analytics/fulfillment',
    '/analytics/throughput',
    '/analytics/open-pos',
    '/analytics/supplier-performance',
    '/analytics/ppv',
    '/analytics/spend',
    '/analytics/lead-times',
    '/analytics/vat',
    '/analytics/currency-summary',
    '/analytics/ar-aging',
    '/analytics/ap-aging',
    '/analytics/fx-gain-loss',
    '/analytics/production-variance',
    '/analytics/wip',
    '/analytics/stock-movements',
    '/analytics/stock-adjustments',
    '/analytics/transfers',
    '/analytics/stock-counts',
    '/analytics/inventory-valuation',
    '/analytics/cogs',
    '/analytics/landed-cost',
    '/analytics/inventory-turnover',
  ],
  READONLY: [
    '/analytics/sales-stats',
    '/analytics/purchase-stats',
    '/analytics/product-profitability',
    '/analytics/inventory-stats',
    '/analytics/stock-on-hand',
    '/analytics/inventory-aging',
    '/analytics/dead-stock',
    '/analytics/stock-allocations',
    '/analytics/negative-stock',
  ],
}

for (const [role, expectedHrefs] of Object.entries(EXPECTED_ANALYTICS_HREFS)) {
  test(`sidebar analytics links are scoped for ${role}`, () => {
    const hrefs = getSidebarAnalyticsChildren(role).map((link) => link.href)
    assert.deepEqual(hrefs, expectedHrefs)
    assert.equal(new Set(hrefs).size, hrefs.length)
  })
}

test('supplier sidebar has no dashboard analytics links', () => {
  assert.deepEqual(getSidebarAnalyticsChildren('SUPPLIER'), [])
})
