#!/usr/bin/env tsx
/**
 * o3d-y14: clear the DUPLICATED order-level coupon on legacy WooCommerce orders.
 *
 * All of the judgement lives in lib/connectors/woocommerce/sync/coupon-discount-backfill.ts — read
 * that file for why each decision is made. This is the reporting and driving shell.
 *
 * IT IS A TWO-PHASE, OPT-IN WORKFLOW, because it rewrites amounts on invoices that are already
 * posted to the ledger, and no field on a row distinguishes "written by the pre-fix importer" from
 * "corrected by hand afterwards" or "written by the fixed importer before it stamped the marker".
 * So a machine may PROPOSE, and only a human may APPROVE:
 *
 *   1. REPORT / PROPOSE (no writes)
 *        tsx scripts/backfill-wc-coupon-order-discount.ts \
 *          --imported-before 2026-07-25T14:00:00Z --allowlist-out y14-allowlist.json
 *
 *   2. REVIEW — see "WHAT A REVIEWER CHECKS" below. Move rows, delete rows, then sign the file.
 *
 *   3. APPLY (writes; consumes ONLY the reviewed file, never a fresh scan)
 *        tsx scripts/backfill-wc-coupon-order-discount.ts --allowlist y14-allowlist.json --apply
 *
 * WHAT A REVIEWER CHECKS, per entry:
 *   • `importedAt` vs the DEPLOYMENT RECORD. The cutoff must be the EARLIEST moment the fixed
 *     importer could have written a row on this instance — earlier is safe (fewer candidates),
 *     later silently sweeps in correct rows. Every entry with `"nearCutoff": true` is one the
 *     cutoff CHOICE decided rather than a comfortable margin; those are the markerless-interval
 *     risk and each needs an individual answer.
 *   • MANUAL CORRECTIONS. If this order's discount was ever fixed by hand (raw SQL, an ad-hoc
 *     script), its amount is ALREADY the residual: move the entry to `stampOnly`. Clearing it would
 *     subtract the line discounts a second time and then stamp the wrong figure permanently.
 *   • `storedOrderDiscount` / `lineDiscountTotal` / `keptOrderLevel` — does the residual make sense
 *     for that order's coupons? `"partial": true` means a residual SURVIVES; those are unmodelled
 *     coupon shapes and are worth opening individually.
 *   • `accountingInvoiceId` — non-null means the ledger document ALREADY understates. Clearing the
 *     IMS field does not reach it; each needs a manual credit/adjustment in the accounting system.
 *   • `postedInvoiceExternalIds` — SYNCED invoice jobs whose external id the order does NOT carry.
 *     A post can succeed and then fail to write its id back (o3d-9kek), so a non-empty list here
 *     with a null `accountingInvoiceId` is a REAL ledger document the column denies. Treat it
 *     exactly like `accountingInvoiceId`: it needs a manual credit/adjustment, and approving the
 *     entry is you saying you have seen it. Apply compares this list against live state and refuses
 *     if it has moved, so approving the row is what unsticks it — there is no separate repair to
 *     run first.
 *   • `revenueDeferredBatchRef` — non-null means a daily-batch Group A1 journal ALSO deferred this
 *     order's revenue using the same wrong discount, and stamped the result on the order. That is a
 *     SECOND document needing a manual adjustment, and the stamp stays stale after the correction.
 *   • Anything you are not sure about: DELETE the entry. Skipping is re-runnable; a wrong correction
 *     is not.
 *
 * Signing means setting `"reviewed": true` and `"reviewedBy": "<your name>"`. Apply refuses
 * otherwise. Apply also re-verifies every evidence field against the live row and RE-DERIVES the
 * amount it writes, so a row that moved between review and apply is SKIPPED, and an edited
 * `keptOrderLevel` causes a refusal rather than a write. `stampOnly` entries are re-verified just
 * as hard — amount, LINE discounts and import timestamp — because a stamp is the one write no later
 * run can reconsider (o3d-y14 r3 finding 3).
 *
 * EVERY REFUSAL IS RECOVERABLE BY RE-RUNNING THE REPORT, and that is a property rather than a hope:
 * a refusal writes nothing, and the report reads every field apply compares (posting state included,
 * o3d-y14 r3 finding 2), so the re-generated proposal shows the reviewer the state that caused the
 * refusal. Approve it again and apply proceeds. A file generated by an older build is refused on its
 * `version` instead, which is the same instruction: re-run the report.
 *
 * POSTING STATE IS NEVER READ FROM THE FILE. The allowlist decides WHICH ORDERS may be touched and
 * nothing else. What the accounting system holds is re-read at apply time under the correction's own
 * lock: a row whose posting state moved since the review is REFUSED, and the "needs a manual ledger
 * adjustment" list printed at the end is built from that live read. A file-derived list would report
 * an invoice posted between review and apply as unposted — telling the operator that nothing needs
 * fixing about the one order that most does.
 *
 * IT ONLY EVER TOUCHES SalesOrder.discountAmount + discountModel, and only on orders with a
 * WooCommerce link. It never touches the accounting queue: an order with unposted invoice work
 * (o3d-5ct) or an unposted daily revenue-deferral journal is DECLINED and reported.
 *
 * --imported-before is the moment the o3d-y14 importer fix went LIVE on this instance. It is dated
 * against ShoppingOrderLink.createdAt — when IMS imported the order — and never against
 * SalesOrder.createdAt, which the initial import backdates to the historical Woo order date.
 */
import { readFileSync, writeFileSync } from 'node:fs'

import { config } from 'dotenv'

import {
  WC_COUPON_BACKFILL_ACTION,
  WC_COUPON_MAX_CANDIDATES,
  WC_COUPON_SCAN_PAGE_SIZE,
  LIVE_SALES_INVOICE_STATUSES,
  POSTED_SALES_INVOICE_STATUSES,
  SALES_INVOICE_SYNC_TYPES,
  applyWcCouponCorrection,
  buildWcCouponAllowlistEntry,
  chunkWcCouponIds,
  collectWcCouponCandidates,
  decideWcCouponBackfill,
  isNearWcCouponCutoff,
  parseWcCouponAllowlist,
  parseWcCouponCutoff,
  sortedPostedInvoiceIds,
  stampWcCouponDiscountModel,
  sumLineDiscounts,
  wcCouponCorrectionNeedsLedgerAdjustment,
  type WcCouponAllowlist,
  type WcCouponAllowlistEntry,
  type WcCouponBackfillDecision,
  type WcCouponBackfillRow,
  type WcCouponPostedEvidence,
} from '../lib/connectors/woocommerce/sync/coupon-discount-backfill'
import { liveDailyBatchDeferralWhere } from '../lib/domain/accounting/daily-batch-discount-fence'

// .env MUST load before lib/db is imported: that module builds its pg Pool from
// process.env.DATABASE_URL at IMPORT time (see scripts/backfill-refund-basis.ts).
config({ path: '.env.local', quiet: true })
config({ quiet: true })

const APPLY = process.argv.includes('--apply')

function flagValue(name: string): string | null {
  const index = process.argv.indexOf(`--${name}`)
  return index >= 0 ? (process.argv[index + 1] ?? null) : null
}

const LOG = '[backfill-wc-coupon-order-discount]'

// ---------------------------------------------------------------------------
// APPLY — consumes the reviewed allowlist and nothing else
// ---------------------------------------------------------------------------

async function apply(allowlistPath: string) {
  const { db } = await import('../lib/db/index')

  let parsedJson: unknown
  try {
    parsedJson = JSON.parse(readFileSync(allowlistPath, 'utf8'))
  } catch (error) {
    console.error(`${LOG} could not read ${allowlistPath}: ${String(error)}`)
    process.exitCode = 1
    return
  }

  const parsed = parseWcCouponAllowlist(parsedJson)
  if (!parsed.ok) {
    console.error(`${LOG} REFUSING to apply ${allowlistPath}: ${parsed.reason} — ${parsed.detail}`)
    process.exitCode = 1
    return
  }
  const allowlist = parsed.allowlist

  console.log(`${LOG} mode: APPLY`)
  console.log(
    `${LOG} allowlist: ${allowlistPath} — generated ${allowlist.generatedAt || '(unrecorded)'} under cutoff ` +
      `${allowlist.cutoff || '(unrecorded)'}, reviewed by ${allowlist.reviewedBy}` +
      (allowlist.reviewedAt ? ` on ${allowlist.reviewedAt}` : ''),
  )
  console.log(
    `${LOG} ${allowlist.stampOnly.length} order(s) to STAMP as already-correct, ` +
      `${allowlist.clear.length} to CLEAR. No other order can be touched by this run.`,
  )

  // STAMP FIRST, deliberately. A stamped row is excluded from every later run by its own evidence
  // rather than by anyone remembering to exclude it — so if this run dies half way, the rows that
  // must never be re-derived are the ones already protected.
  let stamped = 0
  const declined: string[] = []
  for (const entry of allowlist.stampOnly) {
    const result = await db.$transaction((tx) => stampWcCouponDiscountModel(tx, entry))
    if (result.outcome === 'CORRECTED') stamped += 1
    else declined.push(`stamp ${entry.orderNumber || entry.orderId}: ${result.reason} — ${result.detail}`)
  }

  let corrected = 0
  // The posting state reported here is the one READ AT APPLY TIME, under the same lock as the
  // correction — never `entry.accountingInvoiceId`. The allowlist is a list of WHICH ORDERS may be
  // touched; it was written when the proposal was generated and says nothing about what the ledger
  // holds now. An invoice queued after the review and posted before this run would be reported as
  // "not posted" from the file, and the operator would be told no manual ledger correction is
  // needed for the one order that most needs it (o3d-y14 r2).
  const posted: Array<{ entry: WcCouponAllowlistEntry; evidence: WcCouponPostedEvidence }> = []
  for (const entry of allowlist.clear) {
    const result = await db.$transaction((tx) => applyWcCouponCorrection(tx, entry))
    if (result.outcome === 'CORRECTED') {
      corrected += 1
      if (wcCouponCorrectionNeedsLedgerAdjustment(result.posted)) {
        posted.push({ entry, evidence: result.posted as WcCouponPostedEvidence })
      }
    } else {
      declined.push(`clear ${entry.orderNumber || entry.orderId}: ${result.reason} — ${result.detail}`)
    }
  }

  console.log('')
  console.log(
    `${LOG} stamped ${stamped} order(s) as already-correct; corrected ${corrected} order(s). ` +
      'No queued or posted accounting payload was modified.',
  )
  if (posted.length) {
    console.log(
      `${LOG} ${posted.length} corrected order(s) ALREADY HAVE ACCOUNTING DOCUMENTS derived from the old ` +
        'amount, read live at the moment of correction. Each still understates and needs a manual ' +
        'credit/adjustment — clearing the IMS field does not reach a posted document:',
    )
    for (const { entry, evidence } of posted) {
      const parts = [
        evidence.accountingInvoiceId ? `invoice ${evidence.accountingInvoiceId}` : null,
        evidence.postedInvoiceExternalIds.length
          ? `posted-but-unlinked invoice(s) ${evidence.postedInvoiceExternalIds.join(', ')}`
          : null,
        evidence.revenueDeferredBatchRef
          ? `revenue deferral ${evidence.revenueDeferredBatchRef} (unearned ${evidence.unearnedRevenueAmount})`
          : null,
      ].filter(Boolean)
      console.log(`${LOG}   posted: ${entry.orderNumber || entry.orderId} -> ${parts.join('; ')}`)
    }
  }
  if (declined.length) {
    console.log(
      `${LOG} ${declined.length} entr(ies) were declined at write time — the row no longer matches the ` +
        'evidence it was reviewed with, so it was left untouched. Re-run the report to re-propose them:',
    )
    for (const line of declined) console.log(`${LOG}   ${line}`)
  }
}

// ---------------------------------------------------------------------------
// REPORT / PROPOSE — never writes
// ---------------------------------------------------------------------------

async function report(importedBefore: Date | null, csvPath: string | null, allowlistOut: string | null) {
  const { db } = await import('../lib/db/index')

  console.log(`${LOG} mode: DRY RUN`)
  console.log(
    `${LOG} cutoff: ${
      importedBefore
        ? `orders IMPORTED (ShoppingOrderLink.createdAt) before ${importedBefore.toISOString()}`
        : '(none — every unstamped order will report as UNPROVEN)'
    }`,
  )

  // NO cutoff in this query. Scoping the SELECT by SalesOrder.createdAt is the o3d-9te bug: that
  // column is backdated to the Woo order date by the initial import. Provenance is decided per row,
  // from the link timestamp and the recorded discount model.
  //
  // KEYSET-PAGED, and capped (o3d-y14 r2 finding 3). The previous shape loaded every matching order
  // and every line in one statement, then used the whole id list in two more — which is bounded by
  // the catalogue rather than by the work, and past ~65k ids the `IN` lists stop being slow and
  // start being errors. Ordering is by id because that is what makes the keyset sound; the display
  // order is restored below, where it costs nothing.
  type ScannedOrder = Awaited<ReturnType<typeof scanPage>>[number]
  async function scanPage(afterId: string | null) {
    return await db.salesOrder.findMany({
      where: {
        discountAmount: { gt: 0 },
        shoppingLinks: { some: { connector: 'woocommerce' } },
        ...(afterId ? { id: { gt: afterId } } : {}),
      },
      select: {
        id: true,
        orderNumber: true,
        externalOrderNumber: true,
        currency: true,
        discountAmount: true,
        discountModel: true,
        accountingInvoiceId: true,
        revenueDeferredBatchRef: true,
        lines: { select: { discountAmount: true } },
        shoppingLinks: {
          where: { connector: 'woocommerce' },
          select: { createdAt: true },
          orderBy: { createdAt: 'asc' },
          take: 1,
        },
      },
      orderBy: { id: 'asc' },
      take: WC_COUPON_SCAN_PAGE_SIZE,
    })
  }

  const scan = await collectWcCouponCandidates<ScannedOrder>(scanPage)
  if (!scan.ok) {
    // REFUSE rather than truncate. A truncated proposal is indistinguishable from a complete one,
    // and the orders it silently omitted are the ones nobody will ever look at again.
    console.error(
      `${LOG} REFUSING: more than ${WC_COUPON_MAX_CANDIDATES} WooCommerce orders carry an order-level ` +
        `discount (${scan.scanned} scanned). That is far beyond any real catalogue, so the filter is wrong ` +
        'rather than the estate large — this backfill targets a defect affecting tens of orders. Nothing ' +
        'was written.',
    )
    process.exitCode = 1
    return
  }
  const orders = scan.rows
  // The scan order is by id; the reviewer reads by import date, which is the evidence they check.
  orders.sort((a, b) => (a.shoppingLinks[0]?.createdAt?.getTime() ?? 0) - (b.shoppingLinks[0]?.createdAt?.getTime() ?? 0))
  console.log(`${LOG} ${orders.length} WooCommerce order(s) carry an order-level discount`)

  const orderIds = orders.map((order) => order.id)

  // Chunked for the same reason the scan is paged: one `IN` list of every candidate is a statement
  // whose parameter count is set by the catalogue.
  const alreadyBackfilled = new Set<string>()
  for (const batch of chunkWcCouponIds(orderIds)) {
    const marks = await db.activityLog.findMany({
      where: { action: WC_COUPON_BACKFILL_ACTION, entityId: { in: batch } },
      select: { entityId: true },
    })
    for (const mark of marks) if (mark.entityId) alreadyBackfilled.add(mark.entityId)
  }

  const liveJobCounts = new Map<string, number>()
  for (const batch of chunkWcCouponIds(orderIds)) {
    const grouped = await db.accountingSyncLog.groupBy({
      by: ['referenceId'],
      where: {
        referenceType: 'SalesOrder',
        referenceId: { in: batch },
        type: { in: [...SALES_INVOICE_SYNC_TYPES] },
        status: { in: [...LIVE_SALES_INVOICE_STATUSES] },
      },
      _count: { _all: true },
    })
    for (const group of grouped) liveJobCounts.set(group.referenceId, group._count._all)
  }

  // POSTED-BUT-UNLINKED INVOICES (o3d-y14 r3 finding 2). Read here, in the REPORT, and not only at
  // apply time: apply refuses any row whose posting evidence has moved since the review, so evidence
  // the report cannot show is evidence the reviewer can never approve. The o3d-9kek shape — a post
  // that succeeded and then failed to write its id back — lives entirely in these rows and is
  // invisible in `accountingInvoiceId`, which is exactly why the previous revision re-proposed those
  // orders forever and refused them every time.
  const postedInvoiceIds = new Map<string, string[]>()
  for (const batch of chunkWcCouponIds(orderIds)) {
    const syncedRows = await db.accountingSyncLog.findMany({
      where: {
        referenceType: 'SalesOrder',
        referenceId: { in: batch },
        type: { in: [...SALES_INVOICE_SYNC_TYPES] },
        status: { in: [...POSTED_SALES_INVOICE_STATUSES] },
        externalTransactionId: { not: null },
      },
      select: { referenceId: true, externalTransactionId: true },
    })
    for (const row of syncedRows) {
      if (!row.externalTransactionId) continue
      postedInvoiceIds.set(row.referenceId, [
        ...(postedInvoiceIds.get(row.referenceId) ?? []),
        row.externalTransactionId,
      ])
    }
  }

  // The daily-batch producer (o3d-y14 r2 finding 1). Its rows are keyed on the BATCH, not on the
  // order, so they are looked up by the batch reference each order carries — an order-scoped query
  // of any shape would find none of them.
  const batchRefs = [...new Set(orders.map((order) => order.revenueDeferredBatchRef).filter((ref): ref is string => !!ref))]
  const liveBatchCounts = new Map<string, number>()
  for (const batch of chunkWcCouponIds(batchRefs)) {
    const grouped = await db.accountingSyncLog.groupBy({
      by: ['referenceId'],
      where: liveDailyBatchDeferralWhere(batch),
      _count: { _all: true },
    })
    for (const group of grouped) liveBatchCounts.set(group.referenceId, group._count._all)
  }

  const rows: Array<{ row: WcCouponBackfillRow; decision: WcCouponBackfillDecision }> = []
  for (const order of orders) {
    const row: WcCouponBackfillRow = {
      orderId: order.id,
      orderNumber: order.orderNumber ?? '',
      externalOrderNumber: order.externalOrderNumber ?? '',
      currency: order.currency,
      storedOrderDiscount: Number(order.discountAmount),
      lineDiscountTotal: sumLineDiscounts(order.lines),
      accountingInvoiceId: order.accountingInvoiceId,
      postedInvoiceExternalIds: sortedPostedInvoiceIds(postedInvoiceIds.get(order.id) ?? []),
      discountModel: order.discountModel,
      importedAt: order.shoppingLinks[0]?.createdAt ?? null,
      alreadyBackfilled: alreadyBackfilled.has(order.id),
      liveInvoiceJobs: liveJobCounts.get(order.id) ?? 0,
      revenueDeferredBatchRef: order.revenueDeferredBatchRef,
      liveBatchDeferralJobs: order.revenueDeferredBatchRef
        ? (liveBatchCounts.get(order.revenueDeferredBatchRef) ?? 0)
        : 0,
    }
    rows.push({ row, decision: decideWcCouponBackfill(row, { importedBefore }) })
  }

  type Entry<A extends WcCouponBackfillDecision['action']> = {
    row: WcCouponBackfillRow
    decision: Extract<WcCouponBackfillDecision, { action: A }>
  }
  function pick<A extends WcCouponBackfillDecision['action']>(action: A): Array<Entry<A>> {
    return rows.filter((entry): entry is Entry<A> => entry.decision.action === action)
  }
  const corrections = pick('CORRECT')
  const unproven = pick('UNPROVEN')
  const blocked = pick('BLOCKED')
  const skipped = pick('SKIP')

  console.log('')
  console.log('order              external   ccy    stored  onLines  keep   clear  posted  verdict')
  for (const { row, decision } of rows) {
    if (decision.action === 'SKIP' && decision.reason !== 'NOTHING_DUPLICATED') continue
    const keep = decision.action === 'CORRECT' ? String(decision.keptOrderLevel) : '-'
    const clear = decision.action === 'CORRECT' ? String(decision.clearedBy) : '-'
    const near = isNearWcCouponCutoff(row.importedAt, importedBefore) ? ' [NEAR CUTOFF]' : ''
    console.log(
      `${(row.orderNumber || row.orderId).padEnd(18)} ${row.externalOrderNumber.padEnd(10)} ` +
        `${row.currency.padEnd(6)} ${String(row.storedOrderDiscount).padStart(6)} ` +
        `${String(row.lineDiscountTotal).padStart(8)} ${keep.padStart(5)} ${clear.padStart(6)} ` +
        `${(row.accountingInvoiceId ? 'YES' : 'no').padEnd(7)} ${decision.action}` +
        (decision.action === 'CORRECT' ? (decision.partial ? ' (PARTIAL)' : '') : ` — ${decision.reason}`) +
        near,
    )
  }

  // Both accounting artefacts, not just the invoice: an order whose revenue deferral has already
  // been journaled has a SECOND document derived from the amount about to change (o3d-y14 r2).
  const postedCandidates = corrections.filter(
    (entry) =>
      entry.row.accountingInvoiceId ||
      entry.row.postedInvoiceExternalIds.length > 0 ||
      entry.row.revenueDeferredBatchRef,
  )
  const nearCutoff = corrections.filter((entry) => isNearWcCouponCutoff(entry.row.importedAt, importedBefore))
  console.log('')
  console.log(
    `${LOG} ${corrections.length} candidate(s) ` +
      `(${corrections.filter((e) => e.decision.action === 'CORRECT' && e.decision.partial).length} keep a residual), ` +
      `${skipped.length} skipped, ${unproven.length} UNPROVEN, ${blocked.length} BLOCKED`,
  )

  if (postedCandidates.length) {
    console.log(
      `${LOG} ${postedCandidates.length} of the candidates ALREADY HAVE ACCOUNTING DOCUMENTS derived from ` +
        'the amount about to change. Each understates and needs a manual credit/adjustment — clearing the ' +
        'IMS field does not reach a posted document. This is the state AT REPORT TIME; apply re-reads it ' +
        'live and refuses any row whose posting state has moved since you reviewed it.',
    )
    for (const { row } of postedCandidates) {
      const parts = [
        row.accountingInvoiceId ? `invoice ${row.accountingInvoiceId}` : null,
        // Listed SEPARATELY from the column, because "posted but the id was never written back"
        // (o3d-9kek) is a different thing for the reviewer to check than a linked invoice — and it
        // is the one apply used to refuse forever.
        row.postedInvoiceExternalIds.length
          ? `posted-but-unlinked invoice(s) ${row.postedInvoiceExternalIds.join(', ')}`
          : null,
        row.revenueDeferredBatchRef ? `revenue deferral batch ${row.revenueDeferredBatchRef}` : null,
      ].filter(Boolean)
      console.log(`${LOG}   posted: ${row.orderNumber || row.orderId} -> ${parts.join('; ')}`)
    }
  }

  if (nearCutoff.length) {
    console.log('')
    console.log(
      `${LOG} ${nearCutoff.length} candidate(s) were classified by the CUTOFF CHOICE rather than by a ` +
        'comfortable margin — they were imported shortly before it. The fixed importer ran for a while ' +
        'WITHOUT stamping discountModel, so a cutoff even slightly late sweeps in correct rows. Check ' +
        'each of these against the deployment record before approving it:',
    )
    for (const { row } of nearCutoff) {
      console.log(`${LOG}   ${row.orderNumber || row.orderId}: imported ${row.importedAt?.toISOString()}`)
    }
  }

  if (unproven.length) {
    // These are NOT skipped-and-forgotten: the meaning of their stored amount could not be
    // established, so reinterpreting it could destroy a genuine discount. They are listed so they can
    // be settled by hand (or by stamping discountModel) and the run repeated.
    console.log('')
    console.log(
      `${LOG} ${unproven.length} order(s) are UNPROVEN — nothing establishes what their stored ` +
        'discountAmount means, so it is LEFT EXACTLY AS IT IS rather than re-derived:',
    )
    for (const { row, decision } of unproven) {
      console.log(`${LOG}   ${row.orderNumber || row.orderId}: ${decision.reason} — ${decision.detail}`)
    }
  }

  if (blocked.length) {
    console.log('')
    console.log(
      `${LOG} ${blocked.length} order(s) are BLOCKED by live accounting work — a queued SALES_INVOICE, ` +
        'or a daily revenue-deferral journal that has not posted yet. Both carry a payload snapshot the ' +
        'processors post from, and a worker may already hold it, so this run will not propose them. Let ' +
        'the queue and the daily batch drain (or resolve the failed jobs) and re-run:',
    )
    for (const { row, decision } of blocked) {
      console.log(`${LOG}   ${row.orderNumber || row.orderId}: ${decision.detail}`)
    }
  }

  if (csvPath) {
    const header =
      'salesOrderId,orderNumber,externalOrderNumber,currency,storedOrderDiscount,lineDiscountTotal,' +
      'importedAt,nearCutoff,discountModel,accountingInvoiceId,postedInvoiceExternalIds,liveInvoiceJobs,revenueDeferredBatchRef,' +
      'liveBatchDeferralJobs,action,reason,keptOrderLevel,clearedBy,detail'
    const body = rows.map(({ row, decision }) =>
      [
        row.orderId,
        row.orderNumber,
        row.externalOrderNumber,
        row.currency,
        row.storedOrderDiscount,
        row.lineDiscountTotal,
        row.importedAt?.toISOString() ?? '',
        isNearWcCouponCutoff(row.importedAt, importedBefore) ? 'NEAR_CUTOFF' : '',
        row.discountModel ?? '',
        row.accountingInvoiceId ?? '',
        // Space-separated inside ONE field: the separator must not be the CSV separator, or a row
        // with two posted invoices silently shifts every column after it.
        row.postedInvoiceExternalIds.join(' '),
        row.liveInvoiceJobs,
        row.revenueDeferredBatchRef ?? '',
        row.liveBatchDeferralJobs,
        decision.action,
        decision.action === 'CORRECT' ? (decision.partial ? 'PARTIAL' : 'FULL') : decision.reason,
        decision.action === 'CORRECT' ? decision.keptOrderLevel : '',
        decision.action === 'CORRECT' ? decision.clearedBy : '',
        decision.action === 'CORRECT' ? '' : JSON.stringify(decision.detail),
      ].join(','),
    )
    writeFileSync(csvPath, [header, ...body].join('\n') + '\n')
    console.log(`${LOG} wrote ${csvPath} (EVERY order, including the ones left alone)`)
  }

  if (allowlistOut) {
    const proposal: WcCouponAllowlist = {
      version: 2,
      generatedAt: new Date().toISOString(),
      cutoff: importedBefore ? importedBefore.toISOString() : '',
      // UNSIGNED. Apply refuses this file until a human sets these three.
      reviewed: false,
      reviewedBy: null,
      reviewedAt: null,
      stampOnly: [],
      clear: corrections.map(({ row, decision }) => buildWcCouponAllowlistEntry(row, decision, importedBefore)),
    }
    writeFileSync(allowlistOut, JSON.stringify(proposal, null, 2) + '\n')
    console.log('')
    console.log(
      `${LOG} wrote ${allowlistOut} — a PROPOSAL of ${proposal.clear.length} order(s), unsigned.\n` +
        `${LOG} Review every entry (see the header of this script for what to check), move any row ` +
        'whose amount is ALREADY correct into "stampOnly", delete anything you are unsure of, then set\n' +
        `${LOG}   "reviewed": true, "reviewedBy": "<your name>", "reviewedAt": "<ISO>"\n` +
        `${LOG} and run:  --allowlist ${allowlistOut} --apply`,
    )
  }

  console.log('')
  console.log(
    `${LOG} DRY RUN — nothing written. Apply consumes a REVIEWED allowlist only: ` +
      're-run with --allowlist-out <path> if you did not produce one.',
  )
}

async function main() {
  const importedBeforeRaw = flagValue('imported-before')
  const csvPath = flagValue('csv')
  const allowlistPath = flagValue('allowlist')
  const allowlistOut = flagValue('allowlist-out')

  if (APPLY) {
    if (!allowlistPath) {
      console.error(
        `${LOG} REFUSING to apply without --allowlist <path>.\n` +
          'This rewrites the discount on orders whose invoices are already in the ledger, and no field on\n' +
          'a row distinguishes a pre-fix import from one corrected by hand or written by the fixed importer\n' +
          'before it stamped its marker. So apply consumes a REVIEWED list of order ids, never a fresh scan.\n' +
          'Produce one with:  --imported-before <ISO> --allowlist-out <path>',
      )
      process.exitCode = 1
      return
    }
    if (importedBeforeRaw) {
      // The cutoff belongs to the PROPOSAL. Accepting it here would invite "apply with a different
      // cutoff", which is exactly the re-scan the review exists to prevent.
      console.error(
        `${LOG} --imported-before is not accepted with --apply. The cutoff decided which orders were ` +
          'PROPOSED; what apply may touch is decided by the reviewed allowlist alone.',
      )
      process.exitCode = 1
      return
    }
    await apply(allowlistPath)
    return
  }

  let importedBefore: Date | null = null
  if (importedBeforeRaw) {
    const parsed = parseWcCouponCutoff(importedBeforeRaw, new Date())
    if (!parsed.ok) {
      console.error(`${LOG} --imported-before rejected: ${parsed.reason} — ${parsed.detail}`)
      process.exitCode = 1
      return
    }
    importedBefore = parsed.cutoff
  }
  if (allowlistOut && !importedBefore) {
    console.error(
      `${LOG} --allowlist-out needs --imported-before <ISO instant>: without a cutoff every unstamped ` +
        'order is UNPROVEN, so the proposal would be empty.',
    )
    process.exitCode = 1
    return
  }

  await report(importedBefore, csvPath, allowlistOut)
}

// Only when RUN, not when imported: the unit tests import the decision helpers, and a module-load
// side effect would have them open a database connection.
if (process.argv[1]?.includes('backfill-wc-coupon-order-discount')) {
  main()
    .catch((error) => {
      console.error(error)
      process.exitCode = 1
    })
    .finally(async () => {
      const { db } = await import('../lib/db/index')
      await db.$disconnect()
    })
}
