#!/usr/bin/env tsx

import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { PURCHASE_ORDER_TRANSITIONS } from '../lib/domain/workflows/purchase-order-state.ts'
import { REFUND_TRANSITIONS } from '../lib/domain/workflows/refund-state.ts'
import { SALES_ORDER_TRANSITIONS } from '../lib/domain/workflows/sales-order-state.ts'
import { SHIPMENT_TRANSITIONS } from '../lib/domain/workflows/shipment-state.ts'
import { STOCK_TRANSFER_TRANSITIONS } from '../lib/domain/workflows/stock-transfer-state.ts'

const WORKFLOWS_DOC = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
  'docs',
  'workflows.md',
)
const START_MARKER = '<!-- BEGIN:generated-workflow-status-tables -->'
const END_MARKER = '<!-- END:generated-workflow-status-tables -->'

type TransitionMap = Record<string, readonly string[]>

const WORKFLOWS: Array<{
  name: string
  transitions: TransitionMap
  notes?: Partial<Record<string, string>>
}> = [
  {
    name: 'Sales Orders',
    transitions: SALES_ORDER_TRANSITIONS,
    notes: {
      CANCELLED: 'Terminal.',
    },
  },
  {
    name: 'Shipments',
    transitions: SHIPMENT_TRANSITIONS,
    notes: {
      SHIPPED: 'Terminal; stock dispatch and cost-layer snapshots happen on this transition.',
    },
  },
  {
    name: 'Purchase Orders',
    transitions: PURCHASE_ORDER_TRANSITIONS,
    notes: {
      CLOSED: 'Terminal.',
      RETURNED: 'Terminal.',
      CANCELLED: 'Terminal.',
    },
  },
  {
    name: 'Refunds',
    transitions: REFUND_TRANSITIONS,
    notes: {
      RECORDED: 'Derived when a `SalesOrderRefund` row exists.',
      CREDIT_NOTE_SYNCED: 'Derived from accounting credit-note sync state.',
      PAID: 'Terminal; derived from linked refund payments.',
    },
  },
  {
    name: 'Stock Transfers',
    transitions: STOCK_TRANSFER_TRANSITIONS,
    notes: {
      RECEIVED: 'Terminal.',
      CANCELLED: 'Terminal.',
    },
  },
]

function formatNextStatuses(nextStatuses: readonly string[]): string {
  if (nextStatuses.length === 0) {
    return 'None'
  }

  return nextStatuses.map((status) => `\`${status}\``).join(', ')
}

function formatWorkflowTable(workflow: (typeof WORKFLOWS)[number]): string {
  const rows = Object.entries(workflow.transitions)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([status, nextStatuses]) => {
      const note = workflow.notes?.[status] ?? '-'

      return `| \`${status}\` | ${formatNextStatuses(nextStatuses)} | ${note} |`
    })

  return [
    `### ${workflow.name}`,
    '',
    '| Status | Allowed next statuses | Notes |',
    '|---|---|---|',
    ...rows,
  ].join('\n')
}

function renderGeneratedSection(): string {
  return [
    START_MARKER,
    '',
    '<!-- Generated by `npm run docs:workflows`. Do not edit this section by hand. -->',
    '',
    ...WORKFLOWS.flatMap((workflow) => [formatWorkflowTable(workflow), '']),
    END_MARKER,
  ].join('\n')
}

function replaceGeneratedSection(document: string): string {
  const start = document.indexOf(START_MARKER)
  const end = document.indexOf(END_MARKER)

  if (start === -1 || end === -1 || end < start) {
    throw new Error(`Missing generated workflow markers in ${WORKFLOWS_DOC}`)
  }

  return [
    document.slice(0, start).trimEnd(),
    renderGeneratedSection(),
    document.slice(end + END_MARKER.length).trimStart(),
  ].join('\n\n')
}

async function main(): Promise<void> {
  const checkOnly = process.argv.includes('--check')
  const existing = await readFile(WORKFLOWS_DOC, 'utf8')
  const next = replaceGeneratedSection(existing)

  if (checkOnly) {
    if (existing !== next) {
      throw new Error(`${WORKFLOWS_DOC} is out of date. Run npm run docs:workflows.`)
    }

    return
  }

  await writeFile(WORKFLOWS_DOC, next)
}

main().catch((error: unknown) => {
  console.error(error)
  process.exitCode = 1
})
