// Declarations for scripts/check-producer-census.ts: EVERY call of a write primitive found by
// scripts/producer-census.ts is named here, keyed
//
//     <file>::<top-level declaration>::<primitive>[kind]#<ordinal within that declaration>
//
// with the (destination, operation) of lib/security/writer-ownership-map.ts it produces, how it produces
// it (mechanism), whether the work carries a business-event time (obligationTime, which must equal the
// ownership map's), and a note saying why.
//
// HOW TO ADD A PRODUCER. The census failed because a call site is not declared (or a declaration no
// longer matches code). Copy the key from the failure message and add one `d(...)` line below, in file
// order. Pick the (destination, operation) from the ownership map; if the operation is new, add it to
// lib/security/writer-ownership-map.ts first (with its owner per phase). If the site is not an outbound
// producer at all, give it an EXCLUDED_OPERATIONS pair with a reason. A moved site changes its key; a
// deleted site must have its line deleted (a stale declaration fails). This list is meant to SHRINK or
// grow only with the code: never add a line to silence the census without reading the call.

import type { Declaration, Mechanism } from './producer-census'

const d = (
  key: string,
  destination: string,
  operation: string,
  mechanism: Mechanism,
  obligationTime: 'required' | 'not-applicable',
  note: string,
): Declaration => ({ key, destination, operation, mechanism, obligationTime, note })

/**
 * `<destination>.<operation>` pairs a declaration may use although they are not operations of the ownership
 * map, each with the reason. Shrink-only: an unused entry fails the census.
 */
export const EXCLUDED_OPERATIONS: Readonly<Record<string, string>> = {
  'xero.type-generic-queue-seam': 'Generic Xero queue seam parameterised by AccountingSyncType: the operation is declared at each producing caller, and the producer hold applies per type at this seam.',
  'xero.bypass-script-row': 'A repro script that inserts a raw PENDING sync-log row past the seam; not an operation of its own, and the seam must refuse it unless the destination is live.',
  'xero.requeue-existing-row': 'Moves an EXISTING sync-log row back to PENDING; it produces no new obligation, and the writer-side cut-off (not the producer hold) governs what it may deliver.',
  'xero.implicit-contact-item-create': 'Contacts and items are created implicitly inside a queued post; they have no producer of their own, and the post that needs them is the declared operation.',
  'internal.outbox-primitive': 'The generic outbox INSERT: each registry operation is declared at its own enqueue caller, so the primitive itself belongs to no single operation.',
  'internal.posting-refusal-provisional': 'Internal bookkeeping of a refused posting (outbox accounting/posting-refusal.provisional): no destination write.',
  'internal.landed-cost-adjustment-journal': 'Internal outbox accounting/landed-cost.adjustment-journal: its effect is a sync-log row, which meets the Xero seam.',
  'internal.refund-reservation-release': 'Internal outbox sales/refund.reservation-release: releases a stock reservation, no destination write.',
  'internal.refund-unmatched-warning': 'Internal outbox sales/refund.unmatched-warning: raises an operator warning, no destination write.',
  'woocommerce.generic-write-reexport': 'Re-export of the raw WooCommerce write helpers: the operation is chosen at each caller of wcPost or wcPut, which are declared.',
}

/**
 * Ownership-map operations with NO producer in this repository, each with the reason. Equality-checked
 * both ways: an entry for an operation that now has a producer fails, and an operation with neither a
 * producer nor an entry here fails.
 */
export const NO_PRODUCER: Readonly<Record<string, string>> = {
  'woocommerce.order.withdrawal-outcome': 'Owner answer 6: the endpoint stays in the WooCommerce withdrawal plugin; IMS only RECEIVES the outcome through an authenticated API, so IMS has no outbound producer for it.',
  'woocommerce.order.trackship-reconcile': 'Owner answer 6: the endpoint stays in the TrackShip plugin; IMS only receives TrackShip events through an authenticated API, so IMS has no outbound producer for it.',
  'woocommerce.order.invoice-document': 'Owner answer 4: IMS will put the invoice into the customer\'s My Account at P2, but that producer is not written yet; there is no call site in this repo.',
}

export const DECLARATIONS: readonly Declaration[] = [
  d('app/(dashboard)/sync/exceptions/exceptions-client.tsx::ExceptionsClient::replayWmsOrderPush#1', 'mintsoft', 'order.create', 'operator-action', 'required',
    'Exceptions-inbox button that re-arms the create of a Mintsoft order.'),
  d('app/(dashboard)/sync/exceptions/exceptions-client.tsx::ExceptionsClient::repushMissingWmsOrder#1', 'mintsoft', 'order.create', 'operator-action', 'required',
    'Exceptions-inbox button that re-arms the create of a Mintsoft order.'),
  d('app/(dashboard)/sync/failed-sync-banner.tsx::FailedSyncBanner::retryFailedAccountingSync#1', 'xero', 'requeue-existing-row', 'operator-action', 'not-applicable',
    'Button that moves a FAILED sync-log row back to PENDING; the writer-side cut-off covers it, not the producer hold.'),
  d('app/(dashboard)/sync/mintsoft-client.tsx::MintsoftClient::runMintsoftProductVerifyNow#1', 'mintsoft', 'product.upsert', 'operator-action', 'not-applicable',
    'The button that calls the run-product-verify-now action.'),
  d('app/(dashboard)/sync/xero-client.tsx::XeroClient::retryFailedAccountingSync#1', 'xero', 'requeue-existing-row', 'operator-action', 'not-applicable',
    'Button that moves a FAILED sync-log row back to PENDING; the writer-side cut-off covers it, not the producer hold.'),
  d('app/(dashboard)/sync/xero-client.tsx::XeroClient::retryFailedAccountingSync#2', 'xero', 'requeue-existing-row', 'operator-action', 'not-applicable',
    'Button that moves a FAILED sync-log row back to PENDING; the writer-side cut-off covers it, not the producer hold.'),
  d('app/(dashboard)/sync/xero-client.tsx::HistoryEntryRow::retryFailedAccountingSync#1', 'xero', 'requeue-existing-row', 'operator-action', 'not-applicable',
    'Button that moves a FAILED sync-log row back to PENDING; the writer-side cut-off covers it, not the producer hold.'),
  d('app/actions/allocation.ts::autoAllocateOrder::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('app/actions/allocation.ts::autoAllocateOrder::enqueueStockSync#2', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('app/actions/allocation.ts::updateAllocation::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('app/actions/allocation.ts::addAllocation::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('app/actions/allocation.ts::deallocateOrder::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('app/actions/allocation.ts::reopenShipmentForRepackAction::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('app/actions/allocation.ts::updateShipmentStatus::queueDispatchEmailIfEligible#1', 'customer-email', 'despatch', 'queue-producer', 'not-applicable',
    'Queues the despatch e-mail when a shipment is dispatched (setting-gated).'),
  d('app/actions/allocation.ts::updateShipmentStatus::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('app/actions/allocation.ts::updateShipmentTracking::pushOrderDeliveryMetadata#1', 'woocommerce', 'order.tracking', 'facade', 'required',
    'Pushes tracking metadata for an order through the shopping facade.'),
  d('app/actions/email.ts::sendSalesOrderEmail::queueEmail#1', 'customer-email', 'order-confirmation', 'operator-action', 'not-applicable',
    'Operator button: e-mail the sales order confirmation.'),
  d('app/actions/email.ts::sendInvoiceEmail::queueEmail#1', 'customer-email', 'invoice', 'operator-action', 'not-applicable',
    'Operator button: e-mail the invoice.'),
  d('app/actions/import.ts::scheduleProductImportShoppingSync::pushProductMetadata#1', 'woocommerce', 'product.meta', 'facade', 'not-applicable',
    'Pushes product metadata to the storefront through the shopping facade.'),
  d('app/actions/import.ts::scheduleProductImportShoppingSync::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('app/actions/import.ts::scheduleProductImportShoppingSync::enqueueStockSync#2', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('app/actions/import.ts::importOpeningStockCsv::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('app/actions/manufacturing.ts::updateManufacturingOrderStatus::queueAccountingSyncTx#1', 'xero', 'inventory.journals', 'queue-producer', 'required',
    'Queues MANUFACTURING_JOURNAL when a manufacturing order completes.'),
  d('app/actions/manufacturing.ts::updateManufacturingOrderStatus::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('app/actions/manufacturing.ts::updateManufacturingCostLines::queueAccountingSyncTx#1', 'xero', 'inventory.journals', 'queue-producer', 'required',
    'Queues MANUFACTURING_RECLASS when cost lines change.'),
  d('app/actions/mintsoft-sync.ts::runMintsoftProductVerifyNow::runMintsoftProductVerify#1', 'mintsoft', 'product.upsert', 'operator-action', 'not-applicable',
    'Operator button: run the product verify now, which writes.'),
  d('app/actions/mintsoft-sync.ts::runMintsoftBundleVerifyNow::runMintsoftBundleVerify#1', 'mintsoft', 'product.bundle', 'operator-action', 'not-applicable',
    'Operator button: run the bundle verify now, which writes.'),
  d('app/actions/mintsoft-sync.ts::createMintsoftPurchaseOrderAsn::createAsn#1', 'mintsoft', 'asn.create', 'operator-action', 'not-applicable',
    'Operator action: creates an ASN in Mintsoft for a purchase order or a transfer.'),
  d('app/actions/mintsoft-sync.ts::createMintsoftTransferAsn::createAsn#1', 'mintsoft', 'asn.create', 'operator-action', 'not-applicable',
    'Operator action: creates an ASN in Mintsoft for a purchase order or a transfer.'),
  d('app/actions/mintsoft-sync.ts::restockMintsoftReturnInboxItem::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('app/actions/products.ts::createProduct::pushProductMetadata#1', 'woocommerce', 'product.meta', 'facade', 'not-applicable',
    'Pushes product metadata to the storefront through the shopping facade.'),
  d('app/actions/products.ts::createProduct::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('app/actions/products.ts::createProduct::scheduleWmsProductSync#1', 'mintsoft', 'product.upsert', 'queue-producer', 'not-applicable',
    'Schedules a Mintsoft product upsert after the product changes.'),
  d('app/actions/products.ts::updateProduct::pushProductMetadata#1', 'woocommerce', 'product.meta', 'facade', 'not-applicable',
    'Pushes product metadata to the storefront through the shopping facade.'),
  d('app/actions/products.ts::updateProduct::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('app/actions/products.ts::updateProduct::scheduleWmsProductSync#1', 'mintsoft', 'product.upsert', 'queue-producer', 'not-applicable',
    'Schedules a Mintsoft product upsert after the product changes.'),
  d('app/actions/products.ts::generateVariantsFromOptions::pushProductMetadata#1', 'woocommerce', 'product.meta', 'facade', 'not-applicable',
    'Pushes product metadata to the storefront through the shopping facade.'),
  d('app/actions/products.ts::generateVariantsFromOptions::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('app/actions/products.ts::deleteOrDeactivateVariant::pushProductMetadata#1', 'woocommerce', 'product.meta', 'facade', 'not-applicable',
    'Pushes product metadata to the storefront through the shopping facade.'),
  d('app/actions/products.ts::deleteOrDeactivateVariant::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('app/actions/products.ts::bulkDeactivateProducts::pushProductMetadata#1', 'woocommerce', 'product.meta', 'facade', 'not-applicable',
    'Pushes product metadata to the storefront through the shopping facade.'),
  d('app/actions/products.ts::bulkDeactivateProducts::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('app/actions/purchase-orders.ts::receivePurchaseOrder::queueAccountingSyncTx#1', 'xero', 'inventory.journals', 'queue-producer', 'required',
    'Queues STOCK_RECEIPT on receipt of a purchase order.'),
  d('app/actions/purchase-orders.ts::receivePurchaseOrder::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('app/actions/purchase-orders.ts::receivePurchaseOrder::enqueueStockSync#2', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('app/actions/purchase-orders.ts::returnPurchaseOrder::queueAccountingSyncTx#1', 'xero', 'inventory.journals', 'queue-producer', 'required',
    'Queues INVENTORY_ADJUSTMENT for a purchase return.'),
  d('app/actions/purchase-orders.ts::returnPurchaseOrder::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('app/actions/purchase-orders.ts::createInvoice::queueAccountingSyncTx#1', 'xero', 'purchase.bill', 'queue-producer', 'required',
    'Queues PURCHASE_INVOICE when a supplier invoice is created.'),
  d('app/actions/purchase-orders.ts::updateInvoice::queueAccountingSyncTx[reference]#1', 'xero', 'purchase.bill', 'reference', 'required',
    'Hands queueAccountingSyncTx to the purchase-invoice update flow as a dependency.'),
  d('app/actions/purchase-orders.ts::markBillPaid::queueAccountingSyncTx#1', 'xero', 'purchase.bill-payment', 'queue-producer', 'required',
    'Queues BILL_PAYMENT when a bill is marked paid.'),
  d('app/actions/purchase-orders.ts::markBillPaid::queueAccountingSync#1', 'xero', 'fx-journal', 'queue-producer', 'not-applicable',
    'Queues REALISED_FX_JOURNAL, which is suppressed for Xero and never produced there.'),
  d('app/actions/purchase-orders.ts::postSupplierCreditNote::queueAccountingSyncTx#1', 'xero', 'purchase.supplier-credit', 'queue-producer', 'required',
    'Queues PURCHASE_CREDIT_NOTE when a supplier credit note is posted.'),
  d('app/actions/sales.ts::queueSalesInvoiceForOrder::queueAccountingSync[reference]#1', 'xero', 'sales.invoice', 'queue-producer', 'required',
    'Queues SALES_INVOICE for an order; xeroom owns this operation, so IMS shadows it in every phase.'),
  d('app/actions/sales.ts::queueSalesInvoiceForOrder::queueAccountingSync#1', 'xero', 'sales.invoice', 'queue-producer', 'required',
    'Queues SALES_INVOICE for an order; xeroom owns this operation, so IMS shadows it in every phase.'),
  d('app/actions/sales.ts::applySalesOrderStatusTransition::queueDispatchEmailIfEligible#1', 'customer-email', 'despatch', 'queue-producer', 'not-applicable',
    'Queues the despatch e-mail on an order status transition (setting-gated).'),
  d('app/actions/sales.ts::queueRefundAccountingActions::queueAccountingSync#1', 'xero', 'sales.credit-note', 'queue-producer', 'required',
    'Queues CREDIT_NOTE for a refund.'),
  d('app/actions/sales.ts::queueRefundAccountingActions::queueAccountingSyncTxWithOutcome#1', 'xero', 'inventory.journals', 'queue-producer', 'required',
    'Queues the refund COGS_REVERSAL or UNEARNED_REV_REVERSAL inside the refund transaction.'),
  d('app/actions/sales.ts::queueRefundAccountingActions::queueAccountingSync#2', 'xero', 'inventory.journals', 'queue-producer', 'required',
    'Queues the refund COGS_REVERSAL or UNEARNED_REV_REVERSAL outside a transaction.'),
  d('app/actions/sales.ts::createRefund::addOrderComment[reference]#1', 'mintsoft', 'order.comment', 'direct-write', 'not-applicable',
    'Posts a refund note as a Mintsoft order comment (best effort, no enabled-connector check).'),
  d('app/actions/sales.ts::createRefund::addOrderComment#1', 'mintsoft', 'order.comment', 'direct-write', 'not-applicable',
    'Posts a refund note as a Mintsoft order comment (best effort, no enabled-connector check).'),
  d('app/actions/sales.ts::createRefund::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('app/actions/sales.ts::retryRefundAccounting::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('app/actions/sales.ts::deleteSalesOrder::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('app/actions/sales.ts::addPayment::queueAccountingSync#1', 'xero', 'fx-journal', 'queue-producer', 'not-applicable',
    'Queues REALISED_FX_JOURNAL on a payment, which is suppressed for Xero and never produced there.'),
  d('app/actions/settings.ts::generateMissingXeroTaxRates::putXeroTaxRate#1', 'xero', 'tax-rate', 'seam', 'not-applicable',
    'Operator action: PUTs missing tax rates directly to Xero. It asks the producer-side hold first (xeroTaxRateWriteShadow) and creates nothing on a SHADOW verdict; it still checks no sync setting.'),
  d('app/actions/shopping-sync.ts::createShoppingWebhooks::createWcWebhooks#1', 'woocommerce', 'webhooks', 'operator-action', 'not-applicable',
    'The shopping action that fronts webhook registration for the operator.'),
  d('app/actions/stock-counts.ts::postStockCount::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('app/actions/stock.ts::adjustStock::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('app/actions/stock.ts::bulkAdjustStock::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('app/actions/stock.ts::updateAdjustmentMovement::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('app/actions/transfers.ts::dispatchTransfer::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('app/actions/transfers.ts::receiveTransfer::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('app/actions/transfers.ts::receiveTransferPartial::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('app/actions/transfers.ts::cancelDispatchedTransfer::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('app/actions/wc-sync.ts::createWcWebhooks::wcPost#1', 'woocommerce', 'webhooks', 'operator-action', 'not-applicable',
    'Operator button: registers the WooCommerce webhooks.'),
  d('app/actions/wc-sync.ts::probeFxHelperPluginAction::probeFxHelperPlugin#1', 'woocommerce', 'fx-rates', 'operator-action', 'not-applicable',
    'Operator button: probe the FX helper plugin, which POSTs a test request.'),
  d('app/actions/wc-sync.ts::pushFxRatesToWcNow::pushCurrentFxRatesToWc#1', 'woocommerce', 'fx-rates', 'operator-action', 'not-applicable',
    'Operator button: push the current FX rates to WooCommerce now.'),
  d('app/actions/wc-sync.ts::triggerManualSync::startManualWcStockSync#1', 'woocommerce', 'stock', 'operator-action', 'not-applicable',
    'Starts a manual full stock push to WooCommerce.'),
  d('app/api/cron/mintsoft-bundle-verify/route.ts::GET::runMintsoftBundleVerify#1', 'mintsoft', 'product.bundle', 'drain', 'not-applicable',
    'The mintsoft-bundle-verify cron: verifies and writes bundles.'),
  d('app/api/cron/mintsoft-product-verify/route.ts::GET::runMintsoftProductVerify#1', 'mintsoft', 'product.upsert', 'drain', 'not-applicable',
    'The mintsoft-product-verify cron: verifies and writes products.'),
  d('app/api/cron/wc-reconcile/route.ts::GET::runWcReconcile#1', 'woocommerce', 'stock', 'drain', 'not-applicable',
    'The wc-reconcile cron: drains stock jobs and forces a daily full stock reconcile.'),
  d('app/api/cron/wms-order-push/route.ts::GET::runWmsOrderPushSweep#1', 'mintsoft', 'order.create', 'drain', 'required',
    'The wms-order-push cron runs the sweep: release, revalidation, create, verify, update, hold and cancel passes.'),
  d('app/api/e2e/mintsoft/route.ts::POST::runMintsoftProductVerify#1', 'mintsoft', 'product.upsert', 'operator-action', 'not-applicable',
    'End-to-end harness route that runs the product verify against the fake or stage connector.'),
  d('app/api/shopping/manual-sync/route.ts::POST::startManualWcStockSync#1', 'woocommerce', 'stock', 'operator-action', 'not-applicable',
    'Starts a manual full stock push to WooCommerce.'),
  d('lib/accounting/tax-rate-sync-trigger.ts::maybeQueueTaxRateSync::queueAccountingSync#1', 'xero', 'tax-rate', 'queue-producer', 'not-applicable',
    'Queues TAX_RATE_SYNC when a tax rate is created or changed.'),
  d('lib/accounting-email.ts::sendAccountingInvoiceEmailInternal::queueEmail#1', 'customer-email', 'invoice', 'queue-producer', 'not-applicable',
    'Queues the accounting invoice e-mail.'),
  d('lib/accounting-fx-revaluation.ts::runArApFxRevaluation::queueAccountingSync#1', 'xero', 'fx-journal', 'queue-producer', 'not-applicable',
    'Queues UNREALISED_FX_JOURNAL, which is suppressed for Xero and never produced there.'),
  d('lib/accounting-fx-revaluation.ts::runArApFxRevaluation::queueAccountingSync#2', 'xero', 'fx-journal', 'queue-producer', 'not-applicable',
    'Queues UNREALISED_FX_JOURNAL, which is suppressed for Xero and never produced there.'),
  d('lib/accounting.ts::queueAccountingSync::queueXeroSync#1', 'xero', 'type-generic-queue-seam', 'queue-seam', 'not-applicable',
    'The facade routes a queued write to the Xero queue; the operation is the caller\'s AccountingSyncType.'),
  d('lib/accounting.ts::queueAccountingSyncTx::createAccountingSyncLogRow#1', 'xero', 'type-generic-queue-seam', 'queue-seam', 'not-applicable',
    'Transactional enqueue: creates the sync-log row for whatever AccountingSyncType the caller passed.'),
  d('lib/accounting.ts::queueAccountingSyncTx::scheduleXeroAccountingOutbox#1', 'xero', 'type-generic-queue-seam', 'queue-seam', 'not-applicable',
    'Schedules the one outbox row that carries the sync-log row just created.'),
  d('lib/accounting.ts::queueAccountingSyncTxWithOutcome::queueAccountingSyncTx#1', 'xero', 'type-generic-queue-seam', 'queue-seam', 'not-applicable',
    'Wrapper that returns the enqueue outcome; the operation is the caller\'s AccountingSyncType.'),
  d('lib/connectors/accounting-registry.ts::ACCOUNTING_CONNECTOR_FACTORIES::generateMissingXeroTaxRates#1', 'xero', 'tax-rate', 'operator-action', 'not-applicable',
    'Registry entry that wires the operator\'s generate-missing-tax-rates action.'),
  d('lib/connectors/accounting-registry.ts::ACCOUNTING_CONNECTOR_FACTORIES::retryFailedXeroSync#1', 'xero', 'requeue-existing-row', 'operator-action', 'not-applicable',
    'Registry entry that wires the Xero retry action.'),
  d('lib/connectors/mintsoft/api/auth.ts::testMintsoftConnectionSettings::requestMintsoftAuthSession#1', 'mintsoft', 'auth.login', 'direct-write', 'not-applicable',
    'POST /api/Auth mints a key: not a business write, governed by the login grant.'),
  d('lib/connectors/mintsoft/api/auth.ts::getMintsoftAccessToken::requestMintsoftAuthSession#1', 'mintsoft', 'auth.login', 'direct-write', 'not-applicable',
    'POST /api/Auth mints a key: not a business write, governed by the login grant.'),
  d('lib/connectors/mintsoft/index.ts::MintsoftConnector.upsertProduct::upsertMintsoftProduct#1', 'mintsoft', 'product.upsert', 'facade', 'not-applicable',
    'The connector method delegates to the Mintsoft product writer.'),
  d('lib/connectors/mintsoft/index.ts::MintsoftConnector.updateProductContent::updateMintsoftProductContent#1', 'mintsoft', 'product.content', 'facade', 'not-applicable',
    'The connector method delegates to the Mintsoft product CONTENT writer (POST /api/Product with the changed content fields only, never meta).'),
  d('lib/connectors/mintsoft/index.ts::MintsoftConnector.createAsn::createMintsoftAsn#1', 'mintsoft', 'asn.create', 'facade', 'not-applicable',
    'The connector method delegates to the Mintsoft ASN writer.'),
  d('lib/connectors/mintsoft/index.ts::MintsoftConnector.createBundle::createMintsoftBundle#1', 'mintsoft', 'product.bundle', 'facade', 'not-applicable',
    'The connector method delegates to the Mintsoft bundle writer.'),
  d('lib/connectors/mintsoft/index.ts::MintsoftConnector.pushOrder::pushMintsoftOrder#1', 'mintsoft', 'order.create', 'facade', 'required',
    'The connector method delegates to the Mintsoft order creator.'),
  d('lib/connectors/mintsoft/index.ts::MintsoftConnector.updateOrder::updateMintsoftOrder#1', 'mintsoft', 'order.amend', 'facade', 'required',
    'The connector method delegates to the Mintsoft order amender.'),
  d('lib/connectors/mintsoft/index.ts::MintsoftConnector.cancelOrder::cancelMintsoftOrder#1', 'mintsoft', 'order.cancel', 'facade', 'not-applicable',
    'The connector method delegates to the Mintsoft cancel call, which the hold pass also uses.'),
  d('lib/connectors/mintsoft/index.ts::MintsoftConnector.addOrderComment::addMintsoftOrderComment#1', 'mintsoft', 'order.comment', 'facade', 'not-applicable',
    'The connector method delegates to the Mintsoft comment writer.'),
  d('lib/connectors/mintsoft/index.ts::<module>::createMintsoftAsn[reexport]#1', 'mintsoft', 'asn.create', 'reexport', 'not-applicable',
    'Re-exports the Mintsoft ASN writer.'),
  d('lib/connectors/mintsoft/index.ts::<module>::createMintsoftBundle[reexport]#1', 'mintsoft', 'product.bundle', 'reexport', 'not-applicable',
    'Re-exports the Mintsoft bundle writer.'),
  d('lib/connectors/mintsoft/index.ts::<module>::upsertMintsoftProduct[reexport]#1', 'mintsoft', 'product.upsert', 'reexport', 'not-applicable',
    'Re-exports the Mintsoft product writer.'),
  d('lib/connectors/mintsoft/index.ts::<module>::cancelMintsoftOrder[reexport]#1', 'mintsoft', 'order.cancel', 'reexport', 'not-applicable',
    'Re-exports the Mintsoft cancel call.'),
  d('lib/connectors/mintsoft/index.ts::<module>::pushMintsoftOrder[reexport]#1', 'mintsoft', 'order.create', 'reexport', 'required',
    'Re-exports the Mintsoft order creator.'),
  d('lib/connectors/mintsoft/index.ts::<module>::updateMintsoftOrder[reexport]#1', 'mintsoft', 'order.amend', 'reexport', 'required',
    'Re-exports the Mintsoft order amender.'),
  d('lib/connectors/mintsoft/sync/bundle-sync.ts::syncBundleInternal::createBundle[reference]#1', 'mintsoft', 'product.bundle', 'direct-write', 'not-applicable',
    'Creates one bundle in Mintsoft; reached by the verify cron and the operator button.'),
  d('lib/connectors/mintsoft/sync/bundle-sync.ts::syncBundleInternal::createBundle#1', 'mintsoft', 'product.bundle', 'direct-write', 'not-applicable',
    'Creates one bundle in Mintsoft; reached by the verify cron and the operator button.'),
  d('lib/connectors/mintsoft/sync/product-content-sync.ts::syncMintsoftProductContent::updateProductContent[reference]#1', 'mintsoft', 'product.content', 'direct-write', 'not-applicable',
    'The bare-reference check that the connector offers a content method; it calls nothing. The call itself is the next declaration, and it is made only after explainProducerDisposition says LIVE.'),
  d('lib/connectors/mintsoft/sync/product-content-sync.ts::syncMintsoftProductContent::updateProductContent#1', 'mintsoft', 'product.content', 'direct-write', 'not-applicable',
    'Sends the changed, verified content fields of one product to Mintsoft; reached by the product verify run (cron and operator button). SHADOW by producerDisposition (records a shadow row, no call) until IMS is the live writer; also held by the outbound-write hold.'),
  d('lib/connectors/mintsoft/sync/product-sync.ts::syncOneMintsoftProduct::upsertProduct#1', 'mintsoft', 'product.upsert', 'direct-write', 'not-applicable',
    'Upserts one product in Mintsoft; reached by the product-sync hook, the verify cron and the operator button.'),
  d('lib/connectors/mintsoft/sync/stock-sync.ts::enqueueAlignmentStockSync::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('lib/connectors/mintsoft/sync/stock-sync.ts::applyMintsoftAlignmentForProduct::queueAccountingSyncTx#1', 'xero', 'inventory.journals', 'queue-producer', 'required',
    'Queues STOCK_RECEIPT for a Mintsoft stock alignment.'),
  d('lib/connectors/woocommerce/fx-rates.ts::pushCurrentFxRatesToWc::pushFxRatesToWc#1', 'woocommerce', 'fx-rates', 'direct-write', 'not-applicable',
    'POSTs the rates to the WooCommerce FX helper plugin.'),
  d('lib/connectors/woocommerce/index.ts::<module>::wcPost[reexport]#1', 'woocommerce', 'generic-write-reexport', 'reexport', 'not-applicable',
    'Re-exports the raw WooCommerce write helpers from the connector index; the operation is chosen where they are called.'),
  d('lib/connectors/woocommerce/index.ts::<module>::wcPut[reexport]#1', 'woocommerce', 'generic-write-reexport', 'reexport', 'not-applicable',
    'Re-exports the raw WooCommerce write helpers from the connector index; the operation is chosen where they are called.'),
  d('lib/connectors/woocommerce/index.ts::<module>::pushImsStatusToWc[reexport]#1', 'woocommerce', 'order.status', 'reexport', 'required',
    'Re-exports the WooCommerce status writer from the connector index.'),
  d('lib/connectors/woocommerce/index.ts::<module>::pushImsProductToWc[reexport]#1', 'woocommerce', 'product.meta', 'reexport', 'not-applicable',
    'Re-exports the WooCommerce product writer from the connector index.'),
  d('lib/connectors/woocommerce/index.ts::<module>::pushStockToWc[reexport]#1', 'woocommerce', 'stock', 'drain', 'not-applicable',
    'Performs the stock push to WooCommerce (drain of the stock queue, a reconcile, or a manual push).'),
  d('lib/connectors/woocommerce/index.ts::<module>::probeFxHelperPlugin[reexport]#1', 'woocommerce', 'fx-rates', 'reexport', 'not-applicable',
    'Re-exports a WooCommerce FX writer from the connector index.'),
  d('lib/connectors/woocommerce/index.ts::<module>::pushCurrentFxRatesToWc[reexport]#1', 'woocommerce', 'fx-rates', 'reexport', 'not-applicable',
    'Re-exports a WooCommerce FX writer from the connector index.'),
  d('lib/connectors/woocommerce/index.ts::<module>::pushFxRatesToWc[reexport]#1', 'woocommerce', 'fx-rates', 'reexport', 'not-applicable',
    'Re-exports a WooCommerce FX writer from the connector index.'),
  d('lib/connectors/woocommerce/sync/invoice-note.ts::pushInvoiceNoteToWc::wcPost#1', 'woocommerce', 'order.invoice-note', 'direct-write', 'required',
    'Writes the invoice note and invoice meta onto the WooCommerce order.'),
  d('lib/connectors/woocommerce/sync/invoice-note.ts::pushInvoiceNoteToWc::wcPut#1', 'woocommerce', 'order.invoice-note', 'direct-write', 'required',
    'Writes the invoice note and invoice meta onto the WooCommerce order.'),
  d('lib/connectors/woocommerce/sync/order-completion-jobs.ts::scheduleWcOrderCompletion::enqueueIntegrationOutbox#1', 'woocommerce', 'order.status', 'queue-producer', 'required',
    'Enqueues woocommerce/order.complete inside the shipping transaction.'),
  d('lib/connectors/woocommerce/sync/order-completion-jobs.ts::processWcOrderCompletionJobs::pushOrderDeliveryMetadata#1', 'woocommerce', 'order.tracking', 'facade', 'required',
    'Pushes tracking metadata for an order through the shopping facade.'),
  d('lib/connectors/woocommerce/sync/order-completion-jobs.ts::processWcOrderCompletionJobs::pushSalesOrderStatus#1', 'woocommerce', 'order.status', 'drain', 'required',
    'The completion job drain pushes the order-completed status.'),
  d('lib/connectors/woocommerce/sync/order-import.ts::releaseHeldWcSalesInvoice::queueAccountingSync#1', 'xero', 'sales.invoice', 'queue-producer', 'required',
    'Queues SALES_INVOICE for an imported or released WooCommerce order; xeroom owns this operation, so IMS shadows it.'),
  d('lib/connectors/woocommerce/sync/order-import.ts::importWcOrder::queueAccountingSync#1', 'xero', 'sales.invoice', 'queue-producer', 'required',
    'Queues SALES_INVOICE for an imported or released WooCommerce order; xeroom owns this operation, so IMS shadows it.'),
  d('lib/connectors/woocommerce/sync/order-status-jobs.ts::scheduleWcOrderStatusPush::enqueueIntegrationOutbox#1', 'woocommerce', 'order.status', 'queue-producer', 'required',
    'Enqueues woocommerce/order.cancel or order.hold inside the status-change transaction.'),
  d('lib/connectors/woocommerce/sync/order-status-jobs.ts::attemptWcOrderStatusPush::pushSalesOrderStatus#1', 'woocommerce', 'order.status', 'drain', 'required',
    'The status job drain pushes the cancelled or on-hold status.'),
  d('lib/connectors/woocommerce/sync/order-status.ts::pushImsStatusToWc::wcPut#1', 'woocommerce', 'order.status', 'direct-write', 'required',
    'PUTs the order status onto the WooCommerce order.'),
  d('lib/connectors/woocommerce/sync/product-sync.ts::pushImsProductToWc::wcPut#1', 'woocommerce', 'product.meta', 'direct-write', 'not-applicable',
    'PUTs product metadata onto the WooCommerce product.'),
  d('lib/connectors/woocommerce/sync/reconcile.ts::runWcReconcile::pushStockToWc#1', 'woocommerce', 'stock', 'drain', 'not-applicable',
    'Performs the stock push to WooCommerce (drain of the stock queue, a reconcile, or a manual push).'),
  d('lib/connectors/woocommerce/sync/stock-sync-jobs.ts::migrateLegacyWcStockSyncJobs::enqueueIntegrationOutbox#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Enqueues woocommerce/stock.push (the legacy-job migration enqueues the same operation).'),
  d('lib/connectors/woocommerce/sync/stock-sync-jobs.ts::enqueueWcStockSyncJobs::enqueueIntegrationOutbox#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Enqueues woocommerce/stock.push (the legacy-job migration enqueues the same operation).'),
  d('lib/connectors/woocommerce/sync/stock-sync-jobs.ts::processQueuedWcStockSyncJobs::pushStockToWc#1', 'woocommerce', 'stock', 'drain', 'not-applicable',
    'Performs the stock push to WooCommerce (drain of the stock queue, a reconcile, or a manual push).'),
  d('lib/connectors/woocommerce/sync/stock-sync-jobs.ts::enqueueAndProcessImmediateWcStockSync::enqueueWcStockSyncJobs#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Immediate stock sync: enqueues the job rows, then processes them in-process.'),
  d('lib/connectors/woocommerce/sync/stock-sync.ts::safeWcPost::wcPost#1', 'woocommerce', 'stock', 'direct-write', 'not-applicable',
    'The stock push POSTs product and variation stock quantities to WooCommerce.'),
  d('lib/connectors/woocommerce/sync/stock-sync.ts::runManualWcStockPush::pushStockToWc#1', 'woocommerce', 'stock', 'drain', 'not-applicable',
    'Performs the stock push to WooCommerce (drain of the stock queue, a reconcile, or a manual push).'),
  d('lib/connectors/woocommerce/sync/tracking-sync.ts::pushImsTrackingToWc::wcPut#1', 'woocommerce', 'order.tracking', 'direct-write', 'required',
    'PUTs tracking metadata onto the WooCommerce order.'),
  d('lib/connectors/woocommerce/sync/wms-status.ts::pushWmsOrderStatusToWc::wcPut#1', 'woocommerce', 'order.wms-status-meta', 'direct-write', 'not-applicable',
    'PUTs the _oti_wms_* meta onto the WooCommerce order.'),
  d('lib/connectors/woocommerce/webhooks.ts::handleProductWebhook::enqueueAndProcessImmediateWcStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Corrects WooCommerce stock after an inbound product webhook disagrees with IMS.'),
  d('lib/connectors/xero/bills.ts::pushPurchaseBill::xeroPut#1', 'xero', 'purchase.bill', 'drain', 'required',
    'PUTs a purchase bill to Xero.'),
  d('lib/connectors/xero/bills.ts::updatePurchaseBill::xeroPost#1', 'xero', 'purchase.bill', 'drain', 'required',
    'POSTs an update to an existing purchase bill.'),
  d('lib/connectors/xero/contacts.ts::findOrCreateContact::xeroPost#1', 'xero', 'implicit-contact-item-create', 'drain', 'not-applicable',
    'Creates a Xero contact implicitly while a queued post needs one.'),
  d('lib/connectors/xero/credit-notes.ts::pushCreditNote::xeroPost#1', 'xero', 'sales.credit-note', 'drain', 'required',
    'POSTs a sales credit note to Xero.'),
  d('lib/connectors/xero/credit-notes.ts::pushPurchaseCreditNote::xeroPost#1', 'xero', 'purchase.supplier-credit', 'drain', 'required',
    'POSTs a supplier credit note to Xero.'),
  d('lib/connectors/xero/credit-notes.ts::allocatePurchaseCreditNote::xeroPut#1', 'xero', 'purchase.supplier-credit', 'drain', 'required',
    'PUTs an allocation of a supplier credit note.'),
  d('lib/connectors/xero/daily-sync.ts::createPendingSyncLog::createAccountingSyncLogRow#1', 'xero', 'daily-batch', 'queue-producer', 'required',
    'Daily batch rows (A1, A2, B and the reconciliations) are created here; the obligation time is the batch date.'),
  d('lib/connectors/xero/daily-sync.ts::createPendingSyncLog::scheduleXeroAccountingOutbox#1', 'xero', 'daily-batch', 'queue-producer', 'required',
    'Schedules the outbox row for a daily-batch sync-log row.'),
  d('lib/connectors/xero/invoices.ts::pushSalesInvoice::xeroPost#1', 'xero', 'sales.invoice', 'drain', 'required',
    'POSTs a sales invoice to Xero.'),
  d('lib/connectors/xero/invoices.ts::updateSalesInvoice::xeroPost#1', 'xero', 'sales.invoice-update', 'drain', 'required',
    'POSTs an update to an existing sales invoice.'),
  d('lib/connectors/xero/items.ts::findOrCreateItem::xeroPost#1', 'xero', 'implicit-contact-item-create', 'drain', 'not-applicable',
    'Creates a Xero item implicitly while a queued post needs one.'),
  d('lib/connectors/xero/journals.ts::postPreparedManualJournal::xeroPost#1', 'xero', 'type-generic-queue-seam', 'drain', 'not-applicable',
    'POSTs a manual journal; the daily batches, inventory journals and reversals all go through it.'),
  d('lib/connectors/xero/outbox.ts::scheduleXeroAccountingOutbox::enqueueIntegrationOutbox#1', 'xero', 'type-generic-queue-seam', 'queue-seam', 'not-applicable',
    'The 1:1 outbox row for a sync-log row; it also re-arms SUCCEEDED or PERMANENT_FAILED rows.'),
  d('lib/connectors/xero/queue.ts::queueXeroSync::createAccountingSyncLogRow#1', 'xero', 'type-generic-queue-seam', 'queue-seam', 'not-applicable',
    'Non-transactional Xero enqueue: creates the sync-log row for whatever AccountingSyncType the caller passed.'),
  d('lib/connectors/xero/queue.ts::queueXeroSync::scheduleXeroAccountingOutbox#1', 'xero', 'type-generic-queue-seam', 'queue-seam', 'not-applicable',
    'Schedules the outbox row that carries the sync-log row just created.'),
  d('lib/connectors/xero/sync-processor.ts::enqueueFollowUpSyncLog::scheduleXeroAccountingOutbox#1', 'xero', 'type-generic-queue-seam', 'queue-seam', 'not-applicable',
    'Schedules the outbox row for a follow-up sync-log row (a revival of a FAILED row, or a new row).'),
  d('lib/connectors/xero/sync-processor.ts::enqueueFollowUpSyncLog::createAccountingSyncLogRow#1', 'xero', 'type-generic-queue-seam', 'queue-seam', 'not-applicable',
    'Processor follow-ups (payment, attachment, credit-note allocation, invoice note) create their rows here; the type is the follow-up\'s.'),
  d('lib/connectors/xero/sync-processor.ts::enqueueFollowUpSyncLog::scheduleXeroAccountingOutbox#2', 'xero', 'type-generic-queue-seam', 'queue-seam', 'not-applicable',
    'Schedules the outbox row for a follow-up sync-log row (a revival of a FAILED row, or a new row).'),
  d('lib/connectors/xero/sync-processor.ts::ensureXeroOutboxForPendingSyncLogs::scheduleXeroAccountingOutbox#1', 'xero', 'requeue-existing-row', 'drain', 'not-applicable',
    'Backfills an outbox row for a claimable PENDING sync-log row; it re-arms existing work and produces none.'),
  d('lib/connectors/xero/sync-processor.ts::processClaimedEntry::xeroPost#1', 'xero', 'sales.payment', 'drain', 'required',
    'POSTs an invoice payment.'),
  d('lib/connectors/xero/sync-processor.ts::processClaimedEntry::xeroUploadAttachment#1', 'xero', 'purchase.bill-attachment', 'drain', 'required',
    'Uploads a bill attachment.'),
  d('lib/connectors/xero/sync-processor.ts::processClaimedEntry::pushInvoiceNoteToWc#1', 'woocommerce', 'order.invoice-note', 'drain', 'required',
    'The WC_INVOICE_NOTE follow-up: the Xero processor asks for the invoice note to be written to the order.'),
  d('lib/connectors/xero/sync-processor.ts::processClaimedEntry::xeroPost#2', 'xero', 'purchase.bill-payment', 'drain', 'required',
    'POSTs a bill payment.'),
  d('lib/connectors/xero/sync-processor.ts::processClaimedEntry::putXeroTaxRate#1', 'xero', 'tax-rate', 'drain', 'not-applicable',
    'Drains a queued TAX_RATE_SYNC row to Xero.'),
  d('lib/connectors/xero/tax-rates.ts::putXeroTaxRate::xeroPost#1', 'xero', 'tax-rate', 'drain', 'not-applicable',
    'POSTs a tax rate to Xero: the transport behind the queued TAX_RATE_SYNC drain and behind the direct action, which asks the producer-side hold before it calls this.'),
  d('lib/cost-layers.ts::queueShipmentCogsRevaluationSync::queueAccountingSyncTx[reference]#1', 'xero', 'inventory.journals', 'reference', 'required',
    'Passes queueAccountingSyncTx on to queue the COGS_REVERSAL for a cost-layer revaluation.'),
  d('lib/currencies/fx-refresh.ts::fetchAllFxRatesInternal::pushFxRatesToConnectors#1', 'woocommerce', 'fx-rates', 'facade', 'not-applicable',
    'The FX refresh pushes the new rates to every storefront connector.'),
  d('lib/domain/accounting/invoice-payment-enqueue.ts::registerInvoicePaymentWithLedger::queueAccountingSyncTxWithOutcome#1', 'xero', 'sales.payment', 'queue-producer', 'required',
    'Queues INVOICE_PAYMENT when a payment is registered against an invoice.'),
  d('lib/domain/accounting/posting-refusal-provisional.ts::enqueueProvisionalPostingRefusal::enqueueIntegrationOutbox#1', 'internal', 'posting-refusal-provisional', 'queue-producer', 'not-applicable',
    'Internal bookkeeping of a refused posting: no destination write.'),
  d('lib/domain/accounting/sync-log-row.ts::createAccountingSyncLogRow::accountingSyncLog.create#1', 'xero', 'type-generic-queue-seam', 'seam', 'not-applicable',
    'The one INSERT of a LIVE accounting sync-log row; every create site passes through it, and it asks the producer-side hold (xeroProducerSeamVerdict) first, so a SHADOW verdict never reaches this INSERT.'),
  d('lib/domain/accounting/sync-log-row.ts::recordShadowRow::accountingSyncLog.create#1', 'xero', 'type-generic-queue-seam', 'queue-seam', 'not-applicable',
    'The INSERT of a SHADOW row: CANCELLED, settlement basis HELD_SHADOW, never claimable, no outbox job. Reached only from createAccountingSyncLogRow after a SHADOW verdict.'),
  d('lib/domain/integrations/outbox.ts::enqueueIntegrationOutbox::integrationOutbox.create#1', 'internal', 'outbox-primitive', 'queue-seam', 'not-applicable',
    'The one INSERT of an integration-outbox row; each registry operation is declared at its own enqueue caller.'),
  d('lib/domain/inventory/stock-adjustment-apply.ts::applyStockAdjustment::queueAccountingSyncTxWithOutcome#1', 'xero', 'inventory.journals', 'queue-producer', 'required',
    'Queues INVENTORY_ADJUSTMENT for a stock adjustment.'),
  d('lib/domain/purchasing/cancellation-service.ts::defaultCancelPurchaseOrderServiceDeps::enqueueStockSync[reference]#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('lib/domain/purchasing/cancellation-service.ts::defaultCancelPurchaseOrderServiceDeps::queueAccountingSyncTx[reference]#1', 'xero', 'inventory.journals', 'reference', 'required',
    'Wires queueAccountingSyncTx into the purchase-order cancellation service as a dependency.'),
  d('lib/domain/purchasing/cancellation-service.ts::cancelPurchaseOrderService::queueAccountingSyncTx#1', 'xero', 'inventory.journals', 'queue-producer', 'required',
    'Queues INVENTORY_ADJUSTMENT when a purchase order is cancelled.'),
  d('lib/domain/purchasing/cancellation-service.ts::cancelPurchaseOrderService::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('lib/domain/purchasing/landed-cost-journal-outbox.ts::scheduleLandedCostJournalOutbox::enqueueIntegrationOutbox#1', 'internal', 'landed-cost-adjustment-journal', 'queue-producer', 'not-applicable',
    'Internal backstop whose effect is a sync-log row, which meets the Xero seam.'),
  d('lib/domain/purchasing/landed-cost-service.ts::queueLandedCostAdjustmentJournals::queueAccountingSyncTx#1', 'xero', 'inventory.journals', 'queue-producer', 'required',
    'Queues STOCK_IN_TRANSIT and COGS_JOURNAL for landed cost.'),
  d('lib/domain/purchasing/landed-cost-service.ts::queueLandedCostAdjustmentJournals::queueAccountingSyncTx#2', 'xero', 'inventory.journals', 'queue-producer', 'required',
    'Queues STOCK_IN_TRANSIT and COGS_JOURNAL for landed cost.'),
  d('lib/domain/purchasing/purchase-invoice-update-sync.ts::maybeQueuePurchaseInvoiceUpdate::queueAccountingSyncTx#1', 'xero', 'purchase.bill', 'queue-producer', 'required',
    'Queues PURCHASE_INVOICE_UPDATE when a posted bill changes.'),
  d('lib/domain/sales/allocation-service.ts::reverseOrphanedAllocationPosting::queueAccountingSyncTx#1', 'xero', 'inventory.journals', 'queue-producer', 'required',
    'Queues ALLOCATION_REVERSAL for an orphaned allocation posting.'),
  d('lib/domain/sales/refund-reservation-release-outbox.ts::scheduleRefundReservationReleaseOutbox::enqueueIntegrationOutbox#1', 'internal', 'refund-reservation-release', 'queue-producer', 'not-applicable',
    'Internal: releases a stock reservation after a refund.'),
  d('lib/domain/sales/refund-reservation-release-outbox.ts::scheduleRefundUnmatchedWarningOutbox::enqueueIntegrationOutbox#1', 'internal', 'refund-unmatched-warning', 'queue-producer', 'not-applicable',
    'Internal: raises an operator warning about an unmatched refund.'),
  d('lib/domain/sales/sales-invoice-update-sync.ts::queueSalesInvoiceUpdateForExistingAccountingInvoice::queueAccountingSync#1', 'xero', 'sales.invoice-update', 'queue-producer', 'required',
    'Queues SALES_INVOICE_UPDATE for a posted invoice; xeroom owns this operation, so IMS shadows it.'),
  d('lib/domain/sales/shipment-service.ts::reconcileOrderAfterShipment::scheduleShoppingOrderCompletion#1', 'woocommerce', 'order.status', 'queue-producer', 'required',
    'Schedules the storefront completion of a shipped order.'),
  d('lib/domain/wms/booked-in-service.ts::processBookedInEvent::queueAccountingSyncTxWithOutcome#1', 'xero', 'inventory.journals', 'queue-producer', 'required',
    'Queues STOCK_RECEIPT when Mintsoft books an ASN in.'),
  d('lib/domain/wms/booked-in-service.ts::processBookedInEvent::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('lib/domain/wms/dispatch-sweep.ts::createPrismaDispatchDeps::pushPartialShipmentToShopping#1', 'woocommerce', 'order.partial-shipment', 'facade', 'required',
    'Pushes a partial shipment through the shopping facade.'),
  d('lib/domain/wms/order-push-sweep.ts::runWmsOrderPushSweepCore::pushOrder[reference]#1', 'mintsoft', 'order.create', 'reference', 'required',
    'A presence test of the connector\'s optional pushOrder method.'),
  d('lib/domain/wms/order-push-sweep.ts::runWmsOrderPushSweepCore::addOrderComment[reference]#1', 'mintsoft', 'order.comment', 'drain', 'not-applicable',
    'The sweep posts a conflict comment when a hold or cancel cannot be propagated.'),
  d('lib/domain/wms/order-push-sweep.ts::runWmsOrderPushSweepCore::addOrderComment#1', 'mintsoft', 'order.comment', 'drain', 'not-applicable',
    'The sweep posts a conflict comment when a hold or cancel cannot be propagated.'),
  d('lib/domain/wms/order-push-sweep.ts::runWmsOrderPushSweepCore::pushOrder#1', 'mintsoft', 'order.create', 'drain', 'required',
    'The create pass: PUT /api/Order for a PENDING_CREATE link.'),
  d('lib/domain/wms/order-push-sweep.ts::runWmsOrderPushSweepCore::cancelOrder#1', 'mintsoft', 'order.cancel', 'drain', 'not-applicable',
    'Compensating cancel when a withdrawal races an order the create pass just pushed.'),
  d('lib/domain/wms/order-push-sweep.ts::runWmsOrderPushSweepCore::cancelOrder#2', 'mintsoft', 'order.cancel', 'drain', 'not-applicable',
    'Compensating cancel in the verify pass when a withdrawal raced the creation.'),
  d('lib/domain/wms/order-push-sweep.ts::runWmsOrderPushSweepCore::updateOrder#1', 'mintsoft', 'order.amend', 'drain', 'required',
    'The update pass: amends a synced Mintsoft order after the IMS order changes.'),
  d('lib/domain/wms/order-push-sweep.ts::runWmsOrderPushSweepCore::cancelOrder[reference]#1', 'mintsoft', 'order.cancel', 'reference', 'not-applicable',
    'A presence test of the connector\'s optional cancelOrder method before the hold or cancel pass.'),
  d('lib/domain/wms/order-push-sweep.ts::runWmsOrderPushSweepCore::cancelOrder#3', 'mintsoft', 'order.hold', 'drain', 'not-applicable',
    'The hold pass: GET /Order/{id}/Cancel to put a synced order on hold.'),
  d('lib/domain/wms/order-push-sweep.ts::runWmsOrderPushSweepCore::cancelOrder[reference]#2', 'mintsoft', 'order.cancel', 'reference', 'not-applicable',
    'A presence test of the connector\'s optional cancelOrder method before the hold or cancel pass.'),
  d('lib/domain/wms/order-push-sweep.ts::runWmsOrderPushSweepCore::cancelOrder#4', 'mintsoft', 'order.cancel', 'drain', 'not-applicable',
    'The cancel pass: GET /Order/{id}/Cancel for a cancelled order.'),
  d('lib/domain/wms/order-push-sweep.ts::runWmsOrderPushSweep::pushOrder[reference]#1', 'mintsoft', 'order.create', 'reference', 'required',
    'A presence test of the connector\'s optional pushOrder method.'),
  d('lib/domain/wms/order-status-sweep.ts::runWmsOrderStatusSweep::pushWmsOrderStatusToShopping#1', 'woocommerce', 'order.wms-status-meta', 'facade', 'not-applicable',
    'Pushes the warehouse status of an order through the shopping facade.'),
  d('lib/fulfillment/backorder-allocator.ts::allocateBackordersForProducts::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('lib/fulfillment/order-status-push.ts::scheduleManualStatusPush::scheduleShoppingOrderStatusPush#1', 'woocommerce', 'order.status', 'queue-producer', 'required',
    'Schedules a cancel or hold status push for an order.'),
  d('lib/fulfillment/reallocation-sweep.ts::sweepUnallocatedProcessingOrders::enqueueStockSync[reference]#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('lib/fulfillment/reallocation-sweep.ts::sweepUnallocatedProcessingOrders::enqueueStockSync#1', 'woocommerce', 'stock', 'queue-producer', 'not-applicable',
    'Asks the shopping facade to push this product\'s stock to the storefront.'),
  d('lib/fulfillment/shipment-completion-push.ts::scheduleManualShipCompletion::scheduleShoppingOrderCompletion#1', 'woocommerce', 'order.status', 'queue-producer', 'required',
    'Schedules the storefront completion of a shipped order.'),
  d('lib/fulfillment/shipment-completion-push.ts::pushShipmentCompletionToShopping::pushOrderDeliveryMetadata#1', 'woocommerce', 'order.tracking', 'facade', 'required',
    'Pushes tracking metadata for an order through the shopping facade.'),
  d('lib/shopping.ts::syncShoppingConnectorStock::pushStockToWc#1', 'woocommerce', 'stock', 'facade', 'not-applicable',
    'The facade runs a direct stock push for one connector.'),
  d('lib/shopping.ts::enqueueStockSync::enqueueAndProcessImmediateWcStockSync#1', 'woocommerce', 'stock', 'facade', 'not-applicable',
    'The facade passes the stock push to the WooCommerce job queue.'),
  d('lib/shopping.ts::pushProductMetadata::pushImsProductToWc#1', 'woocommerce', 'product.meta', 'facade', 'not-applicable',
    'The facade passes product metadata to the WooCommerce product writer.'),
  d('lib/shopping.ts::pushOrderDeliveryMetadata::pushImsTrackingToWc#1', 'woocommerce', 'order.tracking', 'facade', 'required',
    'The facade passes tracking to the WooCommerce tracking writer.'),
  d('lib/shopping.ts::pushPartialShipmentToShopping::pushPartialShipmentToWc#1', 'woocommerce', 'order.partial-shipment', 'facade', 'required',
    'The facade passes a partial shipment to the WooCommerce companion-plugin writer.'),
  d('lib/shopping.ts::pushWmsOrderStatusToShopping::pushWmsOrderStatusToWc#1', 'woocommerce', 'order.wms-status-meta', 'facade', 'not-applicable',
    'The facade passes the warehouse status to the WooCommerce meta writer.'),
  d('lib/shopping.ts::pushSalesOrderStatus::pushImsStatusToWc#1', 'woocommerce', 'order.status', 'facade', 'required',
    'The facade passes an order status change to the WooCommerce status writer.'),
  d('lib/shopping.ts::scheduleShoppingOrderCompletion::scheduleWcOrderCompletion[reference]#1', 'woocommerce', 'order.status', 'facade', 'required',
    'The facade passes order completion to the WooCommerce job queue.'),
  d('lib/shopping.ts::scheduleShoppingOrderCompletion::scheduleWcOrderCompletion#1', 'woocommerce', 'order.status', 'facade', 'required',
    'The facade passes order completion to the WooCommerce job queue.'),
  d('lib/shopping.ts::scheduleShoppingOrderStatusPush::scheduleWcOrderCancel[reference]#1', 'woocommerce', 'order.status', 'facade', 'required',
    'The facade passes a cancel status to the WooCommerce job queue.'),
  d('lib/shopping.ts::scheduleShoppingOrderStatusPush::scheduleWcOrderCancel#1', 'woocommerce', 'order.status', 'facade', 'required',
    'The facade passes a cancel status to the WooCommerce job queue.'),
  d('lib/shopping.ts::scheduleShoppingOrderStatusPush::scheduleWcOrderHold#1', 'woocommerce', 'order.status', 'facade', 'required',
    'The facade passes an on-hold status to the WooCommerce job queue.'),
  d('lib/shopping.ts::pushFxRatesToConnectors::pushCurrentFxRatesToWc#1', 'woocommerce', 'fx-rates', 'facade', 'not-applicable',
    'The facade passes the current rates to the WooCommerce FX writer.'),
  d('scripts/provision-xero-demo.ts::ensureCurrencies::xeroPut#1', 'xero', 'demo-provisioning', 'script', 'not-applicable',
    'Manual script that provisions a demo Xero tenant; the tenant grant is its only barrier.'),
  d('scripts/provision-xero-demo.ts::ensureAccounts::xeroPut#1', 'xero', 'demo-provisioning', 'script', 'not-applicable',
    'Manual script that provisions a demo Xero tenant; the tenant grant is its only barrier.'),
  d('scripts/provision-xero-demo.ts::ensureBankAccounts::xeroPut#1', 'xero', 'demo-provisioning', 'script', 'not-applicable',
    'Manual script that provisions a demo Xero tenant; the tenant grant is its only barrier.'),
  d('scripts/provision-xero-demo.ts::ensureTaxRates::xeroPost#1', 'xero', 'demo-provisioning', 'script', 'not-applicable',
    'Manual script that provisions a demo Xero tenant; the tenant grant is its only barrier.'),
  d('scripts/repro-scjz68.ts::seedScenario::accountingSyncLog.create#1', 'xero', 'bypass-script-row', 'seam', 'not-applicable',
    'Repro script inserting a raw PENDING row past createAccountingSyncLogRow; it asks the producer seam first and refuses to seed unless the hold is not enforced for Xero or the decision is LIVE.'),
  d('components/sales/wms-order-push-chip.tsx::WmsOrderPushChip::replayWmsOrderPush#1', 'mintsoft', 'order.create', 'operator-action', 'required',
    'Order-page button that re-arms the create of a Mintsoft order.'),
]
