/**
 * AN INSTALL.SH RE-RUN MUST NOT SILENTLY DISCARD WHAT THE OPERATOR ALREADY HAS IN .env (D4 re-run).
 *
 * The file was rewritten from a template: WooCommerce credentials were blanked, the webhook secret
 * was replaced with a fresh random one (breaking the signature check of every webhook WooCommerce
 * was already sending), hand-added variables (TRUSTED_PROXY_IPS ...) vanished, and nothing said so
 * and no copy was kept. Arms lift the SHIPPED functions and prompt lines into a `bash` and run them
 * over real files; each prints the precondition it reached.
 */
import assert from 'node:assert/strict'
import { spawnSync } from 'node:child_process'
import { chmodSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import test from 'node:test'

import { shippedFunction } from './real-postgres-cluster.ts'
import { withTempDir } from './temp-dir.ts'

const REPO = process.cwd()
const INSTALL = readFileSync(join(REPO, 'scripts/install.sh'), 'utf8')
const read = (rel: string): string => readFileSync(join(REPO, rel), 'utf8')

function bash(program: string): { status: number; out: string } {
  const r = spawnSync('bash', ['-c', program], {
    encoding: 'utf8',
    env: { PATH: process.env.PATH ?? '/usr/bin:/bin', LC_ALL: 'C' } as unknown as NodeJS.ProcessEnv,
  })
  return { status: r.status ?? -1, out: `${r.stdout ?? ''}${r.stderr ?? ''}` }
}

/** The previous run's file: one installer-owned key, secrets, and the hand-added keys the finding lost. */
const OLD_ENV = [
  '# generated by install.sh',
  'APP_PORT=3000',
  'AUTH_SECRET=old-auth',
  'WC_STORE_URL=https://shop.example.test',
  'WC_CONSUMER_KEY=ck_old',
  'WC_CONSUMER_SECRET=cs_old',
  'WC_WEBHOOK_SECRET=whsec_old',
  'TRUSTED_PROXY_IPS=10.0.0.1,10.0.0.2',
  'REQUIRE_TRUSTED_PROXY_CONFIG=true',
  'XERO_ALLOWED_TENANT_IDS=tenant-a,tenant-b',
  'MY_FEATURE_FLAG=on',
  'FILE_SCAN_MODE=clamav',
  '',
].join('\n')

const TOO_SHORT_MESSAGE = /^ENV_ADMIN_PASSWORD_TOO_SHORT_MESSAGE="(.*)"$/m.exec(INSTALL)?.[1] ?? ''

const LIB = [
  'set -uo pipefail',
  'exec 2>&1',
  'info() { echo "INFO: $*"; }; warn() { echo "WARN: $*"; }; error() { echo "ERROR: $*"; }',
  'die() { echo "DIE: $*"; exit 9; }',
  'APP_DIR=/opt/app; APP_USER=app; DB_ADMIN_CREDENTIAL_FILE=/etc/ims-db-admin/deploy-admin.env',
  'declare -A EXISTING_ENV=()',
  'declare -a EXISTING_ENV_RAW=() EXISTING_ENV_UNCLASSIFIED=() ENV_REFUSED_KEYS=()',
  'declare -A EXISTING_ENV_LINENO=()',
  'ENV_REFUSAL_REASON=""',
  /^ENV_ADMIN_PASSWORD_MIN_LENGTH=\d+$/m.exec(INSTALL)?.[0] ?? 'ENV_ADMIN_PASSWORD_MIN_LENGTH=UNSET',
  'ENV_ADMIN_PASSWORD_DECODED=""; ENV_UNOWNED_EXISTING_KEYS=()',
  `ENV_ADMIN_PASSWORD_TOO_SHORT_MESSAGE=${JSON.stringify(TOO_SHORT_MESSAGE)}`,
  /^ENV_TEMPLATE_KEYS=.*$/m.exec(INSTALL)?.[0] ?? 'ENV_TEMPLATE_KEYS=()',
  'ENV_FILE_STATE=absent',
  'ENV_BACKUP_FILE=""; ENV_KEPT_KEYS=(); ENV_PRESERVED_BLOCK=""',
  shippedFunction(INSTALL, 'existing_env'),
  shippedFunction(INSTALL, 'env_value_closes_quote'),
  shippedFunction(INSTALL, 'load_existing_env'),
  shippedFunction(INSTALL, 'env_percent_decode'),
  shippedFunction(INSTALL, 'env_percent_encode'),
  /^declare -A ENV_PRESERVE_SHAPES=\([\s\S]*?^\)$/m.exec(INSTALL)?.[0] ?? 'declare -A ENV_PRESERVE_SHAPES=()',
  'ENV_PRESERVE_MAX_LENGTH=4096; ENV_BACKUP_OWNER="$(id -un):$(id -gn)"',
  shippedFunction(INSTALL, 'env_value_has_shape'),
  shippedFunction(INSTALL, 'env_value_has_residual_escape'),
  /^ENV_PRESERVE_SECURITY_KEYS=\([\s\S]*?^\)$/m.exec(INSTALL)?.[0] ?? 'ENV_PRESERVE_SECURITY_KEYS=()',
  /^ENV_SECURITY_KEY_UNCARRIABLE_MESSAGE=".*"$/m.exec(INSTALL)?.[0] ?? 'ENV_SECURITY_KEY_UNCARRIABLE_MESSAGE=x',
  "ENV_PRESERVE_VALUE=''; declare -A ENV_PRESERVED_EFFECTIVE=()",
  shippedFunction(INSTALL, 'env_effective_value'),
  shippedFunction(INSTALL, 'env_canonical_value'),
  shippedFunction(INSTALL, 'env_preserve_decision'),
  shippedFunction(INSTALL, 'env_key_is_security_control'),
  shippedFunction(INSTALL, 'env_value_leaks_secret'),
  shippedFunction(INSTALL, 'env_admin_password_decoded'),
  shippedFunction(INSTALL, 'env_unowned_existing_keys'),
  shippedFunction(INSTALL, 'env_key_carry_check'),
  shippedFunction(INSTALL, 'env_key_is_admin_credential'),
  shippedFunction(INSTALL, 'render_preserved_env_keys'),
  shippedFunction(INSTALL, 'write_env_backup'),
  shippedFunction(INSTALL, 'print_env_rewrite_summary'),
].join('\n')

/** The template output of a re-run, reduced to the keys the arms care about. */
const RENDERED = ['APP_PORT=3000', 'AUTH_SECRET=old-auth', 'WC_STORE_URL=https://shop.example.test', 'WC_CONSUMER_KEY=ck_old', 'WC_CONSUMER_SECRET=cs_old', 'WC_WEBHOOK_SECRET=whsec_old', 'FILE_SCAN_MODE=clamav', 'NEW_KEY=1'].join('\n')

test('re-run: only keys on the carry list are carried, verbatim; every other unowned key is dropped and reported', async () => {
  await withTempDir('ims-env-keep-', async (dir) => {
    const old = join(dir, '.env')
    writeFileSync(old, OLD_ENV)
    const r = bash([LIB, `load_existing_env '${old}'`, `rendered='${RENDERED}'`,
      'render_preserved_env_keys "${rendered}"; echo "RC=$?"', 'printf "BLOCK<<%s>>" "${ENV_PRESERVED_BLOCK}"', 'echo "KEPT=${ENV_KEPT_KEYS[*]}"',
      'printf "DROPPED:%s\\n" "${ENV_REFUSED_KEYS[@]}"'].join('\n'))
    console.log(`  precondition: previous file read; kept -> ${JSON.stringify(r.out.split('\n').filter((l) => /^(KEPT|RC)=/.test(l)))}`)
    console.log(`  dropped -> ${JSON.stringify(r.out.split('\n').filter((l) => /^DROPPED:/.test(l)))}`)
    assert.match(r.out, /RC=0/)
    assert.match(r.out, /KEPT=REQUIRE_TRUSTED_PROXY_CONFIG TRUSTED_PROXY_IPS XERO_ALLOWED_TENANT_IDS\n/)
    assert.match(r.out, /^TRUSTED_PROXY_IPS=10\.0\.0\.1,10\.0\.0\.2$/m)
    assert.match(r.out, /^XERO_ALLOWED_TENANT_IDS=tenant-a,tenant-b$/m)
    const block = /BLOCK<<([\s\S]*?)>>/.exec(r.out)?.[1] ?? ''
    assert.doesNotMatch(block, /^APP_PORT=/m, 'a key the template sets is not written twice')
    // THE ALLOWLIST IS THE ONLY PATH: an unknown key with an innocuous value is dropped, and says so.
    assert.doesNotMatch(block, /MY_FEATURE_FLAG/, 'an unknown key with a harmless value is NOT carried')
    assert.match(r.out, /DROPPED:MY_FEATURE_FLAG \(line \d+\): not on the list of settings a re-run carries over/)
  })
})

test('re-run: a deploy admin credential left in the application .env is REFUSED, never carried forward', async () => {
  await withTempDir('ims-env-admin-', async (dir) => {
    const old = join(dir, '.env')
    writeFileSync(old, `${OLD_ENV}DEPLOY_ADMIN_DATABASE_URL=postgres://admin:SECRETPW@h/db\n`)
    const r = bash([LIB, `load_existing_env '${old}'`, `rendered='${RENDERED}'`,
      'render_preserved_env_keys "${rendered}"; echo "RC=$?"', 'printf "BLOCK=[%s]" "${ENV_PRESERVED_BLOCK}"'].join('\n'))
    console.log(`  admin key present -> ${JSON.stringify(r.out.split('\n').filter((l) => /RC=|ERROR/.test(l)).map((l) => l.slice(0, 90)))}`)
    assert.match(r.out, /RC=1/)
    assert.match(r.out, /ERROR: .*DEPLOY_ADMIN_DATABASE_URL.*must never hold the deploy admin credential/)
    assert.doesNotMatch(r.out, /SECRETPW/, 'and the value is never printed')
    assert.match(r.out, /BLOCK=\[\]/, 'no block was produced')
  })
})

const adminDir = (dir: string): string => {
  const d = join(dir, 'admin-private')
  mkdirSync(d, { mode: 0o700 })
  chmodSync(d, 0o700)
  return d
}

test('re-run: the backup of the old file is root-only, outside the application tree, written from what was read, before anything is replaced', async () => {
  await withTempDir('ims-env-bak-', async (dir) => {
    const old = join(dir, '.env.src')
    writeFileSync(old, OLD_ENV)
    const credDir = adminDir(dir)
    const target = join(dir, 'captured')
    const r = bash([LIB, 'date() { echo 20261008T120000Z; }',
      // publish_durable_file replaced by a recorder: arguments + stdin.
      `publish_durable_file() { echo "PUBLISH $1 $2 $3" > '${target}.args'; cat > '${target}.body'; }`,
      `load_existing_env '${old}'`, `APP_DIR='/opt/app-not-used'`, `DB_ADMIN_CREDENTIAL_DIR='${credDir}'`, 'write_env_backup; echo "RC=$?"', 'echo "FILE=${ENV_BACKUP_FILE}"'].join('\n'))
    const args = readFileSync(`${target}.args`, 'utf8').trim()
    console.log(`  backup: ${args.replace(dir, '<tmp>')}`)
    assert.match(r.out, /RC=0/)
    assert.match(args, new RegExp(`^PUBLISH ${credDir.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}/previous-app-env-20261008T120000Z-\\d+-0 \\S+:\\S+ 600$`))
    assert.doesNotMatch(args, /opt\/app-not-used/, 'and it is not under the application directory')
    assert.equal(readFileSync(`${target}.body`, 'utf8'), OLD_ENV, 'the backup is the old file byte for byte (every dropped key is in it)')
    // The directory is judged: wrong mode refused, nothing published.
    chmodSync(credDir, 0o755)
    const loose = bash([LIB, 'publish_durable_file() { echo CALLED; }', `load_existing_env '${old}'`, `DB_ADMIN_CREDENTIAL_DIR='${credDir}'`, 'write_env_backup; echo "RC=$?"'].join('\n'))
    console.log(`  directory mode 0755: ${JSON.stringify(loose.out.trim().split('\n').map((l) => l.slice(0, 100)))}`)
    assert.match(loose.out, /RC=1/)
    assert.match(loose.out, /must be owned by root with mode 0700/)
    assert.doesNotMatch(loose.out, /CALLED/)
    chmodSync(credDir, 0o700)
    // First install: nothing to back up, nothing published.
    const first = bash([LIB, 'publish_durable_file() { echo CALLED; }', 'write_env_backup; echo "RC=$? FILE=[${ENV_BACKUP_FILE}]"'].join('\n'))
    assert.match(first.out, /RC=0 FILE=\[\]/)
    assert.doesNotMatch(first.out, /CALLED/)
  })
})

test('re-run: two backups in the same second get different names, and a planted name is skipped, never replaced', async () => {
  await withTempDir('ims-env-bak2-', async (dir) => {
    const old = join(dir, '.env.src')
    writeFileSync(old, OLD_ENV)
    const credDir = adminDir(dir)
    const program = (extra: string) => [LIB, 'date() { echo 20261008T120000Z; }',
      // The recorder publishes for real into the reserved name, as publish_durable_file renames over it.
      'publish_durable_file() { cat > "$1"; }',
      `load_existing_env '${old}'`, `DB_ADMIN_CREDENTIAL_DIR='${credDir}'`, extra,
      'write_env_backup; echo "FIRST=${ENV_BACKUP_FILE##*/}"', 'write_env_backup; echo "SECOND=${ENV_BACKUP_FILE##*/}"'].join('\n')
    const r = bash(program(''))
    const first = /FIRST=(\S+)/.exec(r.out)?.[1]
    const second = /SECOND=(\S+)/.exec(r.out)?.[1]
    console.log(`  same-second names: ${first} / ${second}`)
    assert.ok(first && second && first !== second, 'precondition: two names were handed out')
    assert.equal(readFileSync(join(credDir, first), 'utf8'), OLD_ENV, 'and the first backup is still there, intact')
    assert.equal(readFileSync(join(credDir, second), 'utf8'), OLD_ENV)
    // A name already taken (here a symlink planted at the first candidate) is skipped, not followed.
    const victim = join(dir, 'victim')
    writeFileSync(victim, 'DO NOT TOUCH\n')
    const planted = bash(program(`ln -s '${victim}' "${credDir}/previous-app-env-20261008T120000Z-$$-0"`))
    const pf = /FIRST=(\S+)/.exec(planted.out)?.[1]
    console.log(`  with a planted symlink at -0: ${pf}; victim intact: ${readFileSync(victim, 'utf8') === 'DO NOT TOUCH\n'}`)
    assert.match(pf ?? '', /-1$/, 'the planted name was skipped')
    assert.equal(readFileSync(victim, 'utf8'), 'DO NOT TOUCH\n', 'and what it pointed at was not written through')
  })
})

test('re-run: the summary names what was kept, changed and added, and never prints a value', async () => {
  await withTempDir('ims-env-sum-', async (dir) => {
    const old = join(dir, '.env')
    writeFileSync(old, OLD_ENV)
    const now = RENDERED.replace('APP_PORT=3000', 'APP_PORT=3001')
    const r = bash([LIB, `load_existing_env '${old}'`, 'ENV_BACKUP_FILE=/opt/app/.env.bak-x', `rendered='${now}'`,
      'render_preserved_env_keys "${rendered}" > /dev/null', 'print_env_rewrite_summary "${rendered}"'].join('\n'))
    console.log(`  summary: ${JSON.stringify(r.out.split('\n').map((l) => l.slice(0, 110)))}`)
    assert.match(r.out, /Backup \(root-only, mode 600\): \/opt\/app\/\.env\.bak-x/)
    assert.match(r.out, /kept as it was.*TRUSTED_PROXY_IPS/)
    assert.match(r.out, /values this run changed \(1\): APP_PORT/)
    assert.match(r.out, /keys this run added \(1\): NEW_KEY/)
    for (const secret of ['whsec_old', 'cs_old', 'ck_old', 'old-auth', '10.0.0.1']) assert.doesNotMatch(r.out, new RegExp(secret), `${secret} must not be printed`)
  })
})

test('re-run: export/spaced forms and multi-line quoted values are read whole; anything else is unclassified', async () => {
  await withTempDir('ims-env-ml-', async (dir) => {
    const old = join(dir, '.env')
    writeFileSync(old, [
      'A=1',
      'export B=2',
      'C = 3',
      'KEY="BEGIN-OF-VALUE',
      'line two with = and #',
      'END-OF-VALUE"',
      "SQ='one",
      "two'",
      'D="a \\"quoted\\" word"',
      'not a key value line',
      'E="never closed',
      'F=6',
      '',
    ].join('\n'))
    const r = bash([LIB, `load_existing_env '${old}'`,
      'echo "UNCLASSIFIED=${EXISTING_ENV_UNCLASSIFIED[*]}"',
      'for k in A B C KEY SQ D F; do printf "%s|%s|line %s\\n" "$k" "${EXISTING_ENV[$k]-<unset>}" "${EXISTING_ENV_LINENO[$k]-?}"; done'].join('\n'))
    console.log(`  loader: ${JSON.stringify(r.out.split('\n').slice(0, 14))}`)
    assert.match(r.out, /UNCLASSIFIED=10 11\b/, 'the prose line (10) and the quoted value that never closes (11) are the only unclassified lines')
    assert.match(r.out, /^B\|2\|line 2$/m, '`export KEY=v` is read as KEY=v')
    assert.match(r.out, /^C\| 3\|line 3$/m, '`KEY = v` is read as KEY with that value')
    assert.match(r.out, /^KEY\|"BEGIN-OF-VALUE$/m, 'a multi-line quoted value starts at its first line...')
    assert.match(r.out, /^END-OF-VALUE"\|line 4$/m, '...and ends with its closing line (one value; the middle lines are not keys of their own)')
    assert.match(r.out, /^D\|"a \\"quoted\\" word"\|line 9$/m, 'an escaped quote does not close a double-quoted value')
    assert.match(r.out, /^F\|6\|line 12$/m, 'and reading resumes after an unclosed value')
    // The caller refuses the rewrite before anything has changed.
    const lines = INSTALL.split('\n')
    const start = lines.findIndex((l) => l === 'if ((${#EXISTING_ENV_UNCLASSIFIED[@]} > 0)); then')
    const end = lines.findIndex((l, i) => i > start && l === 'fi')
    assert.ok(start > 0 && end > start, 'precondition: the refusal block exists')
    const gate = lines.slice(start, end + 1).join('\n')
    const refused = bash([LIB, 'APP_DIR=/opt/app', `load_existing_env '${old}'`, gate, 'echo "CONTINUED"'].join('\n'))
    console.log(`  caller: ${JSON.stringify(refused.out.split('\n').filter((l) => /DIE|CONTINUED/.test(l)).map((l) => l.slice(0, 150)))}`)
    assert.equal(refused.status, 9)
    assert.match(refused.out, /DIE: .*2 line\(s\).*\(line numbers: 10 11\).*Nothing has been changed\./)
    assert.doesNotMatch(refused.out, /CONTINUED/)
    const clean = join(dir, 'clean.env')
    writeFileSync(clean, 'A=1\nexport B=2\nQ="x\ny"\n')
    const ok = bash([LIB, 'APP_DIR=/opt/app', `load_existing_env '${clean}'`, gate, 'echo "CONTINUED"'].join('\n'))
    assert.match(ok.out, /CONTINUED/, 'a file it can reproduce goes through')
  })
})

test('re-run: a multi-line value under an unlisted key is dropped from the new file and kept whole in the backup', async () => {
  await withTempDir('ims-env-mlc-', async (dir) => {
    const old = join(dir, '.env')
    writeFileSync(old, 'APP_PORT=3000\nCERT_PEM="first\nsecond=\nthird"\nTAIL=1\nOUTBOX_RETRY_BASE_MS="1\n2"\n')
    const r = bash([LIB, `load_existing_env '${old}'`, "rendered='APP_PORT=3000'", 'render_preserved_env_keys "${rendered}"; printf "BLOCK<<%s>>" "${ENV_PRESERVED_BLOCK}"; printf "DROPPED:%s\\n" "${ENV_REFUSED_KEYS[@]}"; printf "RAW<<%s>>" "$(printf "%s\\n" "${EXISTING_ENV_RAW[@]}")"'].join('\n'))
    console.log(`  multi-line: ${JSON.stringify(r.out.split('\n').filter((l) => /^DROPPED:/.test(l)))}`)
    const block = /BLOCK<<([\s\S]*?)>>/.exec(r.out)?.[1] ?? ''
    assert.doesNotMatch(block, /CERT_PEM/, 'the unlisted multi-line value is not carried')
    assert.doesNotMatch(block, /OUTBOX_RETRY_BASE_MS/, 'and a listed key whose value spans lines does not have the shape of a number')
    assert.match(r.out, /DROPPED:CERT_PEM .*not on the list/)
    assert.match(r.out, /DROPPED:OUTBOX_RETRY_BASE_MS .*does not have the shape of a int setting/)
    assert.match(r.out, /RAW<<[\s\S]*CERT_PEM="first\nsecond=\nthird"/, 'the backup lines still hold the whole value')
  })
})

const CARRY_ADMIN = 'postgresql://deployadmin:Adm1nPassw0rd@127.0.0.1:5432/db'

test('re-run: nothing outside the carry list reaches the new file, whatever it is called or encoded as; the reason is listed, the value never printed', async () => {
  await withTempDir('ims-env-carry-', async (dir) => {
    const old = join(dir, '.env')
    const b64 = Buffer.from(CARRY_ADMIN).toString('base64')
    const hex = Buffer.from(CARRY_ADMIN).toString('hex')
    const layered = [...Array(6)].reduce((acc: string) => encodeURIComponent(acc), 'x/Adm1nPassw0rd') // six layers
    writeFileSync(old, [
      'APP_PORT=3000',
      `DIRECT_URL=${CARRY_ADMIN}`,
      `MIGRATION_DATABASE_URL=${CARRY_ADMIN}`,
      'PGPASSWORD=Adm1nPassw0rd',
      `direct_url=${CARRY_ADMIN}`,
      `export SHADOW_DATABASE_URL=${CARRY_ADMIN}`,
      'REPORTING_CONN=postgres://reader:readerpw@db.example.test/reports',
      'PROXYISH=http://user:secretpw@proxy.example.test:3128',
      'INNOCUOUS_NOTE=copied from the admin file: Adm1nPassw0rd',
      `REPORTING_CONFIG=${b64}`,
      `REPORTING_HEX=${hex}`,
      `REPORTING_LAYERS=${layered}`,
      // ...and the same disguises under key names that ARE on the list: the shape rejects them.
      `OUTBOX_RETRY_BASE_MS=${b64}`,
      `PREFLIGHT_DB_CONNECT=${hex}`,
      `DATABASE_RESTORE_MAX_FILE_BYTES=${layered}`,
      'TRUSTED_PROXY_CIDRS=10.0.0.0/8,192.168.0.0/16',
      'REQUIRE_TRUSTED_PROXY_CONFIG=true',
      '',
    ].join('\n'))
    const r = bash([LIB, `DEPLOY_ADMIN_DATABASE_URL='${CARRY_ADMIN}'`, `load_existing_env '${old}'`, "rendered='APP_PORT=3000'",
      'render_preserved_env_keys "${rendered}"; echo "RC=$?"', 'printf "BLOCK<<%s>>\\n" "${ENV_PRESERVED_BLOCK}"',
      'ENV_BACKUP_FILE=/b; print_env_rewrite_summary "${rendered}"'].join('\n'))
    const block = /BLOCK<<([\s\S]*?)>>/.exec(r.out)?.[1] ?? ''
    console.log(`  carried block: ${JSON.stringify(block)}`)
    console.log(`  dropped: ${JSON.stringify(r.out.split('\n').filter((l) => /^WARN:     /.test(l)).map((l) => l.slice(10, 120)))}`)
    assert.match(r.out, /RC=0/)
    assert.deepEqual(block.split('\n').filter((l) => l && !l.startsWith('#')).sort(),
      ['REQUIRE_TRUSTED_PROXY_CONFIG=true', 'TRUSTED_PROXY_CIDRS=10.0.0.0/8,192.168.0.0/16'], 'ONLY the two well-formed listed keys are carried')
    for (const gone of ['DIRECT_URL', 'MIGRATION_DATABASE_URL', 'PGPASSWORD', 'direct_url', 'SHADOW_DATABASE_URL', 'REPORTING_CONN', 'PROXYISH', 'INNOCUOUS_NOTE', 'REPORTING_CONFIG', 'REPORTING_HEX', 'REPORTING_LAYERS']) {
      assert.match(r.out, new RegExp(`WARN:     ${gone} \\(line \\d+\\): not on the list of settings a re-run carries over`), `${gone} must be listed as dropped`)
    }
    for (const listed of ['OUTBOX_RETRY_BASE_MS', 'PREFLIGHT_DB_CONNECT', 'DATABASE_RESTORE_MAX_FILE_BYTES']) {
      assert.match(r.out, new RegExp(`WARN:     ${listed} \\(line \\d+\\): the value does not have the shape`), `${listed} with an encoded blob must fail its shape`)
    }
    for (const secret of ['Adm1nPassw0rd', 'readerpw', 'secretpw', b64, hex]) assert.doesNotMatch(r.out.replace(/BLOCK<<[\s\S]*?>>/, ''), new RegExp(secret.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')), 'no value is ever printed')
  })
})

test('re-run: the carry list is the ONLY path — property check over many innocuous unknown keys, and over the shapes', () => {
  const names = ['MY_FEATURE_FLAG', 'LOG_LEVEL', 'SENTRY_ENVIRONMENT', 'TZ', 'lowercase_key', 'trusted_proxy_ips', 'Trusted_Proxy_Ips', 'X', 'A_B_C_D', 'XERO_UNLISTED', 'WC_UNLISTED', 'REQUIRE_TRUSTED_PROXY_CONFIG_X']
  const body = names.map((n) => `EXISTING_ENV[${n}]=on`).join('; ')
  const r = bash([LIB, 'declare -A EXISTING_ENV_LINENO=()', body, 'render_preserved_env_keys "APP_PORT=3000"; printf "KEPT<<%s>>" "${ENV_KEPT_KEYS[*]-}"; printf "N=%s" "${#ENV_REFUSED_KEYS[@]}"'].join('\n'))
  console.log(`  ${names.length} innocuous unknown keys: ${r.out.trim().split('\n').pop()}`)
  assert.match(r.out, /KEPT<<>>/, 'not one innocuous unknown key is carried')
  assert.match(r.out, new RegExp(`N=${names.length}$`))
  // The shapes: accepted and rejected examples per shape, so a loosened class is red.
  const ok: Record<string, string[]> = {
    bool: ['true', 'false', '1', '0'], int: ['0', '5000', '123456789012'], word: ['redis', 'memory', 'report-only'],
    hostlist: ['10.0.0.1', '10.0.0.0/8,192.168.1.1', '::1,fe80::1', 'proxy.example.test'],
    idlist: ['tenant-a', 'a,b,c'], names: ["Acme Ltd,O'Neil & Sons"], origin: ['https://shop.example.test', 'http://localhost:3000'],
    timestamp: ['2026-10-01', '2026-10-01T09:00:00Z', '2026-10-01T09:00:00.000+01:00'],
  }
  const bad: Record<string, string[]> = {
    bool: ['yes', 'TRUE', ''], int: ['12a', '-1', '1234567890123'], word: ['9x', 'a b', 'redis;rm', 'x'.repeat(40)],
    hostlist: ['10.0.0.1 10.0.0.2', 'a=b', 'a%2Fb', 'QWxhZGRpbjpvcGVu==', 'x'.repeat(65)], idlist: ['a b', 'a;b', 'postgres://x'], names: ['a%2Fb', 'a=b'],
    origin: ['ftp://x', 'https://u:p@h', 'https://h/path'], timestamp: ['yesterday', '2026-10-01 09:00'],
  }
  let checks = 0
  for (const shape of Object.keys(ok)) {
    for (const v of ok[shape]) { assert.equal(bash([LIB, `env_value_has_shape '${shape}' '${v.replace(/'/g, "'\\''")}'; echo "RC=$?"`].join('\n')).out.trim().split('\n').pop(), 'RC=0', `${shape} accepts ${v}`); checks++ }
    for (const v of bad[shape]) { assert.equal(bash([LIB, `env_value_has_shape '${shape}' '${v}'; echo "RC=$?"`].join('\n')).out.trim().split('\n').pop(), 'RC=1', `${shape} rejects ${v}`); checks++ }
  }
  console.log(`  shape table: ${checks} accept/reject checks`)
  // Length cap and residual escapes.
  assert.equal(bash([LIB, `env_value_has_shape int "${'1'.repeat(5000)}"; echo "RC=$?"`].join('\n')).out.trim().split('\n').pop(), 'RC=1')
  const six = 'a%252525252525252F'
  const esc = (v: string) => bash([LIB, `env_value_has_residual_escape '${v}'; echo "RC=$?"`].join('\n')).out.trim().split('\n').pop()
  console.log(`  residual escape: 6-layer ${esc(six)}, plain ${esc('plain-value')}, one layer ${esc('a%2Fb')}`)
  assert.equal(esc(six), 'RC=0', 'a value encoded more deeply than the decode passes is refused, not passed')
  assert.equal(esc('plain-value'), 'RC=1')
  assert.equal(esc('a%2Fb'), 'RC=1', 'what the decode passes fully resolve is not "residual"')
})

test('re-run: the admin-material checks need the admin credential to be known, and ordinary keys pass without it', async () => {
  const check = (key: string, value: string, admin: string) => bash([LIB, admin ? `DEPLOY_ADMIN_DATABASE_URL='${admin}'` : 'DEPLOY_ADMIN_DATABASE_URL=""',
    `env_key_carry_check '${key}' '${value}'; echo "RC=$? REASON=[$ENV_REFUSAL_REASON]"`].join('\n')).out.trim().split('\n').pop()
  const rows: Array<[string, string, string, string]> = [
    ['TRUSTED_PROXY_IPS', '10.0.0.1', CARRY_ADMIN, 'RC=0 REASON=[]'],
    ['NOTE', 'has Adm1nPassw0rd inside', CARRY_ADMIN, "RC=1 REASON=[the value contains the deploy admin's password]"],
    ['NOTE', 'has Adm1nPassw0rd inside', '', 'RC=0 REASON=[]'],
    ['NOTE', 'x@deployadmin:y', CARRY_ADMIN, 'RC=0 REASON=[]'],
    ['NOTE', 'ssh://deployadmin@host/x', CARRY_ADMIN, 'RC=1 REASON=[the value names the deploy admin role as a connection user]'],
    ['PGSSLMODE', 'require', '', 'RC=1 REASON=[the name looks like a database connection setting]'],
    ['SUPERUSER_FLAG', '1', '', 'RC=1 REASON=[the name looks like a database connection setting]'],
    ['FEATURE_X', 'on', '', 'RC=0 REASON=[]'],
  ]
  for (const [key, value, admin, want] of rows) {
    const got = check(key, value, admin)
    console.log(`  ${key}=${value.slice(0, 22)} admin=${admin ? 'known' : 'unknown'} -> ${got}`)
    assert.equal(got, want)
  }
})

/** A block of shipped lines from `first` through `last` inclusive. */
function shippedBlock(first: RegExp, last: RegExp): string {
  const lines = INSTALL.split('\n')
  const start = lines.findIndex((l) => first.test(l))
  const end = lines.findIndex((l, i) => i >= start && last.test(l))
  assert.ok(start > 0 && end >= start, `precondition: block ${first} .. ${last} found (${start}..${end})`)
  return lines.slice(start, end + 1).join('\n')
}

const WC_BLOCK = shippedBlock(/^prompt WC_STORE_URL /, /^unset _wc_name$/)

const wcProgram = (existing: string, exports: string): string =>
  ['set -uo pipefail', 'NON_INTERACTIVE=true', 'declare -A EXISTING_ENV=()', existing,
    shippedFunction(INSTALL, 'existing_env'), shippedFunction(INSTALL, 'prompt'), exports, WC_BLOCK,
    'echo "URL=[${WC_STORE_URL}] KEY=[${WC_CONSUMER_KEY}] SECRET=[${WC_CONSUMER_SECRET}] HOOK=[${WC_WEBHOOK_SECRET}]"'].join('\n')

const WC_EXISTING = 'EXISTING_ENV[WC_STORE_URL]=https://shop.example.test; EXISTING_ENV[WC_CONSUMER_KEY]=ck_old; EXISTING_ENV[WC_CONSUMER_SECRET]=cs_old; EXISTING_ENV[WC_WEBHOOK_SECRET]=whsec_old'

test('re-run: WooCommerce credentials and the webhook secret default to the installed ones; only "none" clears', () => {
  const kept = bash(wcProgram(WC_EXISTING, ''))
  const fresh = bash(wcProgram('', ''))
  const cleared = bash(wcProgram(WC_EXISTING, 'export WC_STORE_URL=none WC_CONSUMER_KEY=none WC_CONSUMER_SECRET=none WC_WEBHOOK_SECRET=none'))
  const blank = bash(wcProgram(WC_EXISTING, 'export WC_STORE_URL= WC_WEBHOOK_SECRET='))
  const override = bash(wcProgram(WC_EXISTING, 'export WC_WEBHOOK_SECRET=whsec_new'))
  console.log(`  WC re-run default -> ${kept.out.trim()}`)
  console.log(`  WC first install  -> ${fresh.out.trim().replace(/HOOK=\[[0-9a-f]+\]/, 'HOOK=[<random>]')}`)
  console.log(`  WC none -> ${cleared.out.trim()}; blank export -> ${blank.out.trim()}; override -> ${override.out.trim()}`)
  assert.match(kept.out, /URL=\[https:\/\/shop\.example\.test\] KEY=\[ck_old\] SECRET=\[cs_old\] HOOK=\[whsec_old\]/)
  assert.match(fresh.out, /URL=\[\] KEY=\[\] SECRET=\[\] HOOK=\[[0-9a-f]{32}\]/, 'a first install still mints a webhook secret')
  assert.match(cleared.out, /URL=\[\] KEY=\[\] SECRET=\[\] HOOK=\[\]/)
  assert.match(blank.out, /URL=\[https:\/\/shop\.example\.test\].*HOOK=\[whsec_old\]/, 'a blank is not a request to clear')
  assert.match(override.out, /HOOK=\[whsec_new\]/)
})

test('re-run: the domain, port and upload-scanner settings default to what is installed', () => {
  const dom = shippedBlock(/^EXISTING_APP_DOMAIN=/, /^prompt APP_PORT /)
  const ask = (existing: string) => bash(['set -uo pipefail', 'NON_INTERACTIVE=true', 'declare -A EXISTING_ENV=()', existing,
    shippedFunction(INSTALL, 'existing_env'), shippedFunction(INSTALL, 'prompt'), dom, 'echo "DOMAIN=[${APP_DOMAIN}] PORT=[${APP_PORT}]"'].join('\n'))
  const installed = ask('EXISTING_ENV[NEXT_PUBLIC_APP_URL]=https://ims.example.test; EXISTING_ENV[APP_PORT]=3055')
  const firstRun = ask('')
  console.log(`  domain/port: installed -> ${installed.out.trim()}; first install -> ${firstRun.out.trim()}`)
  assert.match(installed.out, /DOMAIN=\[ims\.example\.test\] PORT=\[3055\]/)
  assert.match(firstRun.out, /DOMAIN=\[ims\.localhost\] PORT=\[3000\]/)

  const scan = shippedBlock(/^FILE_SCAN_MODE="\$\(existing_env /, /^FILE_SCAN_TIMEOUT_MS="/)
  const scanAsk = (existing: string) => bash(['set -uo pipefail', 'declare -A EXISTING_ENV=()', existing, shippedFunction(INSTALL, 'existing_env'), scan,
    'echo "MODE=[${FILE_SCAN_MODE}] CMD=[${FILE_SCAN_COMMAND}] TIMEOUT=[${FILE_SCAN_TIMEOUT_MS}]"'].join('\n'))
  const tuned = scanAsk('EXISTING_ENV[FILE_SCAN_MODE]=clamav; EXISTING_ENV[FILE_SCAN_COMMAND]=/usr/bin/clamdscan; EXISTING_ENV[FILE_SCAN_TIMEOUT_MS]=90000')
  const factory = scanAsk('')
  console.log(`  scanner: tuned -> ${tuned.out.trim()}; first install -> ${factory.out.trim()}`)
  assert.match(tuned.out, /MODE=\[clamav\] CMD=\[\/usr\/bin\/clamdscan\] TIMEOUT=\[90000\]/)
  assert.match(factory.out, /MODE=\[disabled\] CMD=\[\] TIMEOUT=\[30000\]/)
})

test('re-run: the .env write backs up and keeps before it replaces; the backup is outside the tree', () => {
  const body = shippedFunction(INSTALL, 'write_app_env_file')
  const order = ['render_app_env_file', 'render_preserved_env_keys', 'write_env_backup', 'publish_durable_file'].map((n) => body.indexOf(n))
  console.log(`  write_app_env_file call order offsets: ${order.join(' < ')}`)
  assert.ok(order.every((o) => o > 0) && order.every((o, i) => i === 0 || o > order[i - 1]), 'render, preserve, back up, then publish')
  const backup = shippedFunction(INSTALL, 'write_env_backup')
  assert.match(backup, /candidate="\$\{DB_ADMIN_CREDENTIAL_DIR\}\/previous-app-env-/, 'the backup is made in the root-only directory')
  assert.doesNotMatch(backup, /APP_DIR/, 'and nowhere in the application tree')
  assert.match(backup, /publish_durable_file "\$\{ENV_BACKUP_FILE\}" "\$\{ENV_BACKUP_OWNER\}" 600/)
  assert.match(INSTALL, /^ENV_BACKUP_OWNER="root:root"$/m, 'owned by root')
  assert.ok(!/\.env\.bak-\$\{/.test(backup), 'the installer no longer WRITES an in-tree backup name')
  assert.match(INSTALL, /^print_env_rewrite_summary "\$\{ENV_LAST_RENDERED\}"$/m, 'and the summary is printed after the write')
})

test('re-run: an ENCODED admin password or a libpq keyword/value string cannot slip through under an innocuous key', () => {
  const ENC_ADMIN = 'postgresql://deployadmin:A%40B-Pass%2Fw0rd@127.0.0.1:5432/db'
  const check = (value: string, admin = ENC_ADMIN) =>
    bash([LIB, `DEPLOY_ADMIN_DATABASE_URL='${admin}'`, `env_key_carry_check 'REPORTING_DSN' '${value}'; echo "RC=$? REASON=[$ENV_REFUSAL_REASON]"`].join('\n')).out.trim().split('\n').pop() ?? ''
  const refused: Array<[string, string]> = [
    ['the exact review case: decoded password in a libpq string', 'host=db.example user=deployadmin password=A@B-Pass/w0rd dbname=app'],
    ['decoded password alone', 'x A@B-Pass/w0rd y'],
    ['encoded as written in the URL', 'x A%40B-Pass%2Fw0rd y'],
    ['encoded with lowercase hex', 'x A%40B-Pass%2fw0rd y'],
    ["single-quoted password setting", "host=db password='other secret' dbname=app"],
    ['double-quoted, spaced password setting', 'host=db password = "other" dbname=app'],
    ['user setting naming the admin role', 'host=db user=deployadmin dbname=app'],
    ['quoted user setting naming the admin role', "host=db user='deployadmin' dbname=app"],
    ['spaced, double-quoted user setting', 'host=db user = "deployadmin"'],
    ['postgres URL without a password naming the admin', 'ssh://deployadmin@host/x'],
  ]
  for (const [label, value] of refused) {
    const got = check(value)
    console.log(`  ${label}: ${got}`)
    assert.match(got, /^RC=1 REASON=\[.+\]$/, `${label} must be refused`)
  }
  // Isolating: with the admin credential UNKNOWN, a plain keyword string with no password and another role passes.
  const ok = bash([LIB, 'DEPLOY_ADMIN_DATABASE_URL=""', "env_key_carry_check 'REPORTING_DSN' 'host=db user=reader dbname=app'; echo \"RC=$? REASON=[$ENV_REFUSAL_REASON]\""].join('\n')).out.trim().split('\n').pop()
  console.log(`  innocuous keyword string, admin unknown: ${ok}`)
  assert.equal(ok, 'RC=0 REASON=[]')
  // The decoder and encoder agree on the review's password.
  const rt = bash([LIB, "env_percent_decode 'A%40B-Pass%2Fw0rd' d; env_percent_encode \"$d\" e; echo \"$d|$e\""].join('\n')).out.trim()
  console.log(`  decode/encode: ${rt}`)
  assert.equal(rt, 'A@B-Pass/w0rd|A%40B-Pass%2Fw0rd')
})

// ---------------------------------------------------------------------------
// review round 3: encoded variants, and the short-password policy
// ---------------------------------------------------------------------------

const leaks = (value: string, adminUrl: string): string =>
  bash([LIB, `DEPLOY_ADMIN_DATABASE_URL='${adminUrl}'`, `env_key_carry_check 'REPORTING_NOTE' '${value}'; echo "RC=$? REASON=[$ENV_REFUSAL_REASON]"`].join('\n')).out.trim().split('\n').pop() ?? ''

test('re-run: mixed-case hex, double-, triple-encoded and plus-for-space copies of the admin password are all refused', () => {
  const admin = 'postgresql://deployadmin:A%2FB%3ASecret@127.0.0.1:5432/db' // decoded: A/B:Secret
  const refused: Array<[string, string]> = [
    ['as written (upper-case hex)', 'x A%2FB%3ASecret y'],
    ['mixed-case hex (the review case)', 'x A%2fB%3ASecret y'],
    ['all lower-case hex', 'x A%2fb%3asecret y'.replace('b%3asecret', 'B%3aSecret')],
    ['double-encoded (the review case)', 'x A%252FB%253ASecret y'],
    ['double-encoded, mixed case', 'x A%252fB%253aSecret y'],
    ['triple-encoded', 'x A%25252FB%25253ASecret y'],
    ['decoded', 'x A/B:Secret y'],
    ['inside a longer setting', 'cache=redis;token=A%252FB%253ASecret;ttl=5'],
  ]
  for (const [label, value] of refused) {
    const got = leaks(value, admin)
    console.log(`  ${label}: ${got}`)
    assert.equal(got, "RC=1 REASON=[the value contains the deploy admin's password]", label)
  }
  // plus-for-space: a password with a space, written with '+' in a form-encoded copy.
  const spaced = 'postgresql://deployadmin:pass%20word-9@127.0.0.1:5432/db'
  for (const value of ['x pass+word-9 y', 'x pass%20word-9 y', 'x pass word-9 y', 'x pass%2520word-9 y']) {
    const got = leaks(value, spaced)
    console.log(`  space variant ${JSON.stringify(value)}: ${got}`)
    assert.match(got, /^RC=1 /, value)
  }
  // Isolating: an unrelated value is not refused, so the arms above are not vacuous.
  assert.equal(leaks('x something-else y', admin), 'RC=0 REASON=[]')
})

test('re-run: the password-length floor is 8 — 7 characters ends the run when there are settings to screen, 8 is screened', async () => {
  await withTempDir('ims-env-floor-', async (dir) => {
    const lines = INSTALL.split('\n')
    const start = lines.findIndex((l) => l === 'env_admin_password_decoded')
    const end = lines.findIndex((l, i) => i > start && l === 'fi')
    assert.ok(start > 0 && end > start, 'precondition: the gate block exists')
    // the block ends with TWO nested fi lines; take through the outer one
    const gate = lines.slice(start, end + 2).join('\n')
    const old = join(dir, '.env')
    writeFileSync(old, 'APP_PORT=3000\nAUTH_SECRET=a\nTRUSTED_PROXY_IPS=10.0.0.1\n')
    const bareOld = join(dir, 'bare.env')
    writeFileSync(bareOld, 'APP_PORT=3000\nAUTH_SECRET=a\n')
    const run = (file: string, adminUrl: string) => bash([LIB, `DEPLOY_ADMIN_DATABASE_URL='${adminUrl}'`, `load_existing_env '${file}'`, gate, 'echo CONTINUED'].join('\n'))
    const cases: Array<[string, string, string, boolean]> = [
      ['7 characters, settings to screen', old, 'postgresql://deployadmin:abcdefg@h/db', true],
      ['the exact review case: password x', old, 'postgresql://deployadmin:x@db/app', true],
      ['8 characters, settings to screen', old, 'postgresql://deployadmin:abcdefgh@h/db', false],
      ['7 characters but an encoded 8-char form decodes to 7', old, 'postgresql://deployadmin:abc%64efg@h/db', true],
      ['7 characters, NOTHING to screen', bareOld, 'postgresql://deployadmin:abcdefg@h/db', false],
      ['no password in the admin URL', old, 'postgresql://deployadmin@h/db', false],
    ]
    for (const [label, file, url, refusedRun] of cases) {
      const r = run(file, url)
      console.log(`  ${label}: ${refusedRun ? 'refused' : 'continues'} -> rc=${r.status}`)
      assert.equal(r.status, refusedRun ? 9 : 0, `${label}\n${r.out}`)
      if (refusedRun) {
        assert.ok(r.out.includes(TOO_SHORT_MESSAGE), 'the diagnostic is the single-sourced sentence')
        assert.match(r.out, /Nothing has been changed\./)
        assert.doesNotMatch(r.out, /CONTINUED/)
      } else assert.match(r.out, /CONTINUED/)
    }
    assert.equal(TOO_SHORT_MESSAGE, 'the deploy admin password is too short to screen preserved settings against; set a password of at least 8 characters or remove the extra settings and re-run.')
    assert.ok(read('docs/installation.md').includes(TOO_SHORT_MESSAGE), 'and the docs quote the same sentence')
  })
})

test('re-run: the template key list the early gate uses is exactly the keys render_app_env_file writes', () => {
  const body = shippedFunction(INSTALL, 'render_app_env_file')
  const written = [...new Set(body.split('\n').map((l) => /^([A-Za-z_][A-Za-z0-9_]*)=/.exec(l)?.[1]).filter((k): k is string => Boolean(k)))].sort()
  const listed = (/^ENV_TEMPLATE_KEYS=\((.*)\)$/m.exec(INSTALL)?.[1] ?? '').split(/\s+/).filter(Boolean).sort()
  console.log(`  template keys written: ${written.length}; listed: ${listed.length}`)
  assert.ok(written.length >= 25, 'precondition: the template was parsed')
  assert.deepEqual(listed, written)
})

// ---------------------------------------------------------------------------
// review round 5: the loader's QUOTES, security settings, and the in-tree backups of earlier versions
// ---------------------------------------------------------------------------

const GATE_START = 'for _sec_key in "${ENV_PRESERVE_SECURITY_KEYS[@]}"; do'
const securityGate = (): string => {
  const lines = INSTALL.split('\n')
  const start = lines.findIndex((l) => l === GATE_START)
  const end = lines.findIndex((l, i) => i > start && l === 'unset _sec_key')
  assert.ok(start > 0 && end > start, 'precondition: the security-setting gate exists')
  return lines.slice(start, end + 1).join('\n')
}

test('re-run: a security setting written with quotes, export, CRLF or an inline comment is carried with the same effective meaning, in one canonical form', async () => {
  await withTempDir('ims-env-eff-', async (dir) => {
    const variants: Array<[string, (k: string, v: string) => string]> = [
      ['bare', (k, v) => `${k}=${v}`],
      ['double-quoted', (k, v) => `${k}="${v}"`],
      ['single-quoted', (k, v) => `${k}='${v}'`],
      ['export-prefixed', (k, v) => `export ${k}=${v}`],
      ['export + double-quoted', (k, v) => `export ${k}="${v}"`],
      ['spaces around the value', (k, v) => `${k}=  ${v}   `],
      ['inline comment', (k, v) => `${k}=${v} # why`],
      ['double-quoted + inline comment', (k, v) => `${k}="${v}" # why`],
      ['single-quoted + inline comment', (k, v) => `${k}='${v}'   # why`],
      ['CRLF line ending', (k, v) => `${k}=${v}\r`],
      ['CRLF + double-quoted', (k, v) => `${k}="${v}"\r`],
    ]
    const wants: Array<[string, string]> = [['REQUIRE_TRUSTED_PROXY_CONFIG', 'true'], ['TRUSTED_PROXY_IPS', '10.0.0.1,10.0.0.2'], ['XERO_ALLOWED_TENANT_IDS', 'tenant-a,tenant-b']]
    let checked = 0
    for (const [label, form] of variants) {
      const old = join(dir, `${checked}.env`)
      writeFileSync(old, ['APP_PORT=3000', ...wants.map(([k, v]) => form(k, v)), ''].join(label.includes('CRLF') ? '\r\n'.replace('\r', '') : '\n'))
      const r = bash([LIB, `load_existing_env '${old}'`, "rendered='APP_PORT=3000'", 'render_preserved_env_keys "${rendered}"; echo "RC=$?"', 'printf "BLOCK<<%s>>" "${ENV_PRESERVED_BLOCK}"', 'printf "DROPPED=%s" "${#ENV_REFUSED_KEYS[@]}"'].join('\n'))
      const block = /BLOCK<<([\s\S]*?)>>/.exec(r.out)?.[1] ?? ''
      console.log(`  ${label}: ${JSON.stringify(block.split('\n').filter((l) => l && !l.startsWith('#')))} dropped=${/DROPPED=(\d+)/.exec(r.out)?.[1]}`)
      assert.match(r.out, /RC=0/, label)
      assert.deepEqual(block.split('\n').filter((l) => l && !l.startsWith('#')).sort(), wants.map(([k, v]) => `${k}=${v}`).sort(), `${label}: carried unquoted with the same effective value`)
      assert.match(r.out, /DROPPED=0/, label)
      checked++
    }
    assert.equal(checked, variants.length)
    // The canonical form is lossless for a value that needs quoting, and the loader would read it back the same.
    const canon = bash([LIB, "env_canonical_value \"Acme Ltd,O'Neil & Sons\" c; echo \"$c\"; env_effective_value \"$c\" e; echo \"$e\"", "env_canonical_value 10.0.0.1,10.0.0.2 d; echo \"$d\""].join('\n')).out.trim().split('\n')
    console.log(`  canonical forms: ${JSON.stringify(canon)}`)
    assert.deepEqual(canon, ['"Acme Ltd,O\'Neil & Sons"', "Acme Ltd,O'Neil & Sons", '10.0.0.1,10.0.0.2'])
  })
})

test('re-run: a security setting that cannot be carried REFUSES the run before anything is changed, naming the key and never the value; a non-security one is dropped and reported', async () => {
  await withTempDir('ims-env-sec-', async (dir) => {
    const gate = securityGate()
    const run = (content: string, admin = '') => {
      const old = join(dir, `s${Math.random().toString(36).slice(2)}.env`)
      writeFileSync(old, content)
      return bash([LIB, 'APP_DIR=/opt/app', admin ? `DEPLOY_ADMIN_DATABASE_URL='${admin}'` : 'DEPLOY_ADMIN_DATABASE_URL=""', `load_existing_env '${old}'`, gate, 'echo CONTINUED', "rendered='APP_PORT=3000'", 'render_preserved_env_keys "${rendered}"; echo "RC=$?"; printf "DROPPED:%s\\n" "${ENV_REFUSED_KEYS[@]}"'].join('\n'))
    }
    const cases: Array<[string, string, boolean]> = [
      ['REQUIRE_TRUSTED_PROXY_CONFIG not a boolean', 'REQUIRE_TRUSTED_PROXY_CONFIG=definitely-maybe\n', true],
      ['TRUSTED_PROXY_IPS holds an encoded blob', `TRUSTED_PROXY_IPS=${Buffer.from('postgresql://a:b@h/d').toString('base64')}\n`, true],
      ['XERO tenant allowlist with a space-separated list', 'XERO_ALLOWED_TENANT_IDS=a b\n', true],
      ['a write grant that is not a timestamp', 'MINTSOFT_WRITES_LIVE_FROM=whenever\n', true],
      ['TRUSTED_PROXY_IPS carries the admin password', `TRUSTED_PROXY_IPS=10.0.0.1,Adm1nPassw0rd\n`, true],
      ['a well-formed quoted security setting', 'REQUIRE_TRUSTED_PROXY_CONFIG="true"\nTRUSTED_PROXY_IPS=\'10.0.0.1\'\n', false],
      ['a NON-security setting that does not fit', 'OUTBOX_RETRY_BASE_MS=abc\n', false],
      ['an unlisted key', 'MY_FEATURE_FLAG=on\n', false],
    ]
    for (const [label, content, refused] of cases) {
      const r = run(`APP_PORT=3000\n${content}`, 'postgresql://deployadmin:Adm1nPassw0rd@h/db')
      console.log(`  ${label}: ${refused ? 'refused' : 'continues'} rc=${r.status}`)
      if (refused) {
        assert.equal(r.status, 9, label)
        assert.match(r.out, /DIE: .*\/\.env: [A-Z_]+ is a security setting that this installer cannot carry across/)
        assert.match(r.out, /Nothing has been changed\./)
        assert.doesNotMatch(r.out, /CONTINUED/)
        assert.doesNotMatch(r.out, /Adm1nPassw0rd|definitely-maybe|a b|whenever/, 'the value is never printed')
      } else {
        assert.equal(r.status, 0, `${label}\n${r.out}`)
        assert.match(r.out, /CONTINUED/)
      }
    }
    // Non-security keys that do not fit are dropped AND reported.
    const dropped = run('APP_PORT=3000\nOUTBOX_RETRY_BASE_MS=abc\nMY_FEATURE_FLAG=on\n')
    assert.match(dropped.out, /DROPPED:OUTBOX_RETRY_BASE_MS .*does not have the shape of a int setting/)
    assert.match(dropped.out, /DROPPED:MY_FEATURE_FLAG .*not on the list/)
  })
})

test('re-run: every security setting is on the carry list, and the sentence that refuses is single-sourced', () => {
  const security = (/^ENV_PRESERVE_SECURITY_KEYS=\(([\s\S]*?)^\)$/m.exec(INSTALL)?.[1] ?? '').split(/\s+/).filter(Boolean)
  const shapes = [...(/^declare -A ENV_PRESERVE_SHAPES=\(([\s\S]*?)^\)$/m.exec(INSTALL)?.[1] ?? '').matchAll(/\[([A-Z0-9_]+)\]=/g)].map((m) => m[1])
  console.log(`  ${security.length} security settings, all among the ${shapes.length} listed`)
  assert.ok(security.length >= 15 && shapes.length >= 30, 'precondition: both lists were parsed')
  assert.deepEqual(security.filter((k) => !shapes.includes(k)), [])
  for (const must of ['REQUIRE_TRUSTED_PROXY_CONFIG', 'TRUSTED_PROXY_IPS', 'XERO_ALLOWED_TENANT_IDS', 'XERO_WRITE_ALLOWED_TENANT', 'MINTSOFT_WRITE_ALLOWED', 'WC_WRITES_LIVE_FROM', 'ALLOW_DATABASE_RESTORE']) assert.ok(security.includes(must), must)
  const message = /^ENV_SECURITY_KEY_UNCARRIABLE_MESSAGE="(.*)"$/m.exec(INSTALL)?.[1] ?? ''
  assert.ok(message.length > 40 && read('docs/installation.md').includes('security setting'), 'the docs name the refusal')
})

test('re-run: the source sync spares in-tree .env.bak* files left by earlier installer versions (both rsync paths)', async () => {
  const lines = INSTALL.split('\n')
  const statements: string[] = []
  lines.forEach((l, i) => {
    if (!/^\s*rsync -a --delete \\$/.test(l)) return
    let end = i
    while (lines[end].endsWith('\\')) end++
    statements.push(lines.slice(i, end + 1).join('\n'))
  })
  console.log(`  rsync --delete statements: ${statements.length}`)
  assert.equal(statements.length, 2, 'precondition: the two source-sync paths were found')
  const synced = statements.filter((st) => /\.env'/.test(st))
  assert.equal(synced.length, 2)
  for (const st of statements) assert.match(st, /--exclude='\.env\.bak\*'/, 'each sync excludes the in-tree backups')
  // The statements are RUN: with the real rsync when the machine has one (the --delete is then observed to spare the
  // files), and always with a recording stand-in that proves what rsync would have been asked to spare.
  const haveRsync = bash('command -v rsync').status === 0
  console.log(`  real rsync available: ${haveRsync}`)
  await withTempDir('ims-env-rsync-', async (dir) => {
    const src = join(dir, 'src')
    const app = join(dir, 'app')
    mkdirSync(src); mkdirSync(app)
    writeFileSync(join(src, 'package.json'), '{}')
    writeFileSync(join(app, '.env.bak.20250101'), 'OLD BACKUP')
    writeFileSync(join(app, '.env.bak-20250102T000000Z'), 'OLD BACKUP 2')
    writeFileSync(join(app, '.env'), 'KEEP')
    for (const [i, statement] of statements.entries()) {
      const st = statement.replace(/"\$\{[A-Z_]+%\/\}\/"/, `"${src}/"`).replace(/"\$\{APP_DIR\}\/"/, `"${app}/"`)
      const recorded = bash(`rsync() { printf 'ARG %s\\n' "$@"; }\n${st}`)
      const args = recorded.out.split('\n').filter((l) => l.startsWith('ARG ')).map((l) => l.slice(4))
      console.log(`  sync path ${i + 1} asks rsync to spare: ${JSON.stringify(args.filter((a) => a.startsWith('--exclude')))}`)
      assert.ok(args.includes('--delete') && args.includes('--exclude=.env.bak*') && args.includes('--exclude=.env'), 'the sync deletes, and spares .env and .env.bak*')
      if (haveRsync) {
        writeFileSync(join(app, 'stale.txt'), 'delete me')
        const r = bash(st)
        assert.equal(r.status, 0, r.out)
        assert.ok(!readdirSync(app).includes('stale.txt'), 'precondition: --delete really ran')
        assert.equal(readFileSync(join(app, '.env.bak.20250101'), 'utf8'), 'OLD BACKUP')
        assert.equal(readFileSync(join(app, '.env.bak-20250102T000000Z'), 'utf8'), 'OLD BACKUP 2')
        assert.equal(readFileSync(join(app, '.env'), 'utf8'), 'KEEP')
      }
    }
  })
})
