/**
 * AN INSTALL.SH RE-RUN MUST NOT SILENTLY DISCARD WHAT THE OPERATOR ALREADY HAS IN .env (D4 re-run).
 *
 * The file was rewritten from a template: WooCommerce credentials were blanked, the webhook secret
 * was replaced with a fresh random one (breaking the signature check of every webhook WooCommerce
 * was already sending), hand-added variables (TRUSTED_PROXY_IPS ...) vanished, and nothing said so
 * and no copy was kept. Arms lift the SHIPPED functions and prompt lines into a `bash` and run them
 * over real files; each prints the precondition it reached.
 */
import assert from 'node:assert/strict'
import { spawnSync } from 'node:child_process'
import { chmodSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import test from 'node:test'

import { shippedFunction } from './real-postgres-cluster.ts'
import { withTempDir } from './temp-dir.ts'

const REPO = process.cwd()
const INSTALL = readFileSync(join(REPO, 'scripts/install.sh'), 'utf8')
const read = (rel: string): string => readFileSync(join(REPO, rel), 'utf8')

function bash(program: string): { status: number; out: string } {
  const r = spawnSync('bash', ['-c', program], {
    encoding: 'utf8',
    env: { PATH: process.env.PATH ?? '/usr/bin:/bin', LC_ALL: 'C' } as unknown as NodeJS.ProcessEnv,
  })
  return { status: r.status ?? -1, out: `${r.stdout ?? ''}${r.stderr ?? ''}` }
}

/** The previous run's file: one installer-owned key, secrets, and the hand-added keys the finding lost. */
const OLD_ENV = [
  '# generated by install.sh',
  'APP_PORT=3000',
  'AUTH_SECRET=old-auth',
  'WC_STORE_URL=https://shop.example.test',
  'WC_CONSUMER_KEY=ck_old',
  'WC_CONSUMER_SECRET=cs_old',
  'WC_WEBHOOK_SECRET=whsec_old',
  'TRUSTED_PROXY_IPS=10.0.0.1,10.0.0.2',
  'REQUIRE_TRUSTED_PROXY_CONFIG=true',
  'XERO_ALLOWED_TENANT_IDS=123e4567-e89b-12d3-a456-426614174000,123e4567-e89b-12d3-a456-426614174001',
  'MY_FEATURE_FLAG=on',
  'FILE_SCAN_MODE=clamav',
  '',
].join('\n')

const TOO_SHORT_MESSAGE = /^ENV_ADMIN_PASSWORD_TOO_SHORT_MESSAGE="(.*)"$/m.exec(INSTALL)?.[1] ?? ''

const LIB = [
  'set -uo pipefail',
  'exec 2>&1',
  'info() { echo "INFO: $*"; }; warn() { echo "WARN: $*"; }; error() { echo "ERROR: $*"; }',
  'die() { echo "DIE: $*"; exit 9; }',
  'APP_DIR=/opt/app; APP_USER=app; DB_ADMIN_CREDENTIAL_FILE=/etc/ims-db-admin/deploy-admin.env',
  'declare -A EXISTING_ENV=()',
  'declare -a EXISTING_ENV_RAW=() EXISTING_ENV_UNCLASSIFIED=() ENV_REFUSED_KEYS=()',
  'declare -A EXISTING_ENV_LINENO=()',
  'ENV_REFUSAL_REASON=""',
  /^ENV_ADMIN_PASSWORD_MIN_LENGTH=\d+$/m.exec(INSTALL)?.[0] ?? 'ENV_ADMIN_PASSWORD_MIN_LENGTH=UNSET',
  'ENV_ADMIN_PASSWORD_DECODED=""; ENV_UNOWNED_EXISTING_KEYS=()',
  `ENV_ADMIN_PASSWORD_TOO_SHORT_MESSAGE=${JSON.stringify(TOO_SHORT_MESSAGE)}`,
  /^ENV_TEMPLATE_KEYS=.*$/m.exec(INSTALL)?.[0] ?? 'ENV_TEMPLATE_KEYS=()',
  'ENV_FILE_STATE=absent',
  'ENV_BACKUP_FILE=""; ENV_KEPT_KEYS=(); ENV_PRESERVED_BLOCK=""',
  shippedFunction(INSTALL, 'existing_env'),
  shippedFunction(INSTALL, 'env_value_closes_quote'),
  shippedFunction(INSTALL, 'load_existing_env'),
  shippedFunction(INSTALL, 'env_percent_decode'),
  shippedFunction(INSTALL, 'env_percent_encode'),
  /^declare -A ENV_PRESERVE_SHAPES=\([\s\S]*?^\)$/m.exec(INSTALL)?.[0] ?? 'declare -A ENV_PRESERVE_SHAPES=()',
  'ENV_PRESERVE_MAX_LENGTH=4096; ENV_BACKUP_OWNER="$(id -un):$(id -gn)"',
  shippedFunction(INSTALL, 'env_value_has_shape'),
  shippedFunction(INSTALL, 'env_value_has_residual_escape'),
  /^ENV_PRESERVE_SECURITY_KEYS=\([\s\S]*?^\)$/m.exec(INSTALL)?.[0] ?? 'ENV_PRESERVE_SECURITY_KEYS=()',
  /^ENV_SECURITY_KEY_UNCARRIABLE_MESSAGE=".*"$/m.exec(INSTALL)?.[0] ?? 'ENV_SECURITY_KEY_UNCARRIABLE_MESSAGE=x',
  "ENV_PRESERVE_VALUE=''; declare -A ENV_PRESERVED_EFFECTIVE=()",
  shippedFunction(INSTALL, 'env_effective_value'),
  shippedFunction(INSTALL, 'env_canonical_value'),
  shippedFunction(INSTALL, 'env_preserve_decision'),
  shippedFunction(INSTALL, 'env_key_is_security_control'),
  /^ENV_DECODE_MAX_DEPTH=\d+$/m.exec(INSTALL)?.[0] ?? 'ENV_DECODE_MAX_DEPTH=UNSET',
  /^ENV_DECODE_MAX_WORK=\d+$/m.exec(INSTALL)?.[0] ?? 'ENV_DECODE_MAX_WORK=UNSET',
  'ENV_DECODE_LAYERS=(); ENV_DECODE_CHILDREN=(); ENV_DECODE_UNBOUNDED=0',
  /^ENV_NEEDLE_MAX=\d+$/m.exec(INSTALL)?.[0] ?? 'ENV_NEEDLE_MAX=UNSET',
  /^ENV_NEEDLE_MIN_LENGTH=\d+$/m.exec(INSTALL)?.[0] ?? 'ENV_NEEDLE_MIN_LENGTH=UNSET',
  'ENV_NEEDLES=(); ENV_NEEDLES_SECRET=""; ENV_NEEDLES_READY=0; ENV_NEEDLES_OVERFLOW=0; ENV_ENC_OUT=()',
  shippedFunction(INSTALL, 'env_b64_encode'),
  shippedFunction(INSTALL, 'env_encode_variants'),
  shippedFunction(INSTALL, 'env_admin_needles'),
  shippedFunction(INSTALL, 'env_layers_contain_needle'),
  shippedFunction(INSTALL, 'env_token_decode'),
  shippedFunction(INSTALL, 'env_decode_children'),
  shippedFunction(INSTALL, 'env_decode_seen'),
  shippedFunction(INSTALL, 'env_value_decode_layers'),
  shippedFunction(INSTALL, 'env_value_leaks_secret'),
  shippedFunction(INSTALL, 'env_admin_password_decoded'),
  shippedFunction(INSTALL, 'env_unowned_existing_keys'),
  shippedFunction(INSTALL, 'env_key_carry_check'),
  shippedFunction(INSTALL, 'env_key_is_admin_credential'),
  shippedFunction(INSTALL, 'render_preserved_env_keys'),
  shippedFunction(INSTALL, 'write_env_backup'),
  shippedFunction(INSTALL, 'print_env_rewrite_summary'),
].join('\n')

/** The template output of a re-run, reduced to the keys the arms care about. */
const RENDERED = ['APP_PORT=3000', 'AUTH_SECRET=old-auth', 'WC_STORE_URL=https://shop.example.test', 'WC_CONSUMER_KEY=ck_old', 'WC_CONSUMER_SECRET=cs_old', 'WC_WEBHOOK_SECRET=whsec_old', 'FILE_SCAN_MODE=clamav', 'NEW_KEY=1'].join('\n')

test('re-run: only keys on the carry list are carried, verbatim; every other unowned key is dropped and reported', async () => {
  await withTempDir('ims-env-keep-', async (dir) => {
    const old = join(dir, '.env')
    writeFileSync(old, OLD_ENV)
    const r = bash([LIB, `load_existing_env '${old}'`, `rendered='${RENDERED}'`,
      'render_preserved_env_keys "${rendered}"; echo "RC=$?"', 'printf "BLOCK<<%s>>" "${ENV_PRESERVED_BLOCK}"', 'echo "KEPT=${ENV_KEPT_KEYS[*]}"',
      'printf "DROPPED:%s\\n" "${ENV_REFUSED_KEYS[@]}"'].join('\n'))
    console.log(`  precondition: previous file read; kept -> ${JSON.stringify(r.out.split('\n').filter((l) => /^(KEPT|RC)=/.test(l)))}`)
    console.log(`  dropped -> ${JSON.stringify(r.out.split('\n').filter((l) => /^DROPPED:/.test(l)))}`)
    assert.match(r.out, /RC=0/)
    assert.match(r.out, /KEPT=REQUIRE_TRUSTED_PROXY_CONFIG TRUSTED_PROXY_IPS XERO_ALLOWED_TENANT_IDS\n/)
    assert.match(r.out, /^TRUSTED_PROXY_IPS=10\.0\.0\.1,10\.0\.0\.2$/m)
    assert.match(r.out, /^XERO_ALLOWED_TENANT_IDS=123e4567-e89b-12d3-a456-426614174000,123e4567-e89b-12d3-a456-426614174001$/m)
    const block = /BLOCK<<([\s\S]*?)>>/.exec(r.out)?.[1] ?? ''
    assert.doesNotMatch(block, /^APP_PORT=/m, 'a key the template sets is not written twice')
    // THE ALLOWLIST IS THE ONLY PATH: an unknown key with an innocuous value is dropped, and says so.
    assert.doesNotMatch(block, /MY_FEATURE_FLAG/, 'an unknown key with a harmless value is NOT carried')
    assert.match(r.out, /DROPPED:MY_FEATURE_FLAG \(line \d+\): not on the list of settings a re-run carries over/)
  })
})

test('re-run: a deploy admin credential left in the application .env is REFUSED, never carried forward', async () => {
  await withTempDir('ims-env-admin-', async (dir) => {
    const old = join(dir, '.env')
    writeFileSync(old, `${OLD_ENV}DEPLOY_ADMIN_DATABASE_URL=postgres://admin:SECRETPW@h/db\n`)
    const r = bash([LIB, `load_existing_env '${old}'`, `rendered='${RENDERED}'`,
      'render_preserved_env_keys "${rendered}"; echo "RC=$?"', 'printf "BLOCK=[%s]" "${ENV_PRESERVED_BLOCK}"'].join('\n'))
    console.log(`  admin key present -> ${JSON.stringify(r.out.split('\n').filter((l) => /RC=|ERROR/.test(l)).map((l) => l.slice(0, 90)))}`)
    assert.match(r.out, /RC=1/)
    assert.match(r.out, /ERROR: .*DEPLOY_ADMIN_DATABASE_URL.*must never hold the deploy admin credential/)
    assert.doesNotMatch(r.out, /SECRETPW/, 'and the value is never printed')
    assert.match(r.out, /BLOCK=\[\]/, 'no block was produced')
  })
})

const adminDir = (dir: string): string => {
  const d = join(dir, 'admin-private')
  mkdirSync(d, { mode: 0o700 })
  chmodSync(d, 0o700)
  return d
}

test('re-run: the backup of the old file is root-only, outside the application tree, written from what was read, before anything is replaced', async () => {
  await withTempDir('ims-env-bak-', async (dir) => {
    const old = join(dir, '.env.src')
    writeFileSync(old, OLD_ENV)
    const credDir = adminDir(dir)
    const target = join(dir, 'captured')
    const r = bash([LIB, 'date() { echo 20261008T120000Z; }',
      // publish_durable_file replaced by a recorder: arguments + stdin.
      `publish_durable_file() { echo "PUBLISH $1 $2 $3" > '${target}.args'; cat > '${target}.body'; }`,
      `load_existing_env '${old}'`, `APP_DIR='/opt/app-not-used'`, `DB_ADMIN_CREDENTIAL_DIR='${credDir}'`, 'write_env_backup; echo "RC=$?"', 'echo "FILE=${ENV_BACKUP_FILE}"'].join('\n'))
    const args = readFileSync(`${target}.args`, 'utf8').trim()
    console.log(`  backup: ${args.replace(dir, '<tmp>')}`)
    assert.match(r.out, /RC=0/)
    assert.match(args, new RegExp(`^PUBLISH ${credDir.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}/previous-app-env-20261008T120000Z-\\d+-0 \\S+:\\S+ 600$`))
    assert.doesNotMatch(args, /opt\/app-not-used/, 'and it is not under the application directory')
    assert.equal(readFileSync(`${target}.body`, 'utf8'), OLD_ENV, 'the backup is the old file byte for byte (every dropped key is in it)')
    // The directory is judged: wrong mode refused, nothing published.
    chmodSync(credDir, 0o755)
    const loose = bash([LIB, 'publish_durable_file() { echo CALLED; }', `load_existing_env '${old}'`, `DB_ADMIN_CREDENTIAL_DIR='${credDir}'`, 'write_env_backup; echo "RC=$?"'].join('\n'))
    console.log(`  directory mode 0755: ${JSON.stringify(loose.out.trim().split('\n').map((l) => l.slice(0, 100)))}`)
    assert.match(loose.out, /RC=1/)
    assert.match(loose.out, /must be owned by root with mode 0700/)
    assert.doesNotMatch(loose.out, /CALLED/)
    chmodSync(credDir, 0o700)
    // First install: nothing to back up, nothing published.
    const first = bash([LIB, 'publish_durable_file() { echo CALLED; }', 'write_env_backup; echo "RC=$? FILE=[${ENV_BACKUP_FILE}]"'].join('\n'))
    assert.match(first.out, /RC=0 FILE=\[\]/)
    assert.doesNotMatch(first.out, /CALLED/)
  })
})

test('re-run: two backups in the same second get different names, and a planted name is skipped, never replaced', async () => {
  await withTempDir('ims-env-bak2-', async (dir) => {
    const old = join(dir, '.env.src')
    writeFileSync(old, OLD_ENV)
    const credDir = adminDir(dir)
    const program = (extra: string) => [LIB, 'date() { echo 20261008T120000Z; }',
      // The recorder publishes for real into the reserved name, as publish_durable_file renames over it.
      'publish_durable_file() { cat > "$1"; }',
      `load_existing_env '${old}'`, `DB_ADMIN_CREDENTIAL_DIR='${credDir}'`, extra,
      'write_env_backup; echo "FIRST=${ENV_BACKUP_FILE##*/}"', 'write_env_backup; echo "SECOND=${ENV_BACKUP_FILE##*/}"'].join('\n')
    const r = bash(program(''))
    const first = /FIRST=(\S+)/.exec(r.out)?.[1]
    const second = /SECOND=(\S+)/.exec(r.out)?.[1]
    console.log(`  same-second names: ${first} / ${second}`)
    assert.ok(first && second && first !== second, 'precondition: two names were handed out')
    assert.equal(readFileSync(join(credDir, first), 'utf8'), OLD_ENV, 'and the first backup is still there, intact')
    assert.equal(readFileSync(join(credDir, second), 'utf8'), OLD_ENV)
    // A name already taken (here a symlink planted at the first candidate) is skipped, not followed.
    const victim = join(dir, 'victim')
    writeFileSync(victim, 'DO NOT TOUCH\n')
    const planted = bash(program(`ln -s '${victim}' "${credDir}/previous-app-env-20261008T120000Z-$$-0"`))
    const pf = /FIRST=(\S+)/.exec(planted.out)?.[1]
    console.log(`  with a planted symlink at -0: ${pf}; victim intact: ${readFileSync(victim, 'utf8') === 'DO NOT TOUCH\n'}`)
    assert.match(pf ?? '', /-1$/, 'the planted name was skipped')
    assert.equal(readFileSync(victim, 'utf8'), 'DO NOT TOUCH\n', 'and what it pointed at was not written through')
  })
})

test('re-run: the summary names what was kept, changed and added, and never prints a value', async () => {
  await withTempDir('ims-env-sum-', async (dir) => {
    const old = join(dir, '.env')
    writeFileSync(old, OLD_ENV)
    const now = RENDERED.replace('APP_PORT=3000', 'APP_PORT=3001')
    const r = bash([LIB, `load_existing_env '${old}'`, 'ENV_BACKUP_FILE=/opt/app/.env.bak-x', `rendered='${now}'`,
      'render_preserved_env_keys "${rendered}" > /dev/null', 'print_env_rewrite_summary "${rendered}"'].join('\n'))
    console.log(`  summary: ${JSON.stringify(r.out.split('\n').map((l) => l.slice(0, 110)))}`)
    assert.match(r.out, /Backup \(root-only, mode 600\): \/opt\/app\/\.env\.bak-x/)
    assert.match(r.out, /kept as it was.*TRUSTED_PROXY_IPS/)
    assert.match(r.out, /values this run changed \(1\): APP_PORT/)
    assert.match(r.out, /keys this run added \(1\): NEW_KEY/)
    for (const secret of ['whsec_old', 'cs_old', 'ck_old', 'old-auth', '10.0.0.1']) assert.doesNotMatch(r.out, new RegExp(secret), `${secret} must not be printed`)
  })
})

test('re-run: export/spaced forms and multi-line quoted values are read whole; anything else is unclassified', async () => {
  await withTempDir('ims-env-ml-', async (dir) => {
    const old = join(dir, '.env')
    writeFileSync(old, [
      'A=1',
      'export B=2',
      'C = 3',
      'KEY="BEGIN-OF-VALUE',
      'line two with = and #',
      'END-OF-VALUE"',
      "SQ='one",
      "two'",
      'D="a \\"quoted\\" word"',
      'not a key value line',
      'E="never closed',
      'F=6',
      '',
    ].join('\n'))
    const r = bash([LIB, `load_existing_env '${old}'`,
      'echo "UNCLASSIFIED=${EXISTING_ENV_UNCLASSIFIED[*]}"',
      'for k in A B C KEY SQ D F; do printf "%s|%s|line %s\\n" "$k" "${EXISTING_ENV[$k]-<unset>}" "${EXISTING_ENV_LINENO[$k]-?}"; done'].join('\n'))
    console.log(`  loader: ${JSON.stringify(r.out.split('\n').slice(0, 14))}`)
    assert.match(r.out, /UNCLASSIFIED=10 11\b/, 'the prose line (10) and the quoted value that never closes (11) are the only unclassified lines')
    assert.match(r.out, /^B\|2\|line 2$/m, '`export KEY=v` is read as KEY=v')
    assert.match(r.out, /^C\| 3\|line 3$/m, '`KEY = v` is read as KEY with that value')
    assert.match(r.out, /^KEY\|"BEGIN-OF-VALUE$/m, 'a multi-line quoted value starts at its first line...')
    assert.match(r.out, /^END-OF-VALUE"\|line 4$/m, '...and ends with its closing line (one value; the middle lines are not keys of their own)')
    assert.match(r.out, /^D\|"a \\"quoted\\" word"\|line 9$/m, 'an escaped quote does not close a double-quoted value')
    assert.match(r.out, /^F\|6\|line 12$/m, 'and reading resumes after an unclosed value')
    // The caller refuses the rewrite before anything has changed.
    const lines = INSTALL.split('\n')
    const start = lines.findIndex((l) => l === 'if ((${#EXISTING_ENV_UNCLASSIFIED[@]} > 0)); then')
    const end = lines.findIndex((l, i) => i > start && l === 'fi')
    assert.ok(start > 0 && end > start, 'precondition: the refusal block exists')
    const gate = lines.slice(start, end + 1).join('\n')
    const refused = bash([LIB, 'APP_DIR=/opt/app', `load_existing_env '${old}'`, gate, 'echo "CONTINUED"'].join('\n'))
    console.log(`  caller: ${JSON.stringify(refused.out.split('\n').filter((l) => /DIE|CONTINUED/.test(l)).map((l) => l.slice(0, 150)))}`)
    assert.equal(refused.status, 9)
    assert.match(refused.out, /DIE: .*2 line\(s\).*\(line numbers: 10 11\).*Nothing has been changed\./)
    assert.doesNotMatch(refused.out, /CONTINUED/)
    const clean = join(dir, 'clean.env')
    writeFileSync(clean, 'A=1\nexport B=2\nQ="x\ny"\n')
    const ok = bash([LIB, 'APP_DIR=/opt/app', `load_existing_env '${clean}'`, gate, 'echo "CONTINUED"'].join('\n'))
    assert.match(ok.out, /CONTINUED/, 'a file it can reproduce goes through')
  })
})

test('re-run: a multi-line value under an unlisted key is dropped from the new file and kept whole in the backup', async () => {
  await withTempDir('ims-env-mlc-', async (dir) => {
    const old = join(dir, '.env')
    writeFileSync(old, 'APP_PORT=3000\nCERT_PEM="first\nsecond=\nthird"\nTAIL=1\nOUTBOX_RETRY_BASE_MS="1\n2"\n')
    const r = bash([LIB, `load_existing_env '${old}'`, "rendered='APP_PORT=3000'", 'render_preserved_env_keys "${rendered}"; printf "BLOCK<<%s>>" "${ENV_PRESERVED_BLOCK}"; printf "DROPPED:%s\\n" "${ENV_REFUSED_KEYS[@]}"; printf "RAW<<%s>>" "$(printf "%s\\n" "${EXISTING_ENV_RAW[@]}")"'].join('\n'))
    console.log(`  multi-line: ${JSON.stringify(r.out.split('\n').filter((l) => /^DROPPED:/.test(l)))}`)
    const block = /BLOCK<<([\s\S]*?)>>/.exec(r.out)?.[1] ?? ''
    assert.doesNotMatch(block, /CERT_PEM/, 'the unlisted multi-line value is not carried')
    assert.doesNotMatch(block, /OUTBOX_RETRY_BASE_MS/, 'and a listed key whose value spans lines does not have the shape of a number')
    assert.match(r.out, /DROPPED:CERT_PEM .*not on the list/)
    assert.match(r.out, /DROPPED:OUTBOX_RETRY_BASE_MS .*does not have the shape of a int setting/)
    assert.match(r.out, /RAW<<[\s\S]*CERT_PEM="first\nsecond=\nthird"/, 'the backup lines still hold the whole value')
  })
})

const CARRY_ADMIN = 'postgresql://deployadmin:Adm1nPassw0rd@127.0.0.1:5432/db'

test('re-run: nothing outside the carry list reaches the new file, whatever it is called or encoded as; the reason is listed, the value never printed', async () => {
  await withTempDir('ims-env-carry-', async (dir) => {
    const old = join(dir, '.env')
    const b64 = Buffer.from(CARRY_ADMIN).toString('base64')
    const hex = Buffer.from(CARRY_ADMIN).toString('hex')
    const layered = [...Array(6)].reduce((acc: string) => encodeURIComponent(acc), 'x/Adm1nPassw0rd') // six layers
    writeFileSync(old, [
      'APP_PORT=3000',
      `DIRECT_URL=${CARRY_ADMIN}`,
      `MIGRATION_DATABASE_URL=${CARRY_ADMIN}`,
      'PGPASSWORD=Adm1nPassw0rd',
      `direct_url=${CARRY_ADMIN}`,
      `export SHADOW_DATABASE_URL=${CARRY_ADMIN}`,
      'REPORTING_CONN=postgres://reader:readerpw@db.example.test/reports',
      'PROXYISH=http://user:secretpw@proxy.example.test:3128',
      'INNOCUOUS_NOTE=copied from the admin file: Adm1nPassw0rd',
      `REPORTING_CONFIG=${b64}`,
      `REPORTING_HEX=${hex}`,
      `REPORTING_LAYERS=${layered}`,
      // ...and the same disguises under key names that ARE on the list: the shape rejects them.
      `OUTBOX_RETRY_BASE_MS=${b64}`,
      `OUTBOX_RETRY_JITTER_MS=${hex.slice(0, 3)}x`,
      `OUTBOX_RETRY_MAX_MS=${layered}`,
      'TRUSTED_PROXY_CIDRS=10.0.0.0/8,192.168.0.0/16',
      'REQUIRE_TRUSTED_PROXY_CONFIG=true',
      '',
    ].join('\n'))
    const r = bash([LIB, `DEPLOY_ADMIN_DATABASE_URL='${CARRY_ADMIN}'`, `load_existing_env '${old}'`, "rendered='APP_PORT=3000'",
      'render_preserved_env_keys "${rendered}"; echo "RC=$?"', 'printf "BLOCK<<%s>>\\n" "${ENV_PRESERVED_BLOCK}"',
      'ENV_BACKUP_FILE=/b; print_env_rewrite_summary "${rendered}"'].join('\n'))
    const block = /BLOCK<<([\s\S]*?)>>/.exec(r.out)?.[1] ?? ''
    console.log(`  carried block: ${JSON.stringify(block)}`)
    console.log(`  dropped: ${JSON.stringify(r.out.split('\n').filter((l) => /^WARN:     /.test(l)).map((l) => l.slice(10, 120)))}`)
    assert.match(r.out, /RC=0/)
    assert.deepEqual(block.split('\n').filter((l) => l && !l.startsWith('#')).sort(),
      ['REQUIRE_TRUSTED_PROXY_CONFIG=true', 'TRUSTED_PROXY_CIDRS=10.0.0.0/8,192.168.0.0/16'], 'ONLY the two well-formed listed keys are carried')
    for (const gone of ['DIRECT_URL', 'MIGRATION_DATABASE_URL', 'PGPASSWORD', 'direct_url', 'SHADOW_DATABASE_URL', 'REPORTING_CONN', 'PROXYISH', 'INNOCUOUS_NOTE', 'REPORTING_CONFIG', 'REPORTING_HEX', 'REPORTING_LAYERS']) {
      assert.match(r.out, new RegExp(`WARN:     ${gone} \\(line \\d+\\): not on the list of settings a re-run carries over`), `${gone} must be listed as dropped`)
    }
    for (const listed of ['OUTBOX_RETRY_BASE_MS', 'OUTBOX_RETRY_JITTER_MS', 'OUTBOX_RETRY_MAX_MS']) {
      assert.match(r.out, new RegExp(`WARN:     ${listed} \\(line \\d+\\): the value does not have the shape`), `${listed} with an encoded blob must fail its shape`)
    }
    for (const secret of ['Adm1nPassw0rd', 'readerpw', 'secretpw', b64, hex]) assert.doesNotMatch(r.out.replace(/BLOCK<<[\s\S]*?>>/, ''), new RegExp(secret.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')), 'no value is ever printed')
  })
})

test('re-run: the carry list is the ONLY path — property check over many innocuous unknown keys, and over the shapes', () => {
  const names = ['MY_FEATURE_FLAG', 'LOG_LEVEL', 'SENTRY_ENVIRONMENT', 'TZ', 'lowercase_key', 'trusted_proxy_ips', 'Trusted_Proxy_Ips', 'X', 'A_B_C_D', 'XERO_UNLISTED', 'WC_UNLISTED', 'REQUIRE_TRUSTED_PROXY_CONFIG_X']
  const body = names.map((n) => `EXISTING_ENV[${n}]=on`).join('; ')
  const r = bash([LIB, 'declare -A EXISTING_ENV_LINENO=()', body, 'render_preserved_env_keys "APP_PORT=3000"; printf "KEPT<<%s>>" "${ENV_KEPT_KEYS[*]-}"; printf "N=%s" "${#ENV_REFUSED_KEYS[@]}"'].join('\n'))
  console.log(`  ${names.length} innocuous unknown keys: ${r.out.trim().split('\n').pop()}`)
  assert.match(r.out, /KEPT<<>>/, 'not one innocuous unknown key is carried')
  assert.match(r.out, new RegExp(`N=${names.length}$`))
  // The shapes: accepted and rejected examples per shape, so a loosened class is red.
  const ok: Record<string, string[]> = {
    bool: ['true', 'false', '1', '0', 'yes', 'no', 'on', 'off', 'Yes', 'TRUE', ''], int: ['0', '5000', '1234567890123456'], number: ['1000', '1000.5'],
    rate_limit_backend: ['memory', 'redis', 'Redis', ''], csp_mode: ['enforce', 'report-only', 'off', 'Enforce', ''],
    iplist: ['10.0.0.1', '10.0.0.0/8,192.168.1.1', '10.0.0.1, 10.0.0.2', '::1,fe80::1/64', '[::1]:8080', '::ffff:10.0.0.1'],
    uuid: ['123e4567-e89b-12d3-a456-426614174000', '123E4567-E89B-12D3-A456-426614174000'],
    uuidlist: ['123e4567-e89b-12d3-a456-426614174000', '123e4567-e89b-12d3-a456-426614174000, 123e4567-e89b-12d3-a456-426614174001'],
    names: ["Acme Ltd,O'Neil & Sons", 'Demo Company (UK)'], origin: ['https://shop.example.test', 'https://shop.example.test/', 'http://localhost:3000', 'http://[::1]:3000'],
    iso_utc: ['2026-10-01T09:00Z', '2026-10-01T09:00:00Z', '2026-10-01T09:00:00.123Z'],
    mintsoft_grant: ['https://api.mintsoft.co.uk|89', 'https://x.test/base | 5', 'https://x.test|5|login=a.b@c'],
  }
  const bad: Record<string, string[]> = {
    bool: ['maybe', 'definitely-maybe', '2'], int: ['12a', '-1', '1e3', '12345678901234567'], number: ['1e3', '-1'],
    rate_limit_backend: ['memcached', 'redis;rm'], csp_mode: ['enforcee', 'report only'],
    iplist: ['10.0.0.1 10.0.0.2', 'a=b', 'a%2Fb', 'QWxhZGRpbjpvcGVu==', 'x'.repeat(65), '4142434445464748', 'proxy.example.test', 'QUJDREVGR0g'],
    uuid: ['tenant-a', '4142434445464748', 'QUJDREVGR0g', '123e4567-e89b-12d3-a456-42661417400'],
    uuidlist: ['tenant-a', 'a b', 'postgres://x', '4142434445464748', 'QUJDREVGR0g', '123e4567-e89b-12d3-a456-426614174000,tenant-b', '123e4567e89b12d3a456426614174000'],
    names: ['a%2Fb', 'a=b', 'a\\b'], origin: ['ftp://x', 'https://u:p@h', 'https://h/path', 'https://h?x=1'],
    iso_utc: ['yesterday', '2026-10-01 09:00', '2026-10-01', '2026-10-01T09:00:00+01:00'],
    mintsoft_grant: ['https://x.test', 'https://x.test|0', 'https://x.test|05', 'ftp://x|5', 'https://x.test|5|logon=a'],
  }
  let checks = 0
  for (const shape of Object.keys(ok)) {
    for (const v of ok[shape]) { assert.equal(bash([LIB, `env_value_has_shape '${shape}' '${v.replace(/'/g, "'\\''")}'; echo "RC=$?"`].join('\n')).out.trim().split('\n').pop(), 'RC=0', `${shape} accepts ${v}`); checks++ }
    for (const v of bad[shape]) { assert.equal(bash([LIB, `env_value_has_shape '${shape}' '${v}'; echo "RC=$?"`].join('\n')).out.trim().split('\n').pop(), 'RC=1', `${shape} rejects ${v}`); checks++ }
  }
  console.log(`  shape table: ${checks} accept/reject checks`)
  // Length cap and residual escapes.
  assert.equal(bash([LIB, `env_value_has_shape int "${'1'.repeat(5000)}"; echo "RC=$?"`].join('\n')).out.trim().split('\n').pop(), 'RC=1')
  const six = 'a%252525252525252F'
  const esc = (v: string) => bash([LIB, `env_value_has_residual_escape '${v}'; echo "RC=$?"`].join('\n')).out.trim().split('\n').pop()
  console.log(`  residual escape: 6-layer ${esc(six)}, plain ${esc('plain-value')}, one layer ${esc('a%2Fb')}`)
  assert.equal(esc(six), 'RC=0', 'a value encoded more deeply than the decode passes is refused, not passed')
  assert.equal(esc('plain-value'), 'RC=1')
  assert.equal(esc('a%2Fb'), 'RC=1', 'what the decode passes fully resolve is not "residual"')
})

test('re-run: the admin-material checks need the admin credential to be known, and ordinary keys pass without it', async () => {
  const check = (key: string, value: string, admin: string) => bash([LIB, admin ? `DEPLOY_ADMIN_DATABASE_URL='${admin}'` : 'DEPLOY_ADMIN_DATABASE_URL=""',
    `env_key_carry_check '${key}' '${value}'; echo "RC=$? REASON=[$ENV_REFUSAL_REASON]"`].join('\n')).out.trim().split('\n').pop()
  const rows: Array<[string, string, string, string]> = [
    ['TRUSTED_PROXY_IPS', '10.0.0.1', CARRY_ADMIN, 'RC=0 REASON=[]'],
    ['NOTE', 'has Adm1nPassw0rd inside', CARRY_ADMIN, "RC=1 REASON=[the value contains the deploy admin's password]"],
    ['NOTE', 'has Adm1nPassw0rd inside', '', 'RC=0 REASON=[]'],
    ['NOTE', 'x@deployadmin:y', CARRY_ADMIN, 'RC=0 REASON=[]'],
    ['NOTE', 'ssh://deployadmin@host/x', CARRY_ADMIN, 'RC=1 REASON=[the value names the deploy admin role as a connection user]'],
    ['PGSSLMODE', 'require', '', 'RC=1 REASON=[the name looks like a database connection setting]'],
    ['SUPERUSER_FLAG', '1', '', 'RC=1 REASON=[the name looks like a database connection setting]'],
    ['FEATURE_X', 'on', '', 'RC=0 REASON=[]'],
  ]
  for (const [key, value, admin, want] of rows) {
    const got = check(key, value, admin)
    console.log(`  ${key}=${value.slice(0, 22)} admin=${admin ? 'known' : 'unknown'} -> ${got}`)
    assert.equal(got, want)
  }
})

/** A block of shipped lines from `first` through `last` inclusive. */
function shippedBlock(first: RegExp, last: RegExp): string {
  const lines = INSTALL.split('\n')
  const start = lines.findIndex((l) => first.test(l))
  const end = lines.findIndex((l, i) => i >= start && last.test(l))
  assert.ok(start > 0 && end >= start, `precondition: block ${first} .. ${last} found (${start}..${end})`)
  return lines.slice(start, end + 1).join('\n')
}

const WC_BLOCK = shippedBlock(/^prompt WC_STORE_URL /, /^unset _wc_name$/)

const wcProgram = (existing: string, exports: string): string =>
  ['set -uo pipefail', 'NON_INTERACTIVE=true', 'declare -A EXISTING_ENV=()', existing,
    shippedFunction(INSTALL, 'existing_env'), shippedFunction(INSTALL, 'prompt'), exports, WC_BLOCK,
    'echo "URL=[${WC_STORE_URL}] KEY=[${WC_CONSUMER_KEY}] SECRET=[${WC_CONSUMER_SECRET}] HOOK=[${WC_WEBHOOK_SECRET}]"'].join('\n')

const WC_EXISTING = 'EXISTING_ENV[WC_STORE_URL]=https://shop.example.test; EXISTING_ENV[WC_CONSUMER_KEY]=ck_old; EXISTING_ENV[WC_CONSUMER_SECRET]=cs_old; EXISTING_ENV[WC_WEBHOOK_SECRET]=whsec_old'

test('re-run: WooCommerce credentials and the webhook secret default to the installed ones; only "none" clears', () => {
  const kept = bash(wcProgram(WC_EXISTING, ''))
  const fresh = bash(wcProgram('', ''))
  const cleared = bash(wcProgram(WC_EXISTING, 'export WC_STORE_URL=none WC_CONSUMER_KEY=none WC_CONSUMER_SECRET=none WC_WEBHOOK_SECRET=none'))
  const blank = bash(wcProgram(WC_EXISTING, 'export WC_STORE_URL= WC_WEBHOOK_SECRET='))
  const override = bash(wcProgram(WC_EXISTING, 'export WC_WEBHOOK_SECRET=whsec_new'))
  console.log(`  WC re-run default -> ${kept.out.trim()}`)
  console.log(`  WC first install  -> ${fresh.out.trim().replace(/HOOK=\[[0-9a-f]+\]/, 'HOOK=[<random>]')}`)
  console.log(`  WC none -> ${cleared.out.trim()}; blank export -> ${blank.out.trim()}; override -> ${override.out.trim()}`)
  assert.match(kept.out, /URL=\[https:\/\/shop\.example\.test\] KEY=\[ck_old\] SECRET=\[cs_old\] HOOK=\[whsec_old\]/)
  assert.match(fresh.out, /URL=\[\] KEY=\[\] SECRET=\[\] HOOK=\[[0-9a-f]{32}\]/, 'a first install still mints a webhook secret')
  assert.match(cleared.out, /URL=\[\] KEY=\[\] SECRET=\[\] HOOK=\[\]/)
  assert.match(blank.out, /URL=\[https:\/\/shop\.example\.test\].*HOOK=\[whsec_old\]/, 'a blank is not a request to clear')
  assert.match(override.out, /HOOK=\[whsec_new\]/)
})

test('re-run: the domain, port and upload-scanner settings default to what is installed', () => {
  const dom = shippedBlock(/^EXISTING_APP_DOMAIN=/, /^prompt APP_PORT /)
  const ask = (existing: string) => bash(['set -uo pipefail', 'NON_INTERACTIVE=true', 'declare -A EXISTING_ENV=()', existing,
    shippedFunction(INSTALL, 'existing_env'), shippedFunction(INSTALL, 'prompt'), dom, 'echo "DOMAIN=[${APP_DOMAIN}] PORT=[${APP_PORT}]"'].join('\n'))
  const installed = ask('EXISTING_ENV[NEXT_PUBLIC_APP_URL]=https://ims.example.test; EXISTING_ENV[APP_PORT]=3055')
  const firstRun = ask('')
  console.log(`  domain/port: installed -> ${installed.out.trim()}; first install -> ${firstRun.out.trim()}`)
  assert.match(installed.out, /DOMAIN=\[ims\.example\.test\] PORT=\[3055\]/)
  assert.match(firstRun.out, /DOMAIN=\[ims\.localhost\] PORT=\[3000\]/)

  const scan = shippedBlock(/^FILE_SCAN_MODE="\$\(existing_env /, /^FILE_SCAN_TIMEOUT_MS="/)
  const scanAsk = (existing: string) => bash(['set -uo pipefail', 'declare -A EXISTING_ENV=()', existing, shippedFunction(INSTALL, 'existing_env'), scan,
    'echo "MODE=[${FILE_SCAN_MODE}] CMD=[${FILE_SCAN_COMMAND}] TIMEOUT=[${FILE_SCAN_TIMEOUT_MS}]"'].join('\n'))
  const tuned = scanAsk('EXISTING_ENV[FILE_SCAN_MODE]=clamav; EXISTING_ENV[FILE_SCAN_COMMAND]=/usr/bin/clamdscan; EXISTING_ENV[FILE_SCAN_TIMEOUT_MS]=90000')
  const factory = scanAsk('')
  console.log(`  scanner: tuned -> ${tuned.out.trim()}; first install -> ${factory.out.trim()}`)
  assert.match(tuned.out, /MODE=\[clamav\] CMD=\[\/usr\/bin\/clamdscan\] TIMEOUT=\[90000\]/)
  assert.match(factory.out, /MODE=\[disabled\] CMD=\[\] TIMEOUT=\[30000\]/)
})

test('re-run: the .env write backs up and keeps before it replaces; the backup is outside the tree', () => {
  const body = shippedFunction(INSTALL, 'write_app_env_file')
  const order = ['render_app_env_file', 'render_preserved_env_keys', 'write_env_backup', 'publish_durable_file'].map((n) => body.indexOf(n))
  console.log(`  write_app_env_file call order offsets: ${order.join(' < ')}`)
  assert.ok(order.every((o) => o > 0) && order.every((o, i) => i === 0 || o > order[i - 1]), 'render, preserve, back up, then publish')
  const backup = shippedFunction(INSTALL, 'write_env_backup')
  assert.match(backup, /candidate="\$\{DB_ADMIN_CREDENTIAL_DIR\}\/previous-app-env-/, 'the backup is made in the root-only directory')
  assert.doesNotMatch(backup, /APP_DIR/, 'and nowhere in the application tree')
  assert.match(backup, /publish_durable_file "\$\{ENV_BACKUP_FILE\}" "\$\{ENV_BACKUP_OWNER\}" 600/)
  assert.match(INSTALL, /^ENV_BACKUP_OWNER="root:root"$/m, 'owned by root')
  assert.ok(!/\.env\.bak-\$\{/.test(backup), 'the installer no longer WRITES an in-tree backup name')
  assert.match(INSTALL, /^print_env_rewrite_summary "\$\{ENV_LAST_RENDERED\}"$/m, 'and the summary is printed after the write')
})

test('re-run: an ENCODED admin password or a libpq keyword/value string cannot slip through under an innocuous key', () => {
  const ENC_ADMIN = 'postgresql://deployadmin:A%40B-Pass%2Fw0rd@127.0.0.1:5432/db'
  const check = (value: string, admin = ENC_ADMIN) =>
    bash([LIB, `DEPLOY_ADMIN_DATABASE_URL='${admin}'`, `env_key_carry_check 'REPORTING_DSN' '${value}'; echo "RC=$? REASON=[$ENV_REFUSAL_REASON]"`].join('\n')).out.trim().split('\n').pop() ?? ''
  const refused: Array<[string, string]> = [
    ['the exact review case: decoded password in a libpq string', 'host=db.example user=deployadmin password=A@B-Pass/w0rd dbname=app'],
    ['decoded password alone', 'x A@B-Pass/w0rd y'],
    ['encoded as written in the URL', 'x A%40B-Pass%2Fw0rd y'],
    ['encoded with lowercase hex', 'x A%40B-Pass%2fw0rd y'],
    ["single-quoted password setting", "host=db password='other secret' dbname=app"],
    ['double-quoted, spaced password setting', 'host=db password = "other" dbname=app'],
    ['user setting naming the admin role', 'host=db user=deployadmin dbname=app'],
    ['quoted user setting naming the admin role', "host=db user='deployadmin' dbname=app"],
    ['spaced, double-quoted user setting', 'host=db user = "deployadmin"'],
    ['postgres URL without a password naming the admin', 'ssh://deployadmin@host/x'],
  ]
  for (const [label, value] of refused) {
    const got = check(value)
    console.log(`  ${label}: ${got}`)
    assert.match(got, /^RC=1 REASON=\[.+\]$/, `${label} must be refused`)
  }
  // Isolating: with the admin credential UNKNOWN, a plain keyword string with no password and another role passes.
  const ok = bash([LIB, 'DEPLOY_ADMIN_DATABASE_URL=""', "env_key_carry_check 'REPORTING_DSN' 'host=db user=reader dbname=app'; echo \"RC=$? REASON=[$ENV_REFUSAL_REASON]\""].join('\n')).out.trim().split('\n').pop()
  console.log(`  innocuous keyword string, admin unknown: ${ok}`)
  assert.equal(ok, 'RC=0 REASON=[]')
  // The decoder and encoder agree on the review's password.
  const rt = bash([LIB, "env_percent_decode 'A%40B-Pass%2Fw0rd' d; env_percent_encode \"$d\" e; echo \"$d|$e\""].join('\n')).out.trim()
  console.log(`  decode/encode: ${rt}`)
  assert.equal(rt, 'A@B-Pass/w0rd|A%40B-Pass%2Fw0rd')
})

// ---------------------------------------------------------------------------
// review round 3: encoded variants, and the short-password policy
// ---------------------------------------------------------------------------

const leaks = (value: string, adminUrl: string): string =>
  bash([LIB, `DEPLOY_ADMIN_DATABASE_URL='${adminUrl}'`, `env_key_carry_check 'REPORTING_NOTE' '${value}'; echo "RC=$? REASON=[$ENV_REFUSAL_REASON]"`].join('\n')).out.trim().split('\n').pop() ?? ''

test('re-run: mixed-case hex, double-, triple-encoded and plus-for-space copies of the admin password are all refused', () => {
  const admin = 'postgresql://deployadmin:A%2FB%3ASecret@127.0.0.1:5432/db' // decoded: A/B:Secret
  const refused: Array<[string, string]> = [
    ['as written (upper-case hex)', 'x A%2FB%3ASecret y'],
    ['mixed-case hex (the review case)', 'x A%2fB%3ASecret y'],
    ['all lower-case hex', 'x A%2fb%3asecret y'.replace('b%3asecret', 'B%3aSecret')],
    ['double-encoded (the review case)', 'x A%252FB%253ASecret y'],
    ['double-encoded, mixed case', 'x A%252fB%253aSecret y'],
    ['triple-encoded', 'x A%25252FB%25253ASecret y'],
    ['decoded', 'x A/B:Secret y'],
    ['inside a longer setting', 'cache=redis;token=A%252FB%253ASecret;ttl=5'],
  ]
  for (const [label, value] of refused) {
    const got = leaks(value, admin)
    console.log(`  ${label}: ${got}`)
    assert.equal(got, "RC=1 REASON=[the value contains the deploy admin's password]", label)
  }
  // plus-for-space: a password with a space, written with '+' in a form-encoded copy.
  const spaced = 'postgresql://deployadmin:pass%20word-9@127.0.0.1:5432/db'
  for (const value of ['x pass+word-9 y', 'x pass%20word-9 y', 'x pass word-9 y', 'x pass%2520word-9 y']) {
    const got = leaks(value, spaced)
    console.log(`  space variant ${JSON.stringify(value)}: ${got}`)
    assert.match(got, /^RC=1 /, value)
  }
  // Isolating: an unrelated value is not refused, so the arms above are not vacuous.
  assert.equal(leaks('x something-else y', admin), 'RC=0 REASON=[]')
})

test('re-run: the password-length floor is 8 — 7 characters ends the run when there are settings to screen, 8 is screened', async () => {
  await withTempDir('ims-env-floor-', async (dir) => {
    const lines = INSTALL.split('\n')
    const start = lines.findIndex((l) => l === 'env_admin_password_decoded')
    const end = lines.findIndex((l, i) => i > start && l === 'fi')
    assert.ok(start > 0 && end > start, 'precondition: the gate block exists')
    // the block ends with TWO nested fi lines; take through the outer one
    const gate = lines.slice(start, end + 2).join('\n')
    const old = join(dir, '.env')
    writeFileSync(old, 'APP_PORT=3000\nAUTH_SECRET=a\nTRUSTED_PROXY_IPS=10.0.0.1\n')
    const bareOld = join(dir, 'bare.env')
    writeFileSync(bareOld, 'APP_PORT=3000\nAUTH_SECRET=a\n')
    const run = (file: string, adminUrl: string) => bash([LIB, `DEPLOY_ADMIN_DATABASE_URL='${adminUrl}'`, `load_existing_env '${file}'`, gate, 'echo CONTINUED'].join('\n'))
    const cases: Array<[string, string, string, boolean]> = [
      ['7 characters, settings to screen', old, 'postgresql://deployadmin:abcdefg@h/db', true],
      ['the exact review case: password x', old, 'postgresql://deployadmin:x@db/app', true],
      ['8 characters, settings to screen', old, 'postgresql://deployadmin:abcdefgh@h/db', false],
      ['7 characters but an encoded 8-char form decodes to 7', old, 'postgresql://deployadmin:abc%64efg@h/db', true],
      ['7 characters, NOTHING to screen', bareOld, 'postgresql://deployadmin:abcdefg@h/db', false],
      ['no password in the admin URL', old, 'postgresql://deployadmin@h/db', false],
    ]
    for (const [label, file, url, refusedRun] of cases) {
      const r = run(file, url)
      console.log(`  ${label}: ${refusedRun ? 'refused' : 'continues'} -> rc=${r.status}`)
      assert.equal(r.status, refusedRun ? 9 : 0, `${label}\n${r.out}`)
      if (refusedRun) {
        assert.ok(r.out.includes(TOO_SHORT_MESSAGE), 'the diagnostic is the single-sourced sentence')
        assert.match(r.out, /Nothing has been changed\./)
        assert.doesNotMatch(r.out, /CONTINUED/)
      } else assert.match(r.out, /CONTINUED/)
    }
    assert.equal(TOO_SHORT_MESSAGE, 'the deploy admin password is too short to screen preserved settings against; set a password of at least 8 characters or remove the extra settings and re-run.')
    assert.ok(read('docs/installation.md').includes(TOO_SHORT_MESSAGE), 'and the docs quote the same sentence')
  })
})

test('re-run: the template key list the early gate uses is exactly the keys render_app_env_file writes', () => {
  const body = shippedFunction(INSTALL, 'render_app_env_file')
  const written = [...new Set(body.split('\n').map((l) => /^([A-Za-z_][A-Za-z0-9_]*)=/.exec(l)?.[1]).filter((k): k is string => Boolean(k)))].sort()
  const listed = (/^ENV_TEMPLATE_KEYS=\((.*)\)$/m.exec(INSTALL)?.[1] ?? '').split(/\s+/).filter(Boolean).sort()
  console.log(`  template keys written: ${written.length}; listed: ${listed.length}`)
  assert.ok(written.length >= 25, 'precondition: the template was parsed')
  assert.deepEqual(listed, written)
})

// ---------------------------------------------------------------------------
// review round 5: the loader's QUOTES, security settings, and the in-tree backups of earlier versions
// ---------------------------------------------------------------------------

const GATE_START = 'for _sec_key in "${ENV_PRESERVE_SECURITY_KEYS[@]}"; do'
const securityGate = (): string => {
  const lines = INSTALL.split('\n')
  const start = lines.findIndex((l) => l === GATE_START)
  const end = lines.findIndex((l, i) => i > start && l === 'unset _sec_key')
  assert.ok(start > 0 && end > start, 'precondition: the security-setting gate exists')
  return lines.slice(start, end + 1).join('\n')
}

test('re-run: a security setting written with quotes, export, CRLF or an inline comment is carried with the same effective meaning, in one canonical form', async () => {
  await withTempDir('ims-env-eff-', async (dir) => {
    const variants: Array<[string, (k: string, v: string) => string]> = [
      ['bare', (k, v) => `${k}=${v}`],
      ['double-quoted', (k, v) => `${k}="${v}"`],
      ['single-quoted', (k, v) => `${k}='${v}'`],
      ['export-prefixed', (k, v) => `export ${k}=${v}`],
      ['export + double-quoted', (k, v) => `export ${k}="${v}"`],
      ['spaces around the value', (k, v) => `${k}=  ${v}   `],
      ['inline comment', (k, v) => `${k}=${v} # why`],
      ['double-quoted + inline comment', (k, v) => `${k}="${v}" # why`],
      ['single-quoted + inline comment', (k, v) => `${k}='${v}'   # why`],
      ['CRLF line ending', (k, v) => `${k}=${v}\r`],
      ['CRLF + double-quoted', (k, v) => `${k}="${v}"\r`],
    ]
    const wants: Array<[string, string]> = [['REQUIRE_TRUSTED_PROXY_CONFIG', 'true'], ['TRUSTED_PROXY_IPS', '10.0.0.1,10.0.0.2'], ['XERO_ALLOWED_TENANT_IDS', '123e4567-e89b-12d3-a456-426614174000,123e4567-e89b-12d3-a456-426614174001']]
    let checked = 0
    for (const [label, form] of variants) {
      const old = join(dir, `${checked}.env`)
      writeFileSync(old, ['APP_PORT=3000', ...wants.map(([k, v]) => form(k, v)), ''].join(label.includes('CRLF') ? '\r\n'.replace('\r', '') : '\n'))
      const r = bash([LIB, `load_existing_env '${old}'`, "rendered='APP_PORT=3000'", 'render_preserved_env_keys "${rendered}"; echo "RC=$?"', 'printf "BLOCK<<%s>>" "${ENV_PRESERVED_BLOCK}"', 'printf "DROPPED=%s" "${#ENV_REFUSED_KEYS[@]}"'].join('\n'))
      const block = /BLOCK<<([\s\S]*?)>>/.exec(r.out)?.[1] ?? ''
      console.log(`  ${label}: ${JSON.stringify(block.split('\n').filter((l) => l && !l.startsWith('#')))} dropped=${/DROPPED=(\d+)/.exec(r.out)?.[1]}`)
      assert.match(r.out, /RC=0/, label)
      assert.deepEqual(block.split('\n').filter((l) => l && !l.startsWith('#')).sort(), wants.map(([k, v]) => `${k}=${v}`).sort(), `${label}: carried unquoted with the same effective value`)
      assert.match(r.out, /DROPPED=0/, label)
      checked++
    }
    assert.equal(checked, variants.length)
    // The canonical form is lossless for a value that needs quoting, and the loader would read it back the same.
    const canon = bash([LIB, "env_canonical_value \"Acme Ltd,O'Neil & Sons\" c; echo \"$c\"; env_effective_value \"$c\" e; echo \"$e\"", "env_canonical_value 10.0.0.1,10.0.0.2 d; echo \"$d\""].join('\n')).out.trim().split('\n')
    console.log(`  canonical forms: ${JSON.stringify(canon)}`)
    assert.deepEqual(canon, ['"Acme Ltd,O\'Neil & Sons"', "Acme Ltd,O'Neil & Sons", '10.0.0.1,10.0.0.2'])
  })
})

test('re-run: a security setting that cannot be carried REFUSES the run before anything is changed, naming the key and never the value; a non-security one is dropped and reported', async () => {
  await withTempDir('ims-env-sec-', async (dir) => {
    const gate = securityGate()
    const run = (content: string, admin = '') => {
      const old = join(dir, `s${Math.random().toString(36).slice(2)}.env`)
      writeFileSync(old, content)
      return bash([LIB, 'APP_DIR=/opt/app', admin ? `DEPLOY_ADMIN_DATABASE_URL='${admin}'` : 'DEPLOY_ADMIN_DATABASE_URL=""', `load_existing_env '${old}'`, gate, 'echo CONTINUED', "rendered='APP_PORT=3000'", 'render_preserved_env_keys "${rendered}"; echo "RC=$?"; printf "DROPPED:%s\\n" "${ENV_REFUSED_KEYS[@]}"'].join('\n'))
    }
    const cases: Array<[string, string, boolean]> = [
      ['REQUIRE_TRUSTED_PROXY_CONFIG not a boolean', 'REQUIRE_TRUSTED_PROXY_CONFIG=definitely-maybe\n', true],
      ['TRUSTED_PROXY_IPS holds an encoded blob', `TRUSTED_PROXY_IPS=${Buffer.from('postgresql://a:b@h/d').toString('base64')}\n`, true],
      ['XERO tenant allowlist with a space-separated list', 'XERO_ALLOWED_TENANT_IDS=a b\n', true],
      ['a write grant that is not a timestamp', 'MINTSOFT_WRITES_LIVE_FROM=whenever\n', true],
      ['a producer-hold list with a misspelt destination', 'PRODUCER_HOLD_ENFORCED_DESTINATIONS=xerro\n', true],
      ['a well-formed producer-hold list', 'PRODUCER_HOLD_ENFORCED_DESTINATIONS=xero, woocommerce\n', false],
      ['TRUSTED_PROXY_IPS carries the admin password', `TRUSTED_PROXY_IPS=10.0.0.1,Adm1nPassw0rd\n`, true],
      ['a well-formed quoted security setting', 'REQUIRE_TRUSTED_PROXY_CONFIG="true"\nTRUSTED_PROXY_IPS=\'10.0.0.1\'\n', false],
      ['a NON-security setting that does not fit', 'OUTBOX_RETRY_BASE_MS=abc\n', false],
      ['an unlisted key', 'MY_FEATURE_FLAG=on\n', false],
    ]
    for (const [label, content, refused] of cases) {
      const r = run(`APP_PORT=3000\n${content}`, 'postgresql://deployadmin:Adm1nPassw0rd@h/db')
      console.log(`  ${label}: ${refused ? 'refused' : 'continues'} rc=${r.status}`)
      if (refused) {
        assert.equal(r.status, 9, label)
        assert.match(r.out, /DIE: .*\/\.env: [A-Z_]+ is a security setting that this installer cannot carry across/)
        assert.match(r.out, /Nothing has been changed\./)
        assert.doesNotMatch(r.out, /CONTINUED/)
        assert.doesNotMatch(r.out, /Adm1nPassw0rd|definitely-maybe|a b|whenever/, 'the value is never printed')
      } else {
        assert.equal(r.status, 0, `${label}\n${r.out}`)
        assert.match(r.out, /CONTINUED/)
      }
    }
    // Non-security keys that do not fit are dropped AND reported.
    const dropped = run('APP_PORT=3000\nOUTBOX_RETRY_BASE_MS=abc\nMY_FEATURE_FLAG=on\n')
    assert.match(dropped.out, /DROPPED:OUTBOX_RETRY_BASE_MS .*does not have the shape of a int setting/)
    assert.match(dropped.out, /DROPPED:MY_FEATURE_FLAG .*not on the list/)
  })
})

test('re-run: every security setting is on the carry list, and the sentence that refuses is single-sourced', () => {
  const security = (/^ENV_PRESERVE_SECURITY_KEYS=\(([\s\S]*?)^\)$/m.exec(INSTALL)?.[1] ?? '').split(/\s+/).filter(Boolean)
  const shapes = [...(/^declare -A ENV_PRESERVE_SHAPES=\(([\s\S]*?)^\)$/m.exec(INSTALL)?.[1] ?? '').matchAll(/\[([A-Z0-9_]+)\]=/g)].map((m) => m[1])
  console.log(`  ${security.length} security settings, all among the ${shapes.length} listed`)
  assert.ok(security.length >= 15 && shapes.length >= 30, 'precondition: both lists were parsed')
  assert.deepEqual(security.filter((k) => !shapes.includes(k)), [])
  for (const must of ['REQUIRE_TRUSTED_PROXY_CONFIG', 'TRUSTED_PROXY_IPS', 'XERO_ALLOWED_TENANT_IDS', 'XERO_WRITE_ALLOWED_TENANT', 'MINTSOFT_WRITE_ALLOWED', 'WC_WRITES_LIVE_FROM', 'ALLOW_DATABASE_RESTORE']) assert.ok(security.includes(must), must)
  const message = /^ENV_SECURITY_KEY_UNCARRIABLE_MESSAGE="(.*)"$/m.exec(INSTALL)?.[1] ?? ''
  assert.ok(message.length > 40 && read('docs/installation.md').includes('security setting'), 'the docs name the refusal')
})

test('re-run: the source sync spares in-tree .env.bak* files left by earlier installer versions (both rsync paths)', async () => {
  const lines = INSTALL.split('\n')
  const statements: string[] = []
  lines.forEach((l, i) => {
    if (!/^\s*rsync -a --delete \\$/.test(l)) return
    let end = i
    while (lines[end].endsWith('\\')) end++
    statements.push(lines.slice(i, end + 1).join('\n'))
  })
  console.log(`  rsync --delete statements: ${statements.length}`)
  assert.equal(statements.length, 2, 'precondition: the two source-sync paths were found')
  const synced = statements.filter((st) => /\.env'/.test(st))
  assert.equal(synced.length, 2)
  for (const st of statements) assert.match(st, /--exclude='\.env\.bak\*'/, 'each sync excludes the in-tree backups')
  // The statements are RUN: with the real rsync when the machine has one (the --delete is then observed to spare the
  // files), and always with a recording stand-in that proves what rsync would have been asked to spare.
  const haveRsync = bash('command -v rsync').status === 0
  console.log(`  real rsync available: ${haveRsync}`)
  await withTempDir('ims-env-rsync-', async (dir) => {
    const src = join(dir, 'src')
    const app = join(dir, 'app')
    mkdirSync(src); mkdirSync(app)
    writeFileSync(join(src, 'package.json'), '{}')
    writeFileSync(join(app, '.env.bak.20250101'), 'OLD BACKUP')
    writeFileSync(join(app, '.env.bak-20250102T000000Z'), 'OLD BACKUP 2')
    writeFileSync(join(app, '.env'), 'KEEP')
    for (const [i, statement] of statements.entries()) {
      const st = statement.replace(/"\$\{[A-Z_]+%\/\}\/"/, `"${src}/"`).replace(/"\$\{APP_DIR\}\/"/, `"${app}/"`)
      const recorded = bash(`rsync() { printf 'ARG %s\\n' "$@"; }\n${st}`)
      const args = recorded.out.split('\n').filter((l) => l.startsWith('ARG ')).map((l) => l.slice(4))
      console.log(`  sync path ${i + 1} asks rsync to spare: ${JSON.stringify(args.filter((a) => a.startsWith('--exclude')))}`)
      assert.ok(args.includes('--delete') && args.includes('--exclude=.env.bak*') && args.includes('--exclude=.env'), 'the sync deletes, and spares .env and .env.bak*')
      if (haveRsync) {
        writeFileSync(join(app, 'stale.txt'), 'delete me')
        const r = bash(st)
        assert.equal(r.status, 0, r.out)
        assert.ok(!readdirSync(app).includes('stale.txt'), 'precondition: --delete really ran')
        assert.equal(readFileSync(join(app, '.env.bak.20250101'), 'utf8'), 'OLD BACKUP')
        assert.equal(readFileSync(join(app, '.env.bak-20250102T000000Z'), 'utf8'), 'OLD BACKUP 2')
        assert.equal(readFileSync(join(app, '.env'), 'utf8'), 'KEEP')
      }
    }
  })
})

// ---------------------------------------------------------------------------
// review round 6: real formats per setting, and the reversible-encoding screen
// ---------------------------------------------------------------------------

test('re-run: a reversible encoding of the admin password cannot ride in ANY carried setting (the exact review examples)', () => {
  const admin = 'postgresql://deployadmin:ABCDEFGH@127.0.0.1:5432/db'
  const hex = Buffer.from('ABCDEFGH').toString('hex')          // 4142434445464748
  const b64url = Buffer.from('ABCDEFGH').toString('base64url') // QUJDREVGR0g
  const b64 = Buffer.from('ABCDEFGH').toString('base64')       // QUJDREVGR0g=
  console.log(`  examples: hex=${hex} base64url=${b64url} base64=${b64}`)
  const decide = (key: string, value: string) =>
    bash([LIB, `DEPLOY_ADMIN_DATABASE_URL='${admin}'`, `env_preserve_decision '${key}' '${value}'; echo "RC=$? REASON=[$ENV_REFUSAL_REASON]"`].join('\n')).out.trim().split('\n').pop() ?? ''
  // The class: under keys whose shape admits digits or letters, the token is refused by the screen itself.
  for (const [key, value] of [['OUTBOX_RETRY_BASE_MS', hex], ['XERO_DAILY_BATCH_LIMIT', hex], ['XERO_ALLOWED_TENANT_NAMES', b64url], ['XERO_ALLOWED_TENANT_NAMES', hex]] as const) {
    const got = decide(key, value)
    console.log(`  ${key}=${value}: ${got}`)
    assert.match(got, /^RC=1 REASON=\[the value contains the deploy admin's password\]$/, `${key}`)
  }
  // A padded base64 is outside the names alphabet altogether.
  assert.match(decide('XERO_ALLOWED_TENANT_NAMES', b64), /^RC=1 /)
  // And the UUID-only tenant lists refuse them on shape alone.
  for (const value of [hex, b64url, b64]) {
    const got = decide('XERO_ALLOWED_TENANT_IDS', value)
    console.log(`  XERO_ALLOWED_TENANT_IDS=${value}: ${got}`)
    assert.match(got, /^RC=1 REASON=\[the value does not have the shape of a uuidlist setting\]$/)
  }
  // The same two values as a run: the security setting refuses the whole re-run.
  const lines = INSTALL.split('\n')
  const start = lines.findIndex((l) => l === 'for _sec_key in "${ENV_PRESERVE_SECURITY_KEYS[@]}"; do')
  const end = lines.findIndex((l, i) => i > start && l === 'unset _sec_key')
  const gate = lines.slice(start, end + 1).join('\n')
  for (const value of [hex, b64url]) {
    const r = bash([LIB, 'APP_DIR=/opt/app', `DEPLOY_ADMIN_DATABASE_URL='${admin}'`, 'EXISTING_ENV[XERO_ALLOWED_TENANT_IDS]=' + value, gate, 'echo CONTINUED'].join('\n'))
    assert.equal(r.status, 9, value)
    assert.doesNotMatch(r.out, new RegExp(value), 'and the value is not printed')
  }
  // Isolating: a real UUID list under the same key is carried.
  const good = decide('XERO_ALLOWED_TENANT_IDS', '123e4567-e89b-12d3-a456-426614174000, 123e4567-e89b-12d3-a456-426614174001')
  assert.equal(good, 'RC=0 REASON=[]')
})

test('re-run: PREFLIGHT_DB_CONNECT=yes is kept (the application treats yes as true), and the setting is a security setting', async () => {
  await withTempDir('ims-env-pf-', async (dir) => {
    const old = join(dir, '.env')
    writeFileSync(old, 'APP_PORT=3000\nPREFLIGHT_DB_CONNECT=yes\nXERO_REQUIRE_DEMO_ORG=On\nBEHIND_PROXY="Yes" # proxied\n')
    const r = bash([LIB, `load_existing_env '${old}'`, "rendered='APP_PORT=3000'", 'render_preserved_env_keys "${rendered}"; echo "RC=$?"; printf "BLOCK<<%s>>" "${ENV_PRESERVED_BLOCK}"'].join('\n'))
    const block = /BLOCK<<([\s\S]*?)>>/.exec(r.out)?.[1] ?? ''
    console.log(`  carried: ${JSON.stringify(block.split('\n').filter((l) => l && !l.startsWith('#')))}`)
    assert.match(r.out, /RC=0/)
    assert.deepEqual(block.split('\n').filter((l) => l && !l.startsWith('#')).sort(), ['BEHIND_PROXY=Yes', 'PREFLIGHT_DB_CONNECT=yes', 'XERO_REQUIRE_DEMO_ORG=On'])
  })
  assert.ok((/^ENV_PRESERVE_SECURITY_KEYS=\(([\s\S]*?)^\)$/m.exec(INSTALL)?.[1] ?? '').split(/\s+/).includes('PREFLIGHT_DB_CONNECT'))
})

test('re-run: AUDIT — every value the application accepts for a listed setting passes its shape, and every setting whose absence loosens a guard is a security setting', () => {
  // Read from the code that parses each key (file in the comment). A row is [key, values the app accepts].
  const U = '123e4567-e89b-12d3-a456-426614174000'
  const accepted: Array<[string, string, string[]]> = [
    ['TRUSTED_PROXY_IPS', 'lib/request-ip.ts parseEnvList (split , / trim / isIP)', ['10.0.0.1', '10.0.0.1, 10.0.0.2', '::1', '[::1]:443']],
    ['TRUSTED_PROXY_CIDRS', 'lib/request-ip.ts parseTrustedProxyRange', ['10.0.0.0/8', '10.0.0.1', 'fe80::/10', '10.0.0.0/8, 192.168.0.0/16']],
    ['REQUIRE_TRUSTED_PROXY_CONFIG', 'lib/ops/production-preflight.ts isTruthy', ['1', 'true', 'yes', 'on', 'YES', ' ', '0', 'false']],
    ['BEHIND_PROXY', 'lib/ops/production-preflight.ts isTruthy', ['1', 'true', 'yes', 'on', 'On']],
    ['RATE_LIMIT_BACKEND', 'lib/security/rate-limit.ts (trim, lower; memory|redis|empty)', ['memory', 'redis', 'Redis', '']],
    ['CSP_MODE', 'lib/security/csp.ts getCspMode (enforce|off|else report-only)', ['enforce', 'off', 'report-only', 'ENFORCE']],
    ['ALLOW_DATABASE_RESTORE', 'app/api/backup/restore/route.ts isTruthy', ['true', 'false', 'yes', '1']],
    ['ALLOW_DATABASE_RESTORE_UPLOAD', 'app/api/backup/restore/route.ts isTruthy', ['true', 'false', 'yes', '1']],
    ['PREFLIGHT_DB_CONNECT', 'lib/ops/production-preflight.ts isTruthy', ['1', 'true', 'yes', 'on', 'Yes']],
    ['XERO_ALLOWED_TENANT_IDS', 'lib/connectors/xero/tenant-guard.ts splitEnvList (Xero tenant ids are UUIDs)', [U, `${U}, ${U.replace(/0$/, '1')}`]],
    ['XERO_BLOCKED_TENANT_IDS', 'lib/connectors/xero/tenant-guard.ts splitEnvList', [U]],
    ['XERO_ALLOWED_TENANT_NAMES', 'lib/connectors/xero/tenant-guard.ts splitEnvList (organisation names)', ['Demo Company (UK)', 'Acme Ltd, Beta & Co']],
    ['XERO_REQUIRE_DEMO_ORG', 'lib/connectors/xero/tenant-guard.ts readEnvSwitch', ['1', 'true', 'yes', 'on', '0', 'false', 'no', 'off']],
    ['XERO_TENANT_ID', 'lib/connectors/xero/tenant-guard.ts (deprecated single id)', [U]],
    ['XERO_WRITE_ALLOWED_TENANT', 'lib/security/outbound-write-grant.ts readXeroGrant (one tenant id, a UUID)', [U, U.toUpperCase()]],
    ['XERO_DAILY_BATCH_LIMIT', 'lib/connectors/xero/daily-sync.ts resolveXeroDailyBatchLimit (Number, > 0)', ['1000', '250.5']],
    ['PRODUCER_HOLD_ENFORCED_DESTINATIONS', 'lib/security/producer-seam.ts readProducerEnforcement (comma list of xero|mintsoft|woocommerce, or all; entries trimmed)', ['xero', 'xero, woocommerce', 'all', 'xero,mintsoft,woocommerce']],
    ['XERO_WRITES_LIVE_FROM', 'lib/security/producer-disposition.ts ISO_UTC_RE', ['2026-12-01T00:00Z', '2026-12-01T00:00:00Z', '2026-12-01T00:00:00.5Z']],
    ['WC_WRITES_LIVE_FROM', 'lib/security/producer-disposition.ts ISO_UTC_RE', ['2026-12-01T00:00:00Z']],
    ['MINTSOFT_WRITES_LIVE_FROM', 'lib/security/producer-disposition.ts ISO_UTC_RE', ['2026-12-01T00:00:00Z']],
    ['MINTSOFT_WRITE_ALLOWED', 'lib/security/outbound-write-grant.ts readMintsoftGrant', ['https://api.mintsoft.co.uk|89', 'https://api.mintsoft.co.uk/v1 | 89', 'https://api.mintsoft.co.uk|89|login=ops@example.test']],
    ['MINTSOFT_USE_BULK_ASN_LOOKUP', 'lib/jobs/wms/process-mintsoft-booked-in-event.ts', ['1', 'true', 'yes', 'on', 'TRUE']],
    ['MINTSOFT_WEBHOOK_SWEEPER_PAGE_SIZE', 'lib/jobs/wms/process-mintsoft-booked-in-event.ts parseInt > 0', ['100', '25']],
    ['WC_WRITEBACK_ALLOWED_ORIGIN', 'lib/security/outbound-write-grant.ts parseDestinationUrl (bare origin, https, http for loopback)', ['https://shop.example.test', 'https://shop.example.test/', 'http://localhost:3000', 'http://[::1]:3000']],
    ['OUTBOX_RETRY_BASE_MS', 'lib/domain/integrations/outbox.ts configuredPositiveMs', ['1000']],
    ['OUTBOX_RETRY_JITTER_MS', 'lib/domain/integrations/outbox.ts configuredNonNegativeMs', ['0', '250']],
    ['OUTBOX_RETRY_MAX_MS', 'lib/domain/integrations/outbox.ts configuredPositiveMs', ['600000']],
    ['CONNECTOR_FETCH_TIMEOUT_MS', 'lib/security/connector-fetch.ts', ['30000']],
    ['CONNECTOR_FETCH_MAX_RESPONSE_BYTES', 'lib/security/connector-fetch.ts', ['10485760']],
    ['FRESH_AUTH_MAX_AGE_SECONDS', 'lib/auth/session-state.ts', ['900', '86400']],
    ['INVOICE_PDF_TOKEN_TTL_SECONDS', 'lib/invoice-pdf.ts', ['600']],
    ['INVOICE_PDF_TOKEN_MAX_TTL_SECONDS', 'lib/invoice-pdf.ts', ['2592000']],
    ['DATABASE_RESTORE_MAX_FILE_BYTES', 'app/api/backup/restore/route.ts parsePositiveIntegerEnv', ['52428800']],
    ['SHOPPING_WEBHOOK_MAX_BODY_BYTES', 'app/api/webhooks/shopping/[connector]/[resource]/route.ts parsePositiveIntegerEnv (default 262144)', ['262144', '1048576']],
    ['SHOPPING_WEBHOOK_READ_TIMEOUT_MS', 'app/api/webhooks/shopping/[connector]/[resource]/route.ts parsePositiveIntegerEnv (default 30000)', ['30000', '5000']],
    ['WC_WEBHOOK_INBOX_MAX_ATTEMPTS', 'lib/connectors/shopping-webhook-inbox.ts parsePositiveIntegerEnv', ['5']],
    ['WC_WEBHOOK_INBOX_PROCESS_PAGE_SIZE', 'lib/connectors/shopping-webhook-inbox.ts parsePositiveIntegerEnv', ['50']],
    ['WC_WEBHOOK_INBOX_STALE_PROCESSING_MS', 'lib/connectors/shopping-webhook-inbox.ts parsePositiveIntegerEnv', ['300000']],
    ['WC_PENDING_FX_ORDER_NOTIFY_THRESHOLD', 'lib/connectors/woocommerce/sync/order-import.ts parsePositiveIntegerEnv', ['25']],
    ['XERO_ACCOUNTING_OUTBOX_ENABLED', 'lib/connectors/xero/sync-processor.ts isXeroAccountingOutboxEnabled (false|0|off disable)', ['false', '0', 'off', 'true', 'FALSE']],
  ]
  const shapes = new Map([...(/^declare -A ENV_PRESERVE_SHAPES=\(([\s\S]*?)^\)$/m.exec(INSTALL)?.[1] ?? '').matchAll(/\[([A-Z0-9_]+)\]=(\w+)/g)].map((m) => [m[1], m[2]]))
  const security = new Set((/^ENV_PRESERVE_SECURITY_KEYS=\(([\s\S]*?)^\)$/m.exec(INSTALL)?.[1] ?? '').split(/\s+/).filter(Boolean))
  console.log(`  audit: ${accepted.length} keys audited of ${shapes.size} listed`)
  assert.deepEqual([...shapes.keys()].filter((k) => !accepted.some(([key]) => key === k)).sort(), [], 'every listed key is in the audit table')
  let values = 0
  for (const [key, source, vals] of accepted) {
    const shape = shapes.get(key)
    assert.ok(shape, `${key} is on the carry list`)
    for (const v of vals) {
      const out = bash([LIB, `env_value_has_shape '${shape}' '${v.replace(/'/g, "'\\''")}'; echo "RC=$?"`].join('\n')).out.trim().split('\n').pop()
      // surrounding whitespace is trimmed by the loader before the shape runs, so audit the effective value
      const eff = bash([LIB, `env_effective_value '${v.replace(/'/g, "'\\''")}' e; env_value_has_shape '${shape}' "$e"; echo "RC=$?"`].join('\n')).out.trim().split('\n').pop()
      assert.ok(eff === 'RC=0' && (out === 'RC=0' || v !== v.trim()), `${key} (${source}) accepts ${JSON.stringify(v)}: shape ${shape}`)
      values++
    }
    console.log(`  ${key.padEnd(36)} ${shape.padEnd(18)} ${security.has(key) ? 'SECURITY' : '        '} <- ${source}`)
  }
  console.log(`  ${values} application-accepted values pass their shapes`)
  // A setting whose ABSENCE loosens a verification or a guard (a switch that turns a check on, an allowlist, a cap, a policy mode).
  const loosensWhenAbsent = ['REQUIRE_TRUSTED_PROXY_CONFIG', 'BEHIND_PROXY', 'PREFLIGHT_DB_CONNECT', 'TRUSTED_PROXY_IPS', 'TRUSTED_PROXY_CIDRS', 'RATE_LIMIT_BACKEND', 'CSP_MODE',
    'XERO_ALLOWED_TENANT_IDS', 'XERO_BLOCKED_TENANT_IDS', 'XERO_ALLOWED_TENANT_NAMES', 'XERO_REQUIRE_DEMO_ORG', 'XERO_TENANT_ID', 'XERO_DAILY_BATCH_LIMIT', 'PRODUCER_HOLD_ENFORCED_DESTINATIONS',
    'CONNECTOR_FETCH_TIMEOUT_MS', 'CONNECTOR_FETCH_MAX_RESPONSE_BYTES', 'DATABASE_RESTORE_MAX_FILE_BYTES', 'SHOPPING_WEBHOOK_MAX_BODY_BYTES', 'SHOPPING_WEBHOOK_READ_TIMEOUT_MS', 'XERO_ACCOUNTING_OUTBOX_ENABLED', 'FRESH_AUTH_MAX_AGE_SECONDS', 'INVOICE_PDF_TOKEN_TTL_SECONDS', 'INVOICE_PDF_TOKEN_MAX_TTL_SECONDS']
  assert.deepEqual(loosensWhenAbsent.filter((k) => !security.has(k)), [], 'every guard whose absence loosens it is a security setting')
})

// ---------------------------------------------------------------------------
// review round 7: the screen looks through ANY chain of reversible encodings
// ---------------------------------------------------------------------------

function seeded(seed: number): () => number {
  let a = seed >>> 0
  return () => {
    a = (a + 0x6d2b79f5) >>> 0
    let t = a
    t = Math.imul(t ^ (t >>> 15), t | 1)
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61)
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}
const ENCODERS: Record<string, (s: string, rnd: () => number) => string> = {
  // one hex-digit case per encoded string (a layer written by a tool is consistent; the screen covers both)
  percent: (s, rnd) => { const up = rnd() < 0.5; return [...Buffer.from(s)].map((b) => '%' + (up ? b.toString(16).toUpperCase().padStart(2, '0') : b.toString(16).padStart(2, '0'))).join('') },
  hex: (s, rnd) => (rnd() < 0.5 ? Buffer.from(s).toString('hex') : Buffer.from(s).toString('hex').toUpperCase()),
  base64: (s) => Buffer.from(s).toString('base64'),
  base64url: (s) => Buffer.from(s).toString('base64url'),
  base64nopad: (s) => Buffer.from(s).toString('base64').replace(/=+$/, ''),
}
const shq = (v: string) => `'${v.replace(/'/g, "'\\''")}'`

test('re-run: PROPERTY — a chain of 1-6 random layers (percent, hex, base64, base64url, unpadded) over the admin password is refused, whatever the order', () => {
  const passwords = ['Admin1234', 'ABCDEFGH', 'Zx9#kLm2', 'p@ss w0rd!', 'correct-horse-battery']
  const rnd = seeded(20261009)
  const names = Object.keys(ENCODERS)
  const cases: Array<{ pw: string; chain: string[]; value: string }> = []
  for (const pw of passwords) {
    for (let n = 0; n < 48; n++) {
      const depth = 1 + (n % 6)
      const chain: string[] = []
      let v = pw
      for (let d = 0; d < depth; d++) {
        const enc = names[Math.floor(rnd() * names.length)]
        chain.push(enc)
        v = ENCODERS[enc](v, rnd)
      }
      cases.push({ pw, chain, value: v })
    }
  }
  const lines = [LIB]
  cases.forEach((c, i) => {
    lines.push(`DEPLOY_ADMIN_DATABASE_URL=${shq(`postgresql://deployadmin:${c.pw.replace(/[^A-Za-z0-9]/g, (ch) => '%' + ch.charCodeAt(0).toString(16).toUpperCase().padStart(2, '0'))}@127.0.0.1:5432/db`)}`)
    lines.push(`env_key_carry_check XERO_ALLOWED_TENANT_NAMES ${shq(c.value)}; echo "${i} RC=$? $ENV_REFUSAL_REASON"`)
  })
  const r = bash(lines.join('\n'))
  const results = new Map(r.out.split('\n').filter((l) => /^\d+ RC=/.test(l)).map((l) => [Number(l.split(' ')[0]), l.slice(l.indexOf(' ') + 1)]))
  const miss = cases.filter((c, i) => results.get(i) !== "RC=1 the value contains the deploy admin's password")
  console.log(`  ${cases.length} generated chains over ${passwords.length} passwords (depth 1-6): ${cases.length - miss.length} refused, ${miss.length} passed`)
  assert.deepEqual(miss.slice(0, 3).map((c) => [c.pw, c.chain.join('>')]), [])
  assert.equal(results.size, cases.length)
})

test('re-run: the exact review example (double base64 of Admin1234) is refused, and real organisation names are carried', () => {
  const dbl = Buffer.from(Buffer.from('Admin1234').toString('base64')).toString('base64')
  assert.equal(dbl, 'UVdSdGFXNHhNak0w')
  const decide = (v: string) => bash([LIB, "DEPLOY_ADMIN_DATABASE_URL='postgresql://deployadmin:Admin1234@127.0.0.1:5432/db'", `env_preserve_decision XERO_ALLOWED_TENANT_NAMES ${shq(v)}; echo "RC=$? [$ENV_REFUSAL_REASON]"`].join('\n')).out.trim().split('\n').pop()
  assert.equal(decide(dbl), "RC=1 [the value contains the deploy admin's password]")
  for (const name of ['OneTwo3D Ltd', 'Acme-Widgets', 'Demo Company (UK)', "Smith & Sons, O'Neil Trading", 'Acme-Widgets, OneTwo3D Ltd', 'Production Warehouse']) {
    assert.equal(decide(name), 'RC=0 []', name)
  }
})

test('re-run: the decoder is bounded, and a value still decodable at the bound is refused rather than passed', () => {
  const run = (setup: string, value: string) => bash([LIB, "DEPLOY_ADMIN_DATABASE_URL='postgresql://deployadmin:Admin1234@127.0.0.1:5432/db'", setup, `env_key_carry_check XERO_ALLOWED_TENANT_NAMES ${shq(value)}; echo "RC=$? [$ENV_REFUSAL_REASON] U=$ENV_DECODE_UNBOUNDED"`].join('\n')).out.trim().split('\n').pop()
  let v = 'Admin1234'
  for (let i = 0; i < 12; i++) v = Buffer.from(v).toString('base64')
  // twelve layers: beyond the shipped depth of 10
  assert.match(String(run(':', v)), /^RC=1 \[the value is encoded too deeply to screen for the deploy admin's password\] U=1$/)
  // inside the depth bound the same construction is found as the password
  let w = 'Admin1234'
  for (let i = 0; i < 6; i++) w = Buffer.from(w).toString('base64')
  assert.match(String(run(':', w)), /^RC=1 \[the value contains the deploy admin's password\]/)
  // the total-work bound: a tiny budget refuses a chain that fits the depth
  assert.match(String(run('ENV_DECODE_MAX_WORK=40', w)), /encoded too deeply.*U=1$/)
  // an ordinary value is never "too deep"
  assert.match(String(run('ENV_DECODE_MAX_DEPTH=2', 'OneTwo3D Ltd')), /^RC=0 \[\] U=0$/)
  console.log(`  limits: depth 10 / work ${/^ENV_DECODE_MAX_WORK=(\d+)/m.exec(INSTALL)?.[1]} decoded characters`)
})

// ---------------------------------------------------------------------------
// the closed census: every environment variable the code reads is either set by the template, carried, or
// deliberately not carried with a reason
// ---------------------------------------------------------------------------

/** Environment variables read by the code that a re-run deliberately does NOT carry, each with the reason. */
const NOT_CARRIED: Record<string, string> = {
  // secrets and credentials: copied from the root-only backup by an operator who needs them
  ANTHROPIC_API_KEY: 'secret',
  ENCRYPTION_KEY: 'secret',
  NEXTAUTH_SECRET: 'secret (legacy name)',
  INTEGRATION_CONNECTION_FINGERPRINT_KEY: 'secret',
  XERO_AUDIT_CLIENT_ID: 'credential of a one-off audit script',
  XERO_AUDIT_CLIENT_SECRET: 'secret of a one-off audit script',
  // database connection settings: never carried (admin-credential rule)
  DEPLOY_ADMIN_DATABASE_URL: 'admin credential, never written to .env',
  DIRECT_URL: 'database connection setting',
  SOURCE_DATABASE_URL: 'database connection of a one-off copy script',
  STAGE_DATABASE_URL: 'database connection of a one-off stage script',
  // set by the platform, the shell or CI, not by .env
  CI: 'CI', GITHUB_BASE_REF: 'CI', GITHUB_EVENT_NAME: 'CI', GITHUB_EVENT_PATH: 'CI',
  HOME: 'ambient', PATH: 'ambient', USER: 'ambient', SUDO_USER: 'ambient', NODE_OPTIONS: 'ambient', STATE_DIRECTORY: 'systemd',
  NEXT_RUNTIME: 'set by Next.js',
  COMMIT_SHA: 'build identity, set at build/deploy', GIT_COMMIT_SHA: 'build identity', SOURCE_VERSION: 'build identity', VERCEL_GIT_COMMIT_SHA: 'build identity',
  // development and repository tooling, not read by an installed instance
  ARCHIVE_SEAL_BASE_REF: 'repo tooling', ARCHIVE_SEAL_MANIFEST: 'repo tooling', ARCHIVE_SEAL_REF: 'repo tooling', ARCHIVE_SEAL_REWRITE: 'repo tooling',
  MIGRATION_CONVENTION_BASE_REF: 'repo tooling', MIGRATION_CONVENTION_HEAD_REF: 'repo tooling', SCHEMA_CHECK_BASE_REF: 'repo tooling', SCHEMA_CHECK_HEAD_REF: 'repo tooling',
  SCHEMA_SCOPE_BASE_REF: 'repo tooling', SCHEMA_SCOPE_HEAD_REF: 'repo tooling', PRISMA_DRIFT_ALLOWLIST: 'repo tooling', PRISMA_MIGRATIONS_DIR: 'repo tooling', PRISMA_SCHEMA_PATH: 'repo tooling',
  IMS_VERIFY_COVERAGE_STRICT: 'CI strictness flag of the verification runner', IMS_CHOWN_TREE_ROOT: 'test seam of the installer helper',
  RUN_DB_CONCURRENCY_TESTS: 'test switch', E2E_BASE_URL: 'test', E2E_CRON_RATE_LIMIT_MAX: 'test', E2E_ROUTE_SECRET: 'test', E2E_TEST_MODE: 'test (must never be on in production)',
  REHEARSAL_SEED_USD_RATE: 'rehearsal tooling',
  // cutover tooling paths: written by the cutover scripts, not by an operator
  OTI_CRONTAB_LOCK_PATH: 'cutover tooling path', OTI_CRONTAB_LOCK_WAIT_MS: 'cutover tooling', OTI_CRON_LOG_PATH: 'cutover tooling path', OTI_CUTOVER_STATE_ROOT: 'cutover tooling path',
  // loosening settings whose absence TIGHTENS: dropping is fail-closed, the value stays in the backup
  CONNECTOR_PRIVATE_IP_ALLOWLIST: 'allows connector calls to private addresses; absent = stricter, so a drop is fail-closed',
}

test('re-run: CENSUS — every environment variable the code reads is set by the template, on the carry list, or deliberately not carried (and the table is not stale)', () => {
  const read = new Set<string>()
  const re = /process\.env\.([A-Z][A-Z0-9_]+)|process\.env\[['"]([A-Z][A-Z0-9_]+)['"]\]|\benv\.([A-Z][A-Z0-9_]{3,})\b/g
  const walk = (dir: string) => {
    for (const e of readdirSync(dir, { withFileTypes: true })) {
      if (e.name === 'node_modules' || e.name === '.next' || e.name.startsWith('.')) continue
      const full = join(dir, e.name)
      if (e.isDirectory()) walk(full)
      else if (/\.(ts|tsx|mjs|js)$/.test(e.name)) for (const m of readFileSync(full, 'utf8').matchAll(re)) read.add(m[1] ?? m[2] ?? m[3])
    }
  }
  for (const d of ['lib', 'app', 'scripts']) walk(join(process.cwd(), d))
  const template = new Set((/^ENV_TEMPLATE_KEYS=\((.*)\)$/m.exec(INSTALL)?.[1] ?? '').split(/\s+/).filter(Boolean))
  const carried = new Set([...(/^declare -A ENV_PRESERVE_SHAPES=\(([\s\S]*?)^\)$/m.exec(INSTALL)?.[1] ?? '').matchAll(/\[([A-Z0-9_]+)\]=/g)].map((m) => m[1]))
  const unclassified = [...read].filter((n) => !template.has(n) && !carried.has(n) && !(n in NOT_CARRIED)).sort()
  const stale = Object.keys(NOT_CARRIED).filter((n) => !read.has(n)).sort()
  console.log(`  census: ${read.size} environment variables read in lib/ app/ scripts/; ${[...read].filter((n) => template.has(n)).length} set by the template, ${[...read].filter((n) => carried.has(n)).length} carried, ${[...read].filter((n) => n in NOT_CARRIED).length} deliberately not carried`)
  assert.deepEqual(unclassified, [], 'a variable read in code is on none of: the template, the carry list, NOT_CARRIED (decide, with a reason)')
  assert.deepEqual(stale, [], 'NOT_CARRIED lists a name nothing reads any more')
  // (A carried name may be read through a helper this pattern does not see, so the reverse direction is not asserted.)
})

// ---------------------------------------------------------------------------
// review round 8: an encoding EMBEDDED in longer text
// ---------------------------------------------------------------------------

const ENC2: Record<string, (s: string, rnd: () => number) => string> = {
  ...ENCODERS,
  percentmin: (s, rnd) => { const up = rnd() < 0.5; return [...Buffer.from(s)].map((b) => (/[A-Za-z0-9._~-]/.test(String.fromCharCode(b)) ? String.fromCharCode(b) : '%' + (up ? b.toString(16).toUpperCase().padStart(2, '0') : b.toString(16).padStart(2, '0')))).join('') },
  plusmin: (s, rnd) => ENC2.percentmin(s, rnd).replace(/%20/g, '+'),
}

test('re-run: an encoding of the admin password EMBEDDED in longer text (prefix, suffix, separators) is refused -- the exact example and a generated census over compositions up to depth 3', () => {
  const ADMIN = 'postgresql://deployadmin:Admin1234@127.0.0.1:5432/db'
  const decideOne = (key: string, v: string) => bash([LIB, `DEPLOY_ADMIN_DATABASE_URL=${shq(ADMIN)}`, `env_preserve_decision ${key} ${shq(v)}; echo "RC=$? [$ENV_REFUSAL_REASON]"`].join('\n')).out.trim().split('\n').pop()
  assert.equal(Buffer.from('xQWRtaW4xMjM0').length > 0, true)
  assert.equal(decideOne('XERO_ALLOWED_TENANT_NAMES', 'xQWRtaW4xMjM0'), "RC=1 [the value contains the deploy admin's password]")

  const passwords = ['Admin1234', 'ABCDEFGH', 'Zx9#kLm2', 'p@ss w0rd!', 'correct-horse-battery', '>>??>>??>>']
  const rnd = seeded(20261010)
  const names = Object.keys(ENC2)
  const filler = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 ,;|.-_/+'
  const pad = () => Array.from({ length: Math.floor(rnd() * 7) }, () => filler[Math.floor(rnd() * filler.length)]).join('')
  const cases: Array<{ pw: string; chain: string[]; value: string }> = []
  const build = (pw: string, chain: string[]) => {
    // The password may itself sit inside longer text at ANY level before an encoding (that shifts the base64 alignment),
    // and the final encoding sits inside longer text too.
    const padAt = Math.floor(rnd() * (chain.length + 1))
    let v = pw
    chain.forEach((e, i) => {
      if (i === padAt) v = pad() + v + pad()
      v = ENC2[e](v, rnd)
    })
    if (padAt === chain.length) v = pad() + v + pad()
    cases.push({ pw, chain: [...chain, `pad@${padAt}`], value: pad() + v + pad() })
  }
  for (const pw of passwords) {
    for (const a of names) build(pw, [a])
    for (const a of names) for (const b of names) build(pw, [a, b])
    for (let n = 0; n < 40; n++) build(pw, [0, 1, 2].map(() => names[Math.floor(rnd() * names.length)]))
  }
  const lines = [LIB]
  let current = ''
  cases.forEach((c, i) => {
    if (c.pw !== current) {
      current = c.pw
      lines.push(`DEPLOY_ADMIN_DATABASE_URL=${shq(`postgresql://deployadmin:${c.pw.replace(/[^A-Za-z0-9]/g, (ch) => '%' + ch.charCodeAt(0).toString(16).toUpperCase().padStart(2, '0'))}@127.0.0.1:5432/db`)}`)
    }
    lines.push(`env_key_carry_check XERO_ALLOWED_TENANT_NAMES ${shq(c.value)}; echo "${i} RC=$? $ENV_REFUSAL_REASON"`)
  })
  const r = bash(lines.join('\n'))
  const results = new Map(r.out.split('\n').filter((l) => /^\d+ RC=/.test(l)).map((l) => [Number(l.split(' ')[0]), l.slice(l.indexOf(' ') + 1)]))
  const miss = cases.filter((c, i) => results.get(i) !== "RC=1 the value contains the deploy admin's password")
  console.log(`  ${cases.length} embedded compositions (depth 1-3, random 0-6 character prefix/suffix) over ${passwords.length} passwords: ${cases.length - miss.length} refused, ${miss.length} passed`)
  assert.deepEqual(miss.slice(0, 12).map((c) => [c.pw, c.chain.join('>'), c.value, results.get(cases.indexOf(c))]), [])
  assert.equal(results.size, cases.length)
})

test('re-run: the needle set is bounded, small, and the name shape stays closed', () => {
  const run = (setup: string, key: string, value: string, pw = 'p@ss w0rd!#Zx') => bash([LIB, `DEPLOY_ADMIN_DATABASE_URL='postgresql://deployadmin:${pw.replace(/[^A-Za-z0-9]/g, (c) => '%' + c.charCodeAt(0).toString(16).toUpperCase().padStart(2, '0'))}@127.0.0.1:5432/db'`, setup, `env_preserve_decision ${key} ${shq(value)}; echo "RC=$? [$ENV_REFUSAL_REASON] N=\${#ENV_NEEDLES[@]} O=$ENV_NEEDLES_OVERFLOW"`].join('\n')).out.trim().split('\n').pop() ?? ''
  const worst = run(':', 'XERO_ALLOWED_TENANT_NAMES', 'OneTwo3D Ltd')
  const n = Number(/N=(\d+)/.exec(worst)?.[1])
  console.log(`  needle count for a punctuation-and-space password: ${n} (bound ${/^ENV_NEEDLE_MAX=(\d+)/m.exec(INSTALL)?.[1]})`)
  assert.ok(n > 100 && n < 2000)
  assert.match(worst, /^RC=0 \[\]/)
  assert.match(run('ENV_NEEDLE_MAX=20', 'XERO_ALLOWED_TENANT_NAMES', 'OneTwo3D Ltd'), /^RC=1 \[the value cannot be screened for the deploy admin's password .*O=1$/)
  for (const name of ['OneTwo3D Ltd', 'Acme-Widgets', 'Demo Company (UK)', "Smith & Sons, O'Neil Trading", 'Production Warehouse', 'Acme-Widgets, OneTwo3D Ltd']) {
    assert.match(run(':', 'XERO_ALLOWED_TENANT_NAMES', name), /^RC=0 \[\]/, name)
  }
  assert.match(run(':', 'XERO_ALLOWED_TENANT_NAMES', 'A'.repeat(60) + ',' + 'B'.repeat(61)), /^RC=1 \[the value does not have the shape of a names setting\]/)
  assert.match(run(':', 'XERO_ALLOWED_TENANT_NAMES', 'A'.repeat(59) + ',' + 'B'.repeat(60)), /^RC=0 /)
  for (const bad of ['Acme!Widgets', 'Acme@Widgets', 'Acme=1', 'Acme%41']) assert.match(run(':', 'XERO_ALLOWED_TENANT_NAMES', bad), /^RC=1 /, bad)
})
